workspace(
    name = "jvolkman_rules_pycross_example",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

rules_foreign_cc_commit = "0ed27c13b18f412e00e9122fc01327503d52579c"

http_archive(
    name = "rules_foreign_cc",
    sha256 = "c7913eb3ce2e9fea0e1b2ba65c51114ea66a524d20d974f720a9baa5cbbb2ab3",
    strip_prefix = "rules_foreign_cc-%s" % rules_foreign_cc_commit,
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/%s.tar.gz" % rules_foreign_cc_commit,
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

# This sets up some common toolchains for building targets. For more details, please see
# https://bazelbuild.github.io/rules_foreign_cc/0.9.0/flatten.html#rules_foreign_cc_dependencies
rules_foreign_cc_dependencies()

http_archive(
    name = "rules_python",
    sha256 = "497ca47374f48c8b067d786b512ac10a276211810f4a580178ee9b9ad139323a",
    strip_prefix = "rules_python-0.16.1",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.16.1.tar.gz",
)

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python3_10",
    # Available versions are listed in @rules_python//python:versions.bzl.
    # We recommend using the same version your team is already standardized on.
    python_version = "3.10",
)

load("@python3_10//:defs.bzl", "interpreter")

local_repository(
    name = "jvolkman_rules_pycross",
    path = "../..",
)

load("@jvolkman_rules_pycross//pycross:repositories.bzl", "rules_pycross_dependencies")

rules_pycross_dependencies(python_interpreter_target = interpreter)

http_archive(
    name = "bazel-zig-cc",
    sha256 = "b23d2a47bc79fa7d60f2ef3f18fb204f178029da824dc3c7462c5e87cd284635",
    strip_prefix = "bazel-zig-cc-9d9dc016ef9b7995af0bef45ef8a6dc55993cb25",
    urls = ["https://github.com/uber/bazel-zig-cc/archive/9d9dc016ef9b7995af0bef45ef8a6dc55993cb25.tar.gz"],
)

load(
    "@bazel-zig-cc//toolchain:defs.bzl",
    "URL_FORMAT_NIGHTLY",
    zig_toolchains = "toolchains",
)

zig_version = "0.11.0-dev.2191+30427ff79"

zig_host_platform_sha256 = {
    "linux-aarch64": "0dc1f989bc2e627ec37da25242d29a2a5f5ebbf0b67ffecfdcb26b99708f9eff",
    "linux-x86_64": "66e024a67da49d743c5cf9cd9467d5b64fa9e4f1fdf0bb03523bf9e355e56ef2",
    "macos-aarch64": "bd2c7e8f9a2dd0b63ca6b425cc0a9bf482ff66ce8c704efc73900945e7c74529",
    "macos-x86_64": "d4eecf7f0b15913b7d2cace9b1a328d9cf04da7cee7be3d61ae47ae137af156c",
}

zig_toolchains(
    host_platform_sha256 = zig_host_platform_sha256,
    url_formats = [
        URL_FORMAT_NIGHTLY,
    ],
    version = zig_version,
)

register_toolchains(
    "@zig_sdk//toolchain:linux_amd64_gnu.2.24",
    "@zig_sdk//toolchain:linux_arm64_gnu.2.24",
    "@zig_sdk//toolchain:darwin_amd64",
    "@zig_sdk//toolchain:darwin_arm64",
)

register_toolchains(
    "//:pycross_darwin_linux_tc",
    "//:pycross_linux_darwin_tc",
    "//:pycross_linux_x86_64_linux_arm64_tc",
)

load("//:example_lock.bzl", "repositories")
repositories()

load("//third_party:repositories.bzl", third_party_repositories = "repositories")
third_party_repositories()

load("//third_party:setup.bzl", third_party_setup = "setup")
third_party_setup()
