workspace(
    name = "rules_pycross_example",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "d71d2c67e0bce986e1c5a7731b4693226867c45bfe0b7c5e0067228a536fc580",
    strip_prefix = "rules_python-0.29.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.29.0/rules_python-0.29.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_multi_toolchains")

py_repositories()

python_register_multi_toolchains(
    name = "python",
    default_version = "3.10.12",
    python_versions = [
        "3.10.12",
    ],
)

load("@python//3.10.12:defs.bzl", python_interpreter = "interpreter")

local_repository(
    name = "rules_pycross",
    path = "../..",
)

load("@rules_pycross//pycross:repositories.bzl", "rules_pycross_dependencies")

rules_pycross_dependencies(
    python_interpreter_target = python_interpreter,
)

load(
    "@rules_pycross//pycross:workspace.bzl",
    "lock_repo_model_pdm",
    "pycross_lock_repo",
    "pycross_register_for_python_toolchains",
)

pycross_register_for_python_toolchains(
    name = "pycross_toolchains",
    python_toolchains_repo = "@python",
)

load("@pycross_toolchains//:defs.bzl", "environments")

pycross_lock_repo(
    name = "pdm",
    lock_model = lock_repo_model_pdm(
        lock_file = "@//:pdm.lock",
        project_file = "@//:pyproject.toml",
    ),
    target_environments = environments,
)

load("@pdm//:defs.bzl", "install_deps")

install_deps()
