workspace(
    name = "rules_pycross_example",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "9c6e26911a79fbf510a8f06d8eedb40f412023cf7fa6d1461def27116bff022c",
    strip_prefix = "rules_python-1.1.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/1.1.0/rules_python-1.1.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_multi_toolchains")

py_repositories()

python_register_multi_toolchains(
    name = "python",
    default_version = "3.12",
    python_versions = [
        "3.10",
        "3.11",
        "3.12",
    ],
)

local_repository(
    name = "rules_pycross",
    path = "../..",
)

load("@rules_pycross//pycross:repositories.bzl", "rules_pycross_dependencies")

rules_pycross_dependencies(
    python_interpreter_target = "@python_3_12_host//:python",
)

load(
    "@rules_pycross//pycross:workspace.bzl",
    "lock_repo_model_pdm",
    "pycross_lock_repo",
    "pycross_register_for_python_toolchains",
)

pycross_register_for_python_toolchains(
    name = "pycross_toolchains",
    platforms = [
        "aarch64-apple-darwin",
        "aarch64-unknown-linux-gnu",
        "x86_64-unknown-linux-gnu",
    ],
    python_toolchains_repo = "@python",
)

load("@pycross_toolchains//:defs.bzl", "environments")
load("@rules_pycross//pycross:defs.bzl", "package_annotation")

pycross_lock_repo(
    name = "pdm",
    annotations = {
        "amqp-mock": package_annotation(
            install_exclude_globs = [
                "tests/**",
            ],
        ),
        "grpclib": package_annotation(
            always_build = True,
            build_dependencies = [
                "setuptools",
                "wheel",
            ],
        ),
    },
    lock_model = lock_repo_model_pdm(
        lock_file = "@//:pdm.lock",
        project_file = "@//:pyproject.toml",
    ),
    target_environments = environments,
)

load("@pdm//:defs.bzl", "install_deps")

install_deps()
