workspace(
    name = "jvolkman_rules_pycross_example",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "9fcf91dbcc31fde6d1edb15f117246d912c33c36f44cf681976bd886538deba6",
    strip_prefix = "rules_python-0.8.0",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.8.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python3_9",
    # Available versions are listed in @rules_python//python:versions.bzl.
    # We recommend using the same version your team is already standardized on.
    python_version = "3.9",
)

load("@python3_9//:defs.bzl", "interpreter")

local_repository(
    name = "jvolkman_rules_pycross",
    path = "..",
)

load("@jvolkman_rules_pycross//pycross:repositories.bzl", "rules_pycross_dependencies")
rules_pycross_dependencies()

http_archive(
    name = "aspect_rules_py",
    url = "https://github.com/aspect-build/rules_py/archive/9a8e2e5d15e3376a2ebac2278dd904dc24cbccb8.tar.gz",
    strip_prefix = "rules_py-9a8e2e5d15e3376a2ebac2278dd904dc24cbccb8",
    sha256 = "b4dae72a1d552b15f6a2b6d45f37a7a326677a52cfc77358f739ba467bc88531",
)

load("@aspect_rules_py//py:repositories.bzl", "rules_py_dependencies")
rules_py_dependencies()

load("@jvolkman_rules_pycross//pycross:defs.bzl", "pycross_lock_repo")
pycross_lock_repo(
    name = "example_lock_repo",
    lock_file = "//:example_lock.bzl"
)

load("@example_lock_repo//:requirements.bzl", "install_deps")
install_deps()
