load("@gazelle//:def.bzl", "gazelle")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")
load("@rules_python_gazelle_plugin//manifest:defs.bzl", "gazelle_python_manifest")

# Tell gazelle about python packages
gazelle_python_manifest(
    name = "gazelle_python_manifest",
    modules_mapping = "@uv//:modules_mapping",
    pip_repository_name = "uv",
)

# gazelle:python_extension enabled
# gazelle:python_root //
gazelle(
    name = "gazelle",
    gazelle = "@rules_python_gazelle_plugin//python:gazelle_binary",
)

py_binary(
    name = "test",
    srcs = ["test.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@uv//python_dateutil",
        "@uv//requests",
    ],
)

py_library(
    name = "gazelle_integration",
    srcs = ["test.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@uv//python_dateutil",
        "@uv//requests",
    ],
)
