[project]
name = "rules-pycross-test"
version = "0.1.0"
description = ""
requires-python = ">=3.9, <3.13"
dependencies = [
    "regex>=2024.11.6",
    "setuptools>=75.6.0",
    "wheel>=0.45.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
