"""Generates a resolved pycross TOML lock file from a raw lock model."""

from pathlib import Path
from typing import Any

import tomli_w
from pycross.private.tools import raw_lock_resolver
from pycross.private.tools.args import FlagFileArgumentParser


def parse_flags() -> Any:
    parser = FlagFileArgumentParser(description="Generate pycross dependency TOML lock file.")
    raw_lock_resolver.add_shared_flags(parser)
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="The path to the output TOML file.",
    )

    return parser.parse_args()


def sanitize_name(val):
    return val.lower().replace("-", "_").replace(".", "_").replace("+", "_").replace("@", "_").replace("!", "_")


def main(args: Any) -> None:
    resolved_lock = raw_lock_resolver.resolve(args)

    lock_dict = {"pins": {}, "packages": {}}

    # Sort pins deterministically
    def _format_pin(v):
        if "" in v and len(v) == 1:
            return str(v[""])
        return {k: str(val) for k, val in v.items()}

    lock_dict["pins"] = {str(k): _format_pin(v) for k, v in sorted(resolved_lock.pins.items())}

    packages_dict = {}
    for pkg_key, pkg in sorted(resolved_lock.packages.items()):
        # Find the unique remote file associated with this package.
        repo_name = None
        filename = None
        sha256 = None
        url = None

        # Collect remote files from wheel candidates
        for candidate in pkg.wheel_candidates:
            file_ref = candidate.file_reference
            if file_ref.key:
                file_info = resolved_lock.remote_files.get(file_ref.key)
                if file_info:
                    filename = file_info.name
                    sha256 = file_info.sha256
                    url = file_info.urls[0]

                    # Recreate Bzlmod repo name mapping:
                    key_str = str(file_ref.key)
                    repo_name = "pypi_{}".format(sanitize_name(key_str.replace("/", "_")))
                    break

        # Also check sdist_file if no wheel candidate matched
        if not repo_name and pkg.sdist_file and pkg.sdist_file.key:
            file_info = resolved_lock.remote_files.get(pkg.sdist_file.key)
            if file_info:
                filename = file_info.name
                sha256 = file_info.sha256
                url = file_info.urls[0]
                key_str = str(pkg.sdist_file.key)
                repo_name = "pypi_{}".format(sanitize_name(key_str.replace("/", "_")))

        if not repo_name:
            continue

        # Collect all dependency keys from marker_dependencies
        deps = []
        for md in pkg.marker_dependencies:
            dep_dict = {"key": str(md.key)}
            if md.marker:
                dep_dict["marker"] = md.marker
            deps.append(dep_dict)

        pkg_dict = {
            "name": str(pkg.key.name),
            "version": str(pkg.key.version),
            "repo_name": repo_name,
            "url": url,
            "sha256": sha256,
            "filename": filename,
        }

        if deps:
            pkg_dict["deps"] = sorted(deps, key=lambda x: x["key"])

        packages_dict[str(pkg_key)] = pkg_dict

    lock_dict["packages"] = packages_dict

    # Serialize using tomli-w!
    toml_content = tomli_w.dumps(lock_dict)

    header = "# Generated by toml_lock_generator.py.\n# Do not edit manually.\n\n"

    with open(args.output, "w") as f:
        f.write(header + toml_content)


if __name__ == "__main__":
    main(parse_flags())
