load("//shared:collect_wheels.bzl", "collect_wheels")

collect_wheels(
    name = "all_wheels",
    platforms = [
        "@llvm//platforms:linux_aarch64",
        "@llvm//platforms:linux_x86_64",
        "@llvm//platforms:macos_aarch64",
        "//shared:linux_x86_64_musl",
    ],
    wheels = [
        "@uv//contourpy:wheel",
        "@uv//numpy:wheel",
        "@uv//pandas:wheel",
        "@uv//pywavelets:wheel",
    ],
)
