workspace(
    name = "jvolkman_rules_pycross_example",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "56dc7569e5dd149e576941bdb67a57e19cd2a7a63cc352b62ac047732008d7e1",
    strip_prefix = "rules_python-0.10.0",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.10.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python3_9",
    # Available versions are listed in @rules_python//python:versions.bzl.
    # We recommend using the same version your team is already standardized on.
    python_version = "3.9",
)

load("@python3_9//:defs.bzl", "interpreter")

local_repository(
    name = "jvolkman_rules_pycross",
    path = "../..",
)

load("@jvolkman_rules_pycross//pycross:repositories.bzl", "rules_pycross_dependencies")

rules_pycross_dependencies()

load("@jvolkman_rules_pycross//pycross:defs.bzl", "pycross_lock_repo")

pycross_lock_repo(
    name = "example_lock_repo",
    lock_file = "//:example_lock.bzl",
)

load("@example_lock_repo//:requirements.bzl", "install_deps")

install_deps()

# Setup a CC toolchain using bazel-zig-cc
# https://git.sr.ht/~motiejus/bazel-zig-cc
BAZEL_ZIG_CC_VERSION = "956711690f37d31478494dd1d95ee131dcbbcf24"

http_archive(
    name = "bazel-zig-cc",
    sha256 = "440275ae908d95e8c0fbcd3ce9a489c5045c9270f418d5dafe9270bd54c9ef99",
    strip_prefix = "bazel-zig-cc-{}".format(BAZEL_ZIG_CC_VERSION),
    urls = ["https://git.sr.ht/~motiejus/bazel-zig-cc/archive/{}.tar.gz".format(BAZEL_ZIG_CC_VERSION)],
)

load(
    "@bazel-zig-cc//toolchain:defs.bzl",
    "URL_FORMAT_JAKSTYS",
    "URL_FORMAT_NIGHTLY",
    zig_toolchains = "toolchains",
)

zig_version = "0.10.0-dev.2793+7cc417644"

zig_host_platform_sha256 = {
    "linux-aarch64": "329ffdc7570ab87ca62ce7323b3d07a55986284e787e8c446fad955cc377a540",
    "linux-x86_64": "7a53999f1f8d5a1b91a406de9195c33ecc4f8827f62b9cdabf25cf805ad7b814",
    "macos-aarch64": "664ff988fa9acad0f04879b926a6e22763e6536abc770fde1cc7f9f470e893bc",
    "macos-x86_64": "2e2a6e3155afdbf1d9a8a953102a569d6ce8228025f0d36355836a63a11146d7",
}

zig_toolchains(
    host_platform_sha256 = zig_host_platform_sha256,
    url_formats = [
        URL_FORMAT_NIGHTLY,
        URL_FORMAT_JAKSTYS,
    ],
    version = zig_version,
)

register_toolchains(
    "@zig_sdk//toolchain:linux_amd64_gnu.2.19",
    "@zig_sdk//toolchain:linux_arm64_gnu.2.28",
    "@zig_sdk//toolchain:darwin_amd64",
    "@zig_sdk//toolchain:darwin_arm64",
)
