[project]
name = "uv-forked-build-tools-test"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "six==1.17.0",
    "setuptools==68.0.0; python_version < '3.12'",
    "setuptools==75.6.0; python_version >= '3.12'",
    "wheel==0.45.1",
]

[tool.uv]
environments = [
    "python_version < '3.12'",
    "python_version >= '3.12'",
]
