load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

exports_files([
    "collect_wheels.bzl",
    "cowsay-6.1-py3-none-any.whl",
    "ipython.py",
    "test_cowsay.py",
    "test_dist_info.py",
    "test_freethreaded.py",
    "test_precompile.py",
    "test_regex.py",
    "test_top_level_packages.py",
])

py_binary(
    name = "collect_wheels_tool",
    srcs = ["collect_wheels.py"],
    main = "collect_wheels.py",
    visibility = ["//visibility:public"],
)

# musl target platform. rules_python must select the musl target Python, or wheels are tagged
# manylinux.
platform(
    name = "linux_x86_64_musl",
    flags = ["--@rules_python//python/config_settings:py_linux_libc=musl"],
    parents = ["@llvm//platforms:linux_x86_64_musl"],
)
