bazel_dep(name = "rules_pycross", version = "0.0.0")
bazel_dep(name = "rules_pycross_e2e_shared", version = "0.0.0")
bazel_dep(name = "rules_python", version = "2.0.0")

local_path_override(
    module_name = "rules_pycross",
    path = "../../..",
)

local_path_override(
    module_name = "rules_pycross_e2e_shared",
    path = "../shared",
)

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.14.2",
)
use_repo(python, "python_versions")

pylock = use_extension("@rules_pycross//pycross/extensions:pylock.bzl", "pylock")
pylock.workspace(
    name = "graphless_lock",
    lock_file = "//:pylock.toml",
)
pylock.repo(
    workspace = "graphless_lock",
)
use_repo(pylock, "graphless_lock")
