workspace(
    name = "rules_pycross_example",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "9acc0944c94adb23fba1c9988b48768b1bacc6583b52a2586895c5b7491e2e31",
    strip_prefix = "rules_python-0.27.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.27.0/rules_python-0.27.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_multi_toolchains")

py_repositories()

python_register_multi_toolchains(
    name = "python",
    default_version = "3.12",
    python_versions = [
        "3.10",
        "3.11",
        "3.12",
    ],
)

load("@python//3.12:defs.bzl", python_interpreter = "interpreter")

local_repository(
    name = "rules_pycross",
    path = "../..",
)

load("@rules_pycross//pycross:repositories.bzl", "rules_pycross_dependencies")

rules_pycross_dependencies(
    python_interpreter_target = python_interpreter,
)

load(
    "@rules_pycross//pycross:defs.bzl",
    "pkg_repo_model_pdm",
    "pycross_pkg_repo",
    "pycross_register_for_python_toolchains",
)

pycross_register_for_python_toolchains(
    name = "pycross_toolchains",
    python_toolchains_repo_name = "python",
)

load("@pycross_toolchains//:defs.bzl", "environments")

pycross_pkg_repo(
    name = "pdm",
    lock_model = pkg_repo_model_pdm(
        lock_file = "@//:pdm.lock",
        project_file = "@//:pyproject.toml",
    ),
    target_environments = environments,
)

load("@pdm//:defs.bzl", "install_deps")

install_deps()
