# This file is generated by rules_pycross.
# It is not intended for manual editing.

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@jvolkman_rules_pycross//pycross:defs.bzl", "pycross_wheel_build", "pycross_wheel_library", "pypi_file")

PINS = {
    "annotated_types": "annotated_types_0.6.0",
    "appnope": "appnope_0.1.3",
    "asgiref": "asgiref_3.7.2",
    "asttokens": "asttokens_2.4.1",
    "attrs": "attrs_23.1.0",
    "aws_sam_translator": "aws_sam_translator_1.79.0",
    "aws_xray_sdk": "aws_xray_sdk_2.9.0",
    "black": "black_23.10.1",
    "blinker": "blinker_1.7.0",
    "boto3": "boto3_1.28.80",
    "botocore": "botocore_1.31.80",
    "certifi": "certifi_2023.7.22",
    "cffi": "cffi_1.16.0",
    "cfn_lint": "cfn_lint_0.83.1",
    "charset_normalizer": "charset_normalizer_3.3.2",
    "click": "click_8.1.7",
    "cognitojwt": "cognitojwt_1.4.1",
    "cowsay": "cowsay_6.1",
    "cryptography": "cryptography_41.0.5",
    "cython": "cython_0.29.36",
    "decorator": "decorator_5.1.1",
    "defusedxml": "defusedxml_0.7.1",
    "django": "django_4.2.7",
    "django_allauth": "django_allauth_0.51.0",
    "docker": "docker_6.1.3",
    "ecdsa": "ecdsa_0.18.0",
    "exceptiongroup": "exceptiongroup_1.1.3",
    "executing": "executing_2.0.1",
    "flask": "flask_3.0.0",
    "flask_cors": "flask_cors_4.0.0",
    "future": "future_0.18.3",
    "graphql_core": "graphql_core_3.2.3",
    "greenlet": "greenlet_3.0.1",
    "idna": "idna_3.4",
    "importlib_metadata": "importlib_metadata_6.8.0",
    "ipython": "ipython_8.17.2",
    "itsdangerous": "itsdangerous_2.1.2",
    "jedi": "jedi_0.19.1",
    "jinja2": "jinja2_3.1.2",
    "jmespath": "jmespath_1.0.1",
    "jschema_to_python": "jschema_to_python_1.2.3",
    "jsondiff": "jsondiff_2.0.0",
    "jsonpatch": "jsonpatch_1.33",
    "jsonpickle": "jsonpickle_3.0.2",
    "jsonpointer": "jsonpointer_2.4",
    "jsonschema": "jsonschema_4.19.2",
    "jsonschema_specifications": "jsonschema_specifications_2023.7.1",
    "junit_xml": "junit_xml_1.9",
    "markupsafe": "markupsafe_2.1.3",
    "matplotlib_inline": "matplotlib_inline_0.1.6",
    "moto": "moto_3.1.1",
    "mpmath": "mpmath_1.3.0",
    "mypy_extensions": "mypy_extensions_1.0.0",
    "networkx": "networkx_3.2.1",
    "numpy": "numpy_1.22.3",
    "oauthlib": "oauthlib_3.2.2",
    "packaging": "packaging_23.2",
    "parso": "parso_0.8.3",
    "pathspec": "pathspec_0.11.2",
    "pbr": "pbr_6.0.0",
    "pexpect": "pexpect_4.8.0",
    "platformdirs": "platformdirs_3.11.0",
    "prompt_toolkit": "prompt_toolkit_3.0.39",
    "ptyprocess": "ptyprocess_0.7.0",
    "pure_eval": "pure_eval_0.2.2",
    "pyasn1": "pyasn1_0.5.0",
    "pycparser": "pycparser_2.21",
    "pydantic": "pydantic_2.4.2",
    "pydantic_core": "pydantic_core_2.10.1",
    "pygments": "pygments_2.16.1",
    "pyjwt": "pyjwt_2.8.0",
    "python3_openid": "python3_openid_3.2.0",
    "python_dateutil": "python_dateutil_2.8.2",
    "python_jose": "python_jose_3.1.0",
    "pytz": "pytz_2023.3.post1",
    "pyyaml": "pyyaml_6.0.1",
    "referencing": "referencing_0.30.2",
    "regex": "regex_2023.10.3",
    "requests": "requests_2.31.0",
    "requests_oauthlib": "requests_oauthlib_1.3.1",
    "responses": "responses_0.24.0",
    "rpds_py": "rpds_py_0.12.0",
    "rsa": "rsa_4.9",
    "s3transfer": "s3transfer_0.7.0",
    "sarif_om": "sarif_om_1.0.4",
    "setproctitle": "setproctitle_1.2.2",
    "setuptools": "setuptools_59.2.0",
    "six": "six_1.16.0",
    "sqlalchemy": "sqlalchemy_2.0.23",
    "sqlalchemy_utils": "sqlalchemy_utils_0.38.2",
    "sqlparse": "sqlparse_0.4.4",
    "sshpubkeys": "sshpubkeys_3.3.1",
    "stack_data": "stack_data_0.6.3",
    "sympy": "sympy_1.12",
    "tomli": "tomli_2.0.1",
    "traitlets": "traitlets_5.13.0",
    "tree_sitter": "tree_sitter_0.20.0",
    "typing_extensions": "typing_extensions_4.8.0",
    "urllib3": "urllib3_1.26.18",
    "wcwidth": "wcwidth_0.2.9",
    "websocket_client": "websocket_client_1.6.4",
    "werkzeug": "werkzeug_3.0.1",
    "wheel": "wheel_0.37.0",
    "wrapt": "wrapt_1.15.0",
    "xmltodict": "xmltodict_0.13.0",
    "zipp": "zipp_3.17.0",
}

def targets():
    for pin_name, pin_target in PINS.items():
        native.alias(
            name = pin_name,
            actual = ":" + pin_target,
        )

    native.config_setting(
        name = "_env_python_darwin_arm64",
        constraint_values = [
            "@platforms//os:osx",
            "@platforms//cpu:arm64",
        ],
    )

    native.config_setting(
        name = "_env_python_darwin_x86_64",
        constraint_values = [
            "@platforms//os:osx",
            "@platforms//cpu:x86_64",
        ],
    )

    native.config_setting(
        name = "_env_python_linux_x86_64",
        constraint_values = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    )

    _target = select({
        ":_env_python_darwin_arm64": "@//:python_darwin_arm64",
        ":_env_python_darwin_x86_64": "@//:python_darwin_x86_64",
        ":_env_python_linux_x86_64": "@//:python_linux_x86_64",
    })

    pycross_wheel_library(
        name = "annotated_types_0.6.0",
        wheel = "@example_lock_wheel_annotated_types_0.6.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "appnope_0.1.3",
        wheel = "@example_lock_wheel_appnope_0.1.3_py2.py3_none_any//file",
    )

    _asgiref_3_7_2_deps = [
        ":typing_extensions_4.8.0",
    ]

    pycross_wheel_library(
        name = "asgiref_3.7.2",
        deps = _asgiref_3_7_2_deps,
        wheel = "@example_lock_wheel_asgiref_3.7.2_py3_none_any//file",
    )

    _asttokens_2_4_1_deps = [
        ":six_1.16.0",
    ]

    pycross_wheel_library(
        name = "asttokens_2.4.1",
        deps = _asttokens_2_4_1_deps,
        wheel = "@example_lock_wheel_asttokens_2.4.1_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "attrs_23.1.0",
        wheel = "@example_lock_wheel_attrs_23.1.0_py3_none_any//file",
    )

    _aws_sam_translator_1_79_0_deps = [
        ":boto3_1.28.80",
        ":jsonschema_4.19.2",
        ":pydantic_2.4.2",
        ":typing_extensions_4.8.0",
    ]

    pycross_wheel_library(
        name = "aws_sam_translator_1.79.0",
        deps = _aws_sam_translator_1_79_0_deps,
        wheel = "@example_lock_wheel_aws_sam_translator_1.79.0_py3_none_any//file",
    )

    _aws_xray_sdk_2_9_0_deps = [
        ":botocore_1.31.80",
        ":future_0.18.3",
        ":wrapt_1.15.0",
    ]

    pycross_wheel_library(
        name = "aws_xray_sdk_2.9.0",
        deps = _aws_xray_sdk_2_9_0_deps,
        wheel = "@example_lock_wheel_aws_xray_sdk_2.9.0_py2.py3_none_any//file",
    )

    _black_23_10_1_deps = [
        ":click_8.1.7",
        ":mypy_extensions_1.0.0",
        ":packaging_23.2",
        ":pathspec_0.11.2",
        ":platformdirs_3.11.0",
        ":tomli_2.0.1",
        ":typing_extensions_4.8.0",
    ]

    pycross_wheel_library(
        name = "black_23.10.1",
        deps = _black_23_10_1_deps,
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_black_23.10.1_py3_none_any//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_black_23.10.1_cp39_cp39_macosx_10_16_x86_64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_black_23.10.1_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "blinker_1.7.0",
        wheel = "@example_lock_wheel_blinker_1.7.0_py3_none_any//file",
    )

    _boto3_1_28_80_deps = [
        ":botocore_1.31.80",
        ":jmespath_1.0.1",
        ":s3transfer_0.7.0",
    ]

    pycross_wheel_library(
        name = "boto3_1.28.80",
        deps = _boto3_1_28_80_deps,
        wheel = "@example_lock_wheel_boto3_1.28.80_py3_none_any//file",
    )

    _botocore_1_31_80_deps = [
        ":jmespath_1.0.1",
        ":python_dateutil_2.8.2",
        ":urllib3_1.26.18",
    ]

    pycross_wheel_library(
        name = "botocore_1.31.80",
        deps = _botocore_1_31_80_deps,
        wheel = "@example_lock_wheel_botocore_1.31.80_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "certifi_2023.7.22",
        wheel = "@example_lock_wheel_certifi_2023.7.22_py3_none_any//file",
    )

    _cffi_1_16_0_deps = [
        ":pycparser_2.21",
    ]

    pycross_wheel_library(
        name = "cffi_1.16.0",
        deps = _cffi_1_16_0_deps,
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_cffi_1.16.0_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_cffi_1.16.0_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_cffi_1.16.0_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    _cfn_lint_0_83_1_deps = [
        ":aws_sam_translator_1.79.0",
        ":jschema_to_python_1.2.3",
        ":jsonpatch_1.33",
        ":jsonschema_4.19.2",
        ":junit_xml_1.9",
        ":networkx_3.2.1",
        ":pyyaml_6.0.1",
        ":regex_2023.10.3",
        ":sarif_om_1.0.4",
        ":sympy_1.12",
    ]

    pycross_wheel_library(
        name = "cfn_lint_0.83.1",
        deps = _cfn_lint_0_83_1_deps,
        wheel = "@example_lock_wheel_cfn_lint_0.83.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "charset_normalizer_3.3.2",
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_charset_normalizer_3.3.2_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_charset_normalizer_3.3.2_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_charset_normalizer_3.3.2_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "click_8.1.7",
        wheel = "@example_lock_wheel_click_8.1.7_py3_none_any//file",
    )

    _cognitojwt_1_4_1_deps = [
        ":python_jose_3.1.0",
    ]

    pycross_wheel_library(
        name = "cognitojwt_1.4.1",
        deps = _cognitojwt_1_4_1_deps,
        wheel = "@example_lock_wheel_cognitojwt_1.4.1_py3_none_any//file",
    )

    _cowsay_6_1_build_deps = [
        ":setuptools_59.2.0",
        ":wheel_0.37.0",
    ]

    pycross_wheel_library(
        name = "cowsay_6.1",
        wheel = "@example_lock_wheel_cowsay_6.1_py3_none_any//file",
    )

    _cryptography_41_0_5_deps = [
        ":cffi_1.16.0",
    ]

    pycross_wheel_library(
        name = "cryptography_41.0.5",
        deps = _cryptography_41_0_5_deps,
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_cryptography_41.0.5_cp37_abi3_macosx_10_12_universal2//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_cryptography_41.0.5_cp37_abi3_macosx_10_12_x86_64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_cryptography_41.0.5_cp37_abi3_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "cython_0.29.36",
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_cython_0.29.36_py2.py3_none_any//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_cython_0.29.36_py2.py3_none_any//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_cython_0.29.36_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "decorator_5.1.1",
        wheel = "@example_lock_wheel_decorator_5.1.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "defusedxml_0.7.1",
        wheel = "@example_lock_wheel_defusedxml_0.7.1_py2.py3_none_any//file",
    )

    _django_4_2_7_deps = [
        ":asgiref_3.7.2",
        ":sqlparse_0.4.4",
    ]

    pycross_wheel_library(
        name = "django_4.2.7",
        deps = _django_4_2_7_deps,
        wheel = "@example_lock_wheel_django_4.2.7_py3_none_any//file",
    )

    _django_allauth_0_51_0_deps = [
        ":django_4.2.7",
        ":pyjwt_2.8.0",
        ":python3_openid_3.2.0",
        ":requests_2.31.0",
        ":requests_oauthlib_1.3.1",
    ]

    _django_allauth_0_51_0_build_deps = [
        ":setuptools_59.2.0",
        ":wheel_0.37.0",
    ]

    pycross_wheel_build(
        name = "_build_django_allauth_0.51.0",
        sdist = "@example_lock_sdist_django_allauth_0.51.0//file",
        target_environment = _target,
        deps = _django_allauth_0_51_0_deps + _django_allauth_0_51_0_build_deps,
        tags = ["manual"],
    )

    pycross_wheel_library(
        name = "django_allauth_0.51.0",
        deps = _django_allauth_0_51_0_deps,
        wheel = ":_build_django_allauth_0.51.0",
    )

    _docker_6_1_3_deps = [
        ":packaging_23.2",
        ":requests_2.31.0",
        ":urllib3_1.26.18",
        ":websocket_client_1.6.4",
    ]

    pycross_wheel_library(
        name = "docker_6.1.3",
        deps = _docker_6_1_3_deps,
        wheel = "@example_lock_wheel_docker_6.1.3_py3_none_any//file",
    )

    _ecdsa_0_18_0_deps = [
        ":six_1.16.0",
    ]

    pycross_wheel_library(
        name = "ecdsa_0.18.0",
        deps = _ecdsa_0_18_0_deps,
        wheel = "@example_lock_wheel_ecdsa_0.18.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "exceptiongroup_1.1.3",
        wheel = "@example_lock_wheel_exceptiongroup_1.1.3_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "executing_2.0.1",
        wheel = "@example_lock_wheel_executing_2.0.1_py2.py3_none_any//file",
    )

    _flask_3_0_0_deps = [
        ":blinker_1.7.0",
        ":click_8.1.7",
        ":importlib_metadata_6.8.0",
        ":itsdangerous_2.1.2",
        ":jinja2_3.1.2",
        ":werkzeug_3.0.1",
    ]

    pycross_wheel_library(
        name = "flask_3.0.0",
        deps = _flask_3_0_0_deps,
        wheel = "@example_lock_wheel_flask_3.0.0_py3_none_any//file",
    )

    _flask_cors_4_0_0_deps = [
        ":flask_3.0.0",
    ]

    pycross_wheel_library(
        name = "flask_cors_4.0.0",
        deps = _flask_cors_4_0_0_deps,
        wheel = "@example_lock_wheel_flask_cors_4.0.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "future_0.18.3",
        wheel = "@//deps:overridden_future_0.18.3",
    )

    pycross_wheel_library(
        name = "graphql_core_3.2.3",
        wheel = "@example_lock_wheel_graphql_core_3.2.3_py3_none_any//file",
    )

    _greenlet_3_0_1_build_deps = [
        ":setuptools_59.2.0",
        ":wheel_0.37.0",
    ]

    pycross_wheel_library(
        name = "greenlet_3.0.1",
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_greenlet_3.0.1_cp39_cp39_macosx_10_9_universal2//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_greenlet_3.0.1_cp39_cp39_macosx_10_9_universal2//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_greenlet_3.0.1_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "idna_3.4",
        wheel = "@example_lock_wheel_idna_3.4_py3_none_any//file",
    )

    _importlib_metadata_6_8_0_deps = [
        ":zipp_3.17.0",
    ]

    pycross_wheel_library(
        name = "importlib_metadata_6.8.0",
        deps = _importlib_metadata_6_8_0_deps,
        wheel = "@example_lock_wheel_importlib_metadata_6.8.0_py3_none_any//file",
    )

    _ipython_8_17_2_deps = [
        ":decorator_5.1.1",
        ":exceptiongroup_1.1.3",
        ":jedi_0.19.1",
        ":matplotlib_inline_0.1.6",
        ":pexpect_4.8.0",
        ":prompt_toolkit_3.0.39",
        ":pygments_2.16.1",
        ":stack_data_0.6.3",
        ":traitlets_5.13.0",
        ":typing_extensions_4.8.0",
    ] + select({
        ":_env_python_darwin_arm64": [
            ":appnope_0.1.3",
        ],
        ":_env_python_darwin_x86_64": [
            ":appnope_0.1.3",
        ],
        "//conditions:default": [],
    })

    pycross_wheel_library(
        name = "ipython_8.17.2",
        deps = _ipython_8_17_2_deps,
        wheel = "@example_lock_wheel_ipython_8.17.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "itsdangerous_2.1.2",
        wheel = "@example_lock_wheel_itsdangerous_2.1.2_py3_none_any//file",
    )

    _jedi_0_19_1_deps = [
        ":parso_0.8.3",
    ]

    pycross_wheel_library(
        name = "jedi_0.19.1",
        deps = _jedi_0_19_1_deps,
        wheel = "@example_lock_wheel_jedi_0.19.1_py2.py3_none_any//file",
    )

    _jinja2_3_1_2_deps = [
        ":markupsafe_2.1.3",
    ]

    pycross_wheel_library(
        name = "jinja2_3.1.2",
        deps = _jinja2_3_1_2_deps,
        wheel = "@example_lock_wheel_jinja2_3.1.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "jmespath_1.0.1",
        wheel = "@example_lock_wheel_jmespath_1.0.1_py3_none_any//file",
    )

    _jschema_to_python_1_2_3_deps = [
        ":attrs_23.1.0",
        ":jsonpickle_3.0.2",
        ":pbr_6.0.0",
    ]

    pycross_wheel_library(
        name = "jschema_to_python_1.2.3",
        deps = _jschema_to_python_1_2_3_deps,
        wheel = "@example_lock_wheel_jschema_to_python_1.2.3_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "jsondiff_2.0.0",
        wheel = "@example_lock_wheel_jsondiff_2.0.0_py3_none_any//file",
    )

    _jsonpatch_1_33_deps = [
        ":jsonpointer_2.4",
    ]

    pycross_wheel_library(
        name = "jsonpatch_1.33",
        deps = _jsonpatch_1_33_deps,
        wheel = "@example_lock_wheel_jsonpatch_1.33_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "jsonpickle_3.0.2",
        wheel = "@example_lock_wheel_jsonpickle_3.0.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "jsonpointer_2.4",
        wheel = "@example_lock_wheel_jsonpointer_2.4_py2.py3_none_any//file",
    )

    _jsonschema_4_19_2_deps = [
        ":attrs_23.1.0",
        ":jsonschema_specifications_2023.7.1",
        ":referencing_0.30.2",
        ":rpds_py_0.12.0",
    ]

    pycross_wheel_library(
        name = "jsonschema_4.19.2",
        deps = _jsonschema_4_19_2_deps,
        wheel = "@example_lock_wheel_jsonschema_4.19.2_py3_none_any//file",
    )

    _jsonschema_specifications_2023_7_1_deps = [
        ":referencing_0.30.2",
    ]

    pycross_wheel_library(
        name = "jsonschema_specifications_2023.7.1",
        deps = _jsonschema_specifications_2023_7_1_deps,
        wheel = "@example_lock_wheel_jsonschema_specifications_2023.7.1_py3_none_any//file",
    )

    _junit_xml_1_9_deps = [
        ":six_1.16.0",
    ]

    pycross_wheel_library(
        name = "junit_xml_1.9",
        deps = _junit_xml_1_9_deps,
        wheel = "@example_lock_wheel_junit_xml_1.9_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "markupsafe_2.1.3",
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_markupsafe_2.1.3_cp39_cp39_macosx_10_9_universal2//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_markupsafe_2.1.3_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_markupsafe_2.1.3_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    _matplotlib_inline_0_1_6_deps = [
        ":traitlets_5.13.0",
    ]

    pycross_wheel_library(
        name = "matplotlib_inline_0.1.6",
        deps = _matplotlib_inline_0_1_6_deps,
        wheel = "@example_lock_wheel_matplotlib_inline_0.1.6_py3_none_any//file",
    )

    _moto_3_1_1_deps = [
        ":aws_xray_sdk_2.9.0",
        ":boto3_1.28.80",
        ":botocore_1.31.80",
        ":cfn_lint_0.83.1",
        ":cryptography_41.0.5",
        ":docker_6.1.3",
        ":ecdsa_0.18.0",
        ":flask_3.0.0",
        ":flask_cors_4.0.0",
        ":graphql_core_3.2.3",
        ":idna_3.4",
        ":jinja2_3.1.2",
        ":jsondiff_2.0.0",
        ":markupsafe_2.1.3",
        ":python_dateutil_2.8.2",
        ":python_jose_3.1.0",
        ":pytz_2023.3.post1",
        ":pyyaml_6.0.1",
        ":requests_2.31.0",
        ":responses_0.24.0",
        ":setuptools_59.2.0",
        ":sshpubkeys_3.3.1",
        ":werkzeug_3.0.1",
        ":xmltodict_0.13.0",
    ]

    pycross_wheel_library(
        name = "moto_3.1.1",
        deps = _moto_3_1_1_deps,
        wheel = "@example_lock_wheel_moto_3.1.1_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "mpmath_1.3.0",
        wheel = "@example_lock_wheel_mpmath_1.3.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "mypy_extensions_1.0.0",
        wheel = "@example_lock_wheel_mypy_extensions_1.0.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "networkx_3.2.1",
        wheel = "@example_lock_wheel_networkx_3.2.1_py3_none_any//file",
    )

    _numpy_1_22_3_build_deps = [
        ":cython_0.29.36",
        ":setuptools_59.2.0",
        ":wheel_0.37.0",
    ]

    pycross_wheel_library(
        name = "numpy_1.22.3",
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_numpy_1.22.3_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_numpy_1.22.3_cp39_cp39_macosx_10_14_x86_64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_numpy_1.22.3_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "oauthlib_3.2.2",
        wheel = "@example_lock_wheel_oauthlib_3.2.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "packaging_23.2",
        wheel = "@example_lock_wheel_packaging_23.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "parso_0.8.3",
        wheel = "@example_lock_wheel_parso_0.8.3_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pathspec_0.11.2",
        wheel = "@example_lock_wheel_pathspec_0.11.2_py3_none_any//file",
    )

    _pbr_6_0_0_build_deps = [
        ":setuptools_59.2.0",
        ":wheel_0.37.0",
    ]

    pycross_wheel_build(
        name = "_build_pbr_6.0.0",
        sdist = "@example_lock_sdist_pbr_6.0.0//file",
        target_environment = _target,
        deps = _pbr_6_0_0_build_deps,
        tags = ["manual"],
    )

    pycross_wheel_library(
        name = "pbr_6.0.0",
        wheel = ":_build_pbr_6.0.0",
    )

    _pexpect_4_8_0_deps = [
        ":ptyprocess_0.7.0",
    ]

    pycross_wheel_library(
        name = "pexpect_4.8.0",
        deps = _pexpect_4_8_0_deps,
        wheel = "@example_lock_wheel_pexpect_4.8.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "platformdirs_3.11.0",
        wheel = "@example_lock_wheel_platformdirs_3.11.0_py3_none_any//file",
    )

    _prompt_toolkit_3_0_39_deps = [
        ":wcwidth_0.2.9",
    ]

    pycross_wheel_library(
        name = "prompt_toolkit_3.0.39",
        deps = _prompt_toolkit_3_0_39_deps,
        wheel = "@example_lock_wheel_prompt_toolkit_3.0.39_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "ptyprocess_0.7.0",
        wheel = "@example_lock_wheel_ptyprocess_0.7.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pure_eval_0.2.2",
        wheel = "@example_lock_wheel_pure_eval_0.2.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pyasn1_0.5.0",
        wheel = "@example_lock_wheel_pyasn1_0.5.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pycparser_2.21",
        wheel = "@example_lock_wheel_pycparser_2.21_py2.py3_none_any//file",
    )

    _pydantic_2_4_2_deps = [
        ":annotated_types_0.6.0",
        ":pydantic_core_2.10.1",
        ":typing_extensions_4.8.0",
    ]

    pycross_wheel_library(
        name = "pydantic_2.4.2",
        deps = _pydantic_2_4_2_deps,
        wheel = "@example_lock_wheel_pydantic_2.4.2_py3_none_any//file",
    )

    _pydantic_core_2_10_1_deps = [
        ":typing_extensions_4.8.0",
    ]

    pycross_wheel_library(
        name = "pydantic_core_2.10.1",
        deps = _pydantic_core_2_10_1_deps,
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_pydantic_core_2.10.1_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_pydantic_core_2.10.1_cp39_cp39_macosx_10_7_x86_64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_pydantic_core_2.10.1_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "pygments_2.16.1",
        wheel = "@example_lock_wheel_pygments_2.16.1_py3_none_any//file",
    )

    _pyjwt_2_8_0_deps = [
        ":cryptography_41.0.5",
    ]

    pycross_wheel_library(
        name = "pyjwt_2.8.0",
        deps = _pyjwt_2_8_0_deps,
        wheel = "@example_lock_wheel_pyjwt_2.8.0_py3_none_any//file",
    )

    _python_dateutil_2_8_2_deps = [
        ":six_1.16.0",
    ]

    pycross_wheel_library(
        name = "python_dateutil_2.8.2",
        deps = _python_dateutil_2_8_2_deps,
        wheel = "@example_lock_wheel_python_dateutil_2.8.2_py2.py3_none_any//file",
    )

    _python_jose_3_1_0_deps = [
        ":cryptography_41.0.5",
        ":ecdsa_0.18.0",
        ":pyasn1_0.5.0",
        ":rsa_4.9",
        ":six_1.16.0",
    ]

    pycross_wheel_library(
        name = "python_jose_3.1.0",
        deps = _python_jose_3_1_0_deps,
        wheel = "@example_lock_wheel_python_jose_3.1.0_py2.py3_none_any//file",
    )

    _python3_openid_3_2_0_deps = [
        ":defusedxml_0.7.1",
    ]

    pycross_wheel_library(
        name = "python3_openid_3.2.0",
        deps = _python3_openid_3_2_0_deps,
        wheel = "@example_lock_wheel_python3_openid_3.2.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pytz_2023.3.post1",
        wheel = "@example_lock_wheel_pytz_2023.3.post1_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pyyaml_6.0.1",
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_pyyaml_6.0.1_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_pyyaml_6.0.1_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_pyyaml_6.0.1_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    _referencing_0_30_2_deps = [
        ":attrs_23.1.0",
        ":rpds_py_0.12.0",
    ]

    pycross_wheel_library(
        name = "referencing_0.30.2",
        deps = _referencing_0_30_2_deps,
        wheel = "@example_lock_wheel_referencing_0.30.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "regex_2023.10.3",
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_regex_2023.10.3_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_regex_2023.10.3_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_regex_2023.10.3_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    _requests_2_31_0_deps = [
        ":certifi_2023.7.22",
        ":charset_normalizer_3.3.2",
        ":idna_3.4",
        ":urllib3_1.26.18",
    ]

    pycross_wheel_library(
        name = "requests_2.31.0",
        deps = _requests_2_31_0_deps,
        wheel = "@example_lock_wheel_requests_2.31.0_py3_none_any//file",
    )

    _requests_oauthlib_1_3_1_deps = [
        ":oauthlib_3.2.2",
        ":requests_2.31.0",
    ]

    pycross_wheel_library(
        name = "requests_oauthlib_1.3.1",
        deps = _requests_oauthlib_1_3_1_deps,
        wheel = "@example_lock_wheel_requests_oauthlib_1.3.1_py2.py3_none_any//file",
    )

    _responses_0_24_0_deps = [
        ":pyyaml_6.0.1",
        ":requests_2.31.0",
        ":urllib3_1.26.18",
    ]

    pycross_wheel_library(
        name = "responses_0.24.0",
        deps = _responses_0_24_0_deps,
        wheel = "@example_lock_wheel_responses_0.24.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "rpds_py_0.12.0",
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_rpds_py_0.12.0_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_rpds_py_0.12.0_cp39_cp39_macosx_10_7_x86_64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_rpds_py_0.12.0_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    _rsa_4_9_deps = [
        ":pyasn1_0.5.0",
    ]

    pycross_wheel_library(
        name = "rsa_4.9",
        deps = _rsa_4_9_deps,
        wheel = "@example_lock_wheel_rsa_4.9_py3_none_any//file",
    )

    _s3transfer_0_7_0_deps = [
        ":botocore_1.31.80",
    ]

    pycross_wheel_library(
        name = "s3transfer_0.7.0",
        deps = _s3transfer_0_7_0_deps,
        wheel = "@example_lock_wheel_s3transfer_0.7.0_py3_none_any//file",
    )

    _sarif_om_1_0_4_deps = [
        ":attrs_23.1.0",
        ":pbr_6.0.0",
    ]

    pycross_wheel_library(
        name = "sarif_om_1.0.4",
        deps = _sarif_om_1_0_4_deps,
        wheel = "@example_lock_wheel_sarif_om_1.0.4_py3_none_any//file",
    )

    _setproctitle_1_2_2_build_deps = [
        ":setuptools_59.2.0",
        ":wheel_0.37.0",
    ]

    pycross_wheel_build(
        name = "_build_setproctitle_1.2.2",
        sdist = "@example_lock_sdist_setproctitle_1.2.2//file",
        target_environment = _target,
        deps = _setproctitle_1_2_2_build_deps,
        tags = ["manual"],
    )

    pycross_wheel_library(
        name = "setproctitle_1.2.2",
        wheel = ":_build_setproctitle_1.2.2",
    )

    pycross_wheel_library(
        name = "setuptools_59.2.0",
        wheel = "@example_lock_wheel_setuptools_59.2.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "six_1.16.0",
        wheel = "@example_lock_wheel_six_1.16.0_py2.py3_none_any//file",
    )

    _sqlalchemy_2_0_23_deps = [
        ":typing_extensions_4.8.0",
    ] + select({
        ":_env_python_darwin_x86_64": [
            ":greenlet_3.0.1",
        ],
        ":_env_python_linux_x86_64": [
            ":greenlet_3.0.1",
        ],
        "//conditions:default": [],
    })

    _sqlalchemy_2_0_23_build_deps = [
        ":setuptools_59.2.0",
        ":wheel_0.37.0",
    ]

    pycross_wheel_library(
        name = "sqlalchemy_2.0.23",
        deps = _sqlalchemy_2_0_23_deps,
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_sqlalchemy_2.0.23_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_sqlalchemy_2.0.23_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_sqlalchemy_2.0.23_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    _sqlalchemy_utils_0_38_2_deps = [
        ":six_1.16.0",
        ":sqlalchemy_2.0.23",
    ]

    pycross_wheel_library(
        name = "sqlalchemy_utils_0.38.2",
        deps = _sqlalchemy_utils_0_38_2_deps,
        wheel = "@example_lock_wheel_sqlalchemy_utils_0.38.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "sqlparse_0.4.4",
        wheel = "@example_lock_wheel_sqlparse_0.4.4_py3_none_any//file",
    )

    _sshpubkeys_3_3_1_deps = [
        ":cryptography_41.0.5",
        ":ecdsa_0.18.0",
    ]

    pycross_wheel_library(
        name = "sshpubkeys_3.3.1",
        deps = _sshpubkeys_3_3_1_deps,
        wheel = "@example_lock_wheel_sshpubkeys_3.3.1_py2.py3_none_any//file",
    )

    _stack_data_0_6_3_deps = [
        ":asttokens_2.4.1",
        ":executing_2.0.1",
        ":pure_eval_0.2.2",
    ]

    pycross_wheel_library(
        name = "stack_data_0.6.3",
        deps = _stack_data_0_6_3_deps,
        wheel = "@example_lock_wheel_stack_data_0.6.3_py3_none_any//file",
    )

    _sympy_1_12_deps = [
        ":mpmath_1.3.0",
    ]

    pycross_wheel_library(
        name = "sympy_1.12",
        deps = _sympy_1_12_deps,
        wheel = "@example_lock_wheel_sympy_1.12_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "tomli_2.0.1",
        wheel = "@example_lock_wheel_tomli_2.0.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "traitlets_5.13.0",
        wheel = "@example_lock_wheel_traitlets_5.13.0_py3_none_any//file",
    )

    _tree_sitter_0_20_0_build_deps = [
        ":setuptools_59.2.0",
        ":wheel_0.37.0",
    ]

    pycross_wheel_build(
        name = "_build_tree_sitter_0.20.0",
        sdist = "@example_lock_sdist_tree_sitter_0.20.0//file",
        target_environment = _target,
        deps = _tree_sitter_0_20_0_build_deps,
        tags = ["manual"],
    )

    pycross_wheel_library(
        name = "tree_sitter_0.20.0",
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_tree_sitter_0.20.0_cp39_cp39_macosx_12_0_arm64//file",
            ":_env_python_darwin_x86_64": ":_build_tree_sitter_0.20.0",
            ":_env_python_linux_x86_64": ":_build_tree_sitter_0.20.0",
        }),
    )

    pycross_wheel_library(
        name = "typing_extensions_4.8.0",
        wheel = "@example_lock_wheel_typing_extensions_4.8.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "urllib3_1.26.18",
        wheel = "@example_lock_wheel_urllib3_1.26.18_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "wcwidth_0.2.9",
        wheel = "@example_lock_wheel_wcwidth_0.2.9_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "websocket_client_1.6.4",
        wheel = "@example_lock_wheel_websocket_client_1.6.4_py3_none_any//file",
    )

    _werkzeug_3_0_1_deps = [
        ":markupsafe_2.1.3",
    ]

    pycross_wheel_library(
        name = "werkzeug_3.0.1",
        deps = _werkzeug_3_0_1_deps,
        wheel = "@example_lock_wheel_werkzeug_3.0.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "wheel_0.37.0",
        wheel = "@example_lock_wheel_wheel_0.37.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "wrapt_1.15.0",
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_wrapt_1.15.0_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_wrapt_1.15.0_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_wrapt_1.15.0_cp39_cp39_manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "xmltodict_0.13.0",
        wheel = "@example_lock_wheel_xmltodict_0.13.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "zipp_3.17.0",
        wheel = "@example_lock_wheel_zipp_3.17.0_py3_none_any//file",
    )

def repositories():
    maybe(
        http_file,
        name = "example_lock_sdist_django_allauth_0.51.0",
        urls = [
            "https://files.pythonhosted.org/packages/44/cf/ef0354010b6621b0d2053dc25ddce0132635fb0cbcfebf32a947877fb78e/django-allauth-0.51.0.tar.gz"
        ],
        sha256 = "ca1622733b6faa591580ccd3984042f12d8c79ade93438212de249b7ffb6f91f",
        downloaded_file_path = "django-allauth-0.51.0.tar.gz",
    )

    maybe(
        http_file,
        name = "example_lock_sdist_future_0.18.3",
        urls = [
            "https://files.pythonhosted.org/packages/8f/2e/cf6accf7415237d6faeeebdc7832023c90e0282aa16fd3263db0eb4715ec/future-0.18.3.tar.gz"
        ],
        sha256 = "34a17436ed1e96697a86f9de3d15a3b0be01d8bc8de9c1dffd59fb8234ed5307",
        downloaded_file_path = "future-0.18.3.tar.gz",
    )

    maybe(
        http_file,
        name = "example_lock_sdist_pbr_6.0.0",
        urls = [
            "https://files.pythonhosted.org/packages/8d/c2/ee43b3b11bf2b40e56536183fc9f22afbb04e882720332b6276ee2454c24/pbr-6.0.0.tar.gz"
        ],
        sha256 = "d1377122a5a00e2f940ee482999518efe16d745d423a670c27773dfbc3c9a7d9",
        downloaded_file_path = "pbr-6.0.0.tar.gz",
    )

    maybe(
        http_file,
        name = "example_lock_sdist_setproctitle_1.2.2",
        urls = [
            "https://files.pythonhosted.org/packages/a1/7f/a1d4f4c7b66f0fc02f35dc5c85f45a8b4e4a7988357a29e61c14e725ef86/setproctitle-1.2.2.tar.gz"
        ],
        sha256 = "7dfb472c8852403d34007e01d6e3c68c57eb66433fb8a5c77b13b89a160d97df",
        downloaded_file_path = "setproctitle-1.2.2.tar.gz",
    )

    maybe(
        http_file,
        name = "example_lock_sdist_tree_sitter_0.20.0",
        urls = [
            "https://files.pythonhosted.org/packages/10/19/434f796441f739cb0a980b76ac71bdeeff64ea75ff9ace3a8a2b18be3aeb/tree_sitter-0.20.0.tar.gz"
        ],
        sha256 = "1940f64be1e8c9c3c0e34a2258f1e4c324207534d5b1eefc5ab2960a9d98f668",
        downloaded_file_path = "tree_sitter-0.20.0.tar.gz",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_annotated_types_0.6.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/28/78/d31230046e58c207284c6b2c4e8d96e6d3cb4e52354721b944d3e1ee4aa5/annotated_types-0.6.0-py3-none-any.whl"
        ],
        sha256 = "0641064de18ba7a25dee8f96403ebc39113d0cb953a01429249d5c7564666a43",
        downloaded_file_path = "annotated_types-0.6.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_appnope_0.1.3_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/41/4a/381783f26df413dde4c70c734163d88ca0550a1361cb74a1c68f47550619/appnope-0.1.3-py2.py3-none-any.whl"
        ],
        sha256 = "265a455292d0bd8a72453494fa24df5a11eb18373a60c7c0430889f22548605e",
        downloaded_file_path = "appnope-0.1.3-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_asgiref_3.7.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/9b/80/b9051a4a07ad231558fcd8ffc89232711b4e618c15cb7a392a17384bbeef/asgiref-3.7.2-py3-none-any.whl"
        ],
        sha256 = "89b2ef2247e3b562a16eef663bc0e2e703ec6468e2fa8a5cd61cd449786d4f6e",
        downloaded_file_path = "asgiref-3.7.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_asttokens_2.4.1_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/45/86/4736ac618d82a20d87d2f92ae19441ebc7ac9e7a581d7e58bbe79233b24a/asttokens-2.4.1-py2.py3-none-any.whl"
        ],
        sha256 = "051ed49c3dcae8913ea7cd08e46a606dba30b79993209636c4875bc1d637bc24",
        downloaded_file_path = "asttokens-2.4.1-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_attrs_23.1.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/f0/eb/fcb708c7bf5056045e9e98f62b93bd7467eb718b0202e7698eb11d66416c/attrs-23.1.0-py3-none-any.whl"
        ],
        sha256 = "1f28b4522cdc2fb4256ac1a020c78acf9cba2c6b461ccd2c126f3aa8e8335d04",
        downloaded_file_path = "attrs-23.1.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_aws_sam_translator_1.79.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/16/14/7dd754c697fd8ef9910cec3c22b3e311fb8a80cefa205845227b24d5fa58/aws_sam_translator-1.79.0-py3-none-any.whl"
        ],
        sha256 = "6f0c6bbcebcc98c4f98dc238352a06b0befe7fb72535cca75712fffff4873875",
        downloaded_file_path = "aws_sam_translator-1.79.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_aws_xray_sdk_2.9.0_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/52/4b/4e0b47146a3fdca48b00774b7280e35c48c48aa9960010c6fc4a3f7f49ad/aws_xray_sdk-2.9.0-py2.py3-none-any.whl"
        ],
        sha256 = "98216b3ac8281b51b59a8703f8ec561c460807d9d0679838f5c0179d381d7e58",
        downloaded_file_path = "aws_xray_sdk-2.9.0-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_black_23.10.1_cp39_cp39_macosx_10_16_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/57/61/a91a66459dc4885a3b92c1bcf36e0556021f849e8c21732199a72ce9603c/black-23.10.1-cp39-cp39-macosx_10_16_x86_64.whl"
        ],
        sha256 = "7670242e90dc129c539e9ca17665e39a146a761e681805c54fbd86015c7c84f7",
        downloaded_file_path = "black-23.10.1-cp39-cp39-macosx_10_16_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_black_23.10.1_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/3c/32/56126f1991a4dfe31ce82adbf57b100b8bb11d4a8bf3b7ac716cfd52bf4d/black-23.10.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        ],
        sha256 = "5ed45ac9a613fb52dad3b61c8dea2ec9510bf3108d4db88422bacc7d1ba1243d",
        downloaded_file_path = "black-23.10.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_black_23.10.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/72/6e/3c49b5779a087979cb1916b1409e2bcee2d58bab1f880a4d2720251a3bfa/black-23.10.1-py3-none-any.whl"
        ],
        sha256 = "d431e6739f727bb2e0495df64a6c7a5310758e87505f5f8cde9ff6c0f2d7e4fe",
        downloaded_file_path = "black-23.10.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_blinker_1.7.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/fa/2a/7f3714cbc6356a0efec525ce7a0613d581072ed6eb53eb7b9754f33db807/blinker-1.7.0-py3-none-any.whl"
        ],
        sha256 = "c3f865d4d54db7abc53758a01601cf343fe55b84c1de4e3fa910e420b438d5b9",
        downloaded_file_path = "blinker-1.7.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_boto3_1.28.80_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/0c/51/1bbfa5647840f9231cd82a8e65ba6d859eb0e98cc7139babfb4563b43957/boto3-1.28.80-py3-none-any.whl"
        ],
        sha256 = "2f43e032ab804a3c39996d524003d2b906e5d86856a32da3427e36912a22d2b7",
        downloaded_file_path = "boto3-1.28.80-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_botocore_1.31.80_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/7d/23/d189daa14ea4012cdd5f66b22ddf4f6d917bb87e636868e5fedf7c757a7c/botocore-1.31.80-py3-none-any.whl"
        ],
        sha256 = "1c693c0f8b2553fcbe0df223241191e6f9f60b4245d65c1822c08f659274fef2",
        downloaded_file_path = "botocore-1.31.80-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_certifi_2023.7.22_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl"
        ],
        sha256 = "92d6037539857d8206b8f6ae472e8b77db8058fec5937a1ef3f54304089edbb9",
        downloaded_file_path = "certifi-2023.7.22-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_cffi_1.16.0_cp39_cp39_macosx_10_9_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/9d/da/e6dbf22b66899419e66c501ae5f1cf3d69979d4c75ad30da683f60abba94/cffi-1.16.0-cp39-cp39-macosx_10_9_x86_64.whl"
        ],
        sha256 = "582215a0e9adbe0e379761260553ba11c58943e4bbe9c36430c4ca6ac74b15ed",
        downloaded_file_path = "cffi-1.16.0-cp39-cp39-macosx_10_9_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_cffi_1.16.0_cp39_cp39_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/20/3b/f95e667064141843843df8ca79dd49ba57bb7a7615d6d7d538531e45f002/cffi-1.16.0-cp39-cp39-macosx_11_0_arm64.whl"
        ],
        sha256 = "b29ebffcf550f9da55bec9e02ad430c992a87e5f512cd63388abb76f1036d8d2",
        downloaded_file_path = "cffi-1.16.0-cp39-cp39-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_cffi_1.16.0_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/ea/ac/e9e77bc385729035143e54cc8c4785bd480eaca9df17565963556b0b7a93/cffi-1.16.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        ],
        sha256 = "8f8e709127c6c77446a8c0a8c8bf3c8ee706a06cd44b1e827c3e6a2ee6b8c098",
        downloaded_file_path = "cffi-1.16.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_cfn_lint_0.83.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/72/f4/b0f7473b8675f23ed7b3d0dd292d9909dc540e2bc522bbd730a11212b6db/cfn_lint-0.83.1-py3-none-any.whl"
        ],
        sha256 = "e801e9ca384f8c0fbbcd3e342cad5b038d6ca60214b81e70e2710b4dc3339567",
        downloaded_file_path = "cfn_lint-0.83.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_charset_normalizer_3.3.2_cp39_cp39_macosx_10_9_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/66/fe/c7d3da40a66a6bf2920cce0f436fa1f62ee28aaf92f412f0bf3b84c8ad6c/charset_normalizer-3.3.2-cp39-cp39-macosx_10_9_x86_64.whl"
        ],
        sha256 = "5b4c145409bef602a690e7cfad0a15a55c13320ff7a3ad7ca59c13bb8ba4d45d",
        downloaded_file_path = "charset_normalizer-3.3.2-cp39-cp39-macosx_10_9_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_charset_normalizer_3.3.2_cp39_cp39_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/2a/9d/a6d15bd1e3e2914af5955c8eb15f4071997e7078419328fee93dfd497eb7/charset_normalizer-3.3.2-cp39-cp39-macosx_11_0_arm64.whl"
        ],
        sha256 = "68d1f8a9e9e37c1223b656399be5d6b448dea850bed7d0f87a8311f1ff3dabb0",
        downloaded_file_path = "charset_normalizer-3.3.2-cp39-cp39-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_charset_normalizer_3.3.2_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/98/69/5d8751b4b670d623aa7a47bef061d69c279e9f922f6705147983aa76c3ce/charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        ],
        sha256 = "b261ccdec7821281dade748d088bb6e9b69e6d15b30652b74cbbac25e280b796",
        downloaded_file_path = "charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_click_8.1.7_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl"
        ],
        sha256 = "ae74fb96c20a0277a1d615f1e4d73c8414f5a98db8b799a7931d1582f3390c28",
        downloaded_file_path = "click-8.1.7-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_cognitojwt_1.4.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/a5/69/97faafdc4f1900fa1b525cedae0f98aa30b0bb086d076f8d66c68a18b1b2/cognitojwt-1.4.1-py3-none-any.whl"
        ],
        sha256 = "8ee189f82289d140dc750c91e8772436b64b94d071507ace42efc22c525f42ce",
        downloaded_file_path = "cognitojwt-1.4.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_cowsay_6.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/f1/13/63c0a02c44024ee16f664e0b36eefeb22d54e93531630bd99e237986f534/cowsay-6.1-py3-none-any.whl"
        ],
        sha256 = "274b1e6fc1b966d53976333eb90ac94cb07a450a700b455af9fbdf882244b30a",
        downloaded_file_path = "cowsay-6.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_cryptography_41.0.5_cp37_abi3_macosx_10_12_universal2",
        urls = [
            "https://files.pythonhosted.org/packages/0b/c1/2f1e8abb31ec0bf8b004052bbe0face0a8be386ed5ea30e5e300bfffd51a/cryptography-41.0.5-cp37-abi3-macosx_10_12_universal2.whl"
        ],
        sha256 = "da6a0ff8f1016ccc7477e6339e1d50ce5f59b88905585f77193ebd5068f1e797",
        downloaded_file_path = "cryptography-41.0.5-cp37-abi3-macosx_10_12_universal2.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_cryptography_41.0.5_cp37_abi3_macosx_10_12_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/76/77/e5ed12b40bbb710137bec76dd43efa6151b43fdece233b647463349e38fa/cryptography-41.0.5-cp37-abi3-macosx_10_12_x86_64.whl"
        ],
        sha256 = "b948e09fe5fb18517d99994184854ebd50b57248736fd4c720ad540560174ec5",
        downloaded_file_path = "cryptography-41.0.5-cp37-abi3-macosx_10_12_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_cryptography_41.0.5_cp37_abi3_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/3e/1b/1703679eface155413730f4a2313aebf846ae7496c15083ae9c07e7324b2/cryptography-41.0.5-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        ],
        sha256 = "e270c04f4d9b5671ebcc792b3ba5d4488bf7c42c3c241a3748e2599776f29696",
        downloaded_file_path = "cryptography-41.0.5-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_cython_0.29.36_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/35/cb/24999b0f2774ddc498d8e885f0b5f0441e008e1c100b7810498913b5bf55/Cython-0.29.36-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl"
        ],
        sha256 = "f0df6552be39853b10dfb5a10dbd08f5c49023d6b390d7ce92d4792a8b6e73ee",
        downloaded_file_path = "Cython-0.29.36-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_cython_0.29.36_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/3f/d6/9eed523aeaca42acbaa3e6d3850edae780dc7f8da9df1bf6a2ceb851839c/Cython-0.29.36-py2.py3-none-any.whl"
        ],
        sha256 = "95bb13d8be507425d03ebe051f90d4b2a9fdccc64e4f30b35645fdb7542742eb",
        downloaded_file_path = "Cython-0.29.36-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_decorator_5.1.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/d5/50/83c593b07763e1161326b3b8c6686f0f4b0f24d5526546bee538c89837d6/decorator-5.1.1-py3-none-any.whl"
        ],
        sha256 = "b8c3f85900b9dc423225913c5aace94729fe1fa9763b38939a95226f02d37186",
        downloaded_file_path = "decorator-5.1.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_defusedxml_0.7.1_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/07/6c/aa3f2f849e01cb6a001cd8554a88d4c77c5c1a31c95bdf1cf9301e6d9ef4/defusedxml-0.7.1-py2.py3-none-any.whl"
        ],
        sha256 = "a352e7e428770286cc899e2542b6cdaedb2b4953ff269a210103ec58f6198a61",
        downloaded_file_path = "defusedxml-0.7.1-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_django_4.2.7_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/2d/6d/e87236e3c7b2f5911d132034177aebb605f3953910cc429df8061b13bf10/Django-4.2.7-py3-none-any.whl"
        ],
        sha256 = "e1d37c51ad26186de355cbcec16613ebdabfa9689bbade9c538835205a8abbe9",
        downloaded_file_path = "Django-4.2.7-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_docker_6.1.3_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/db/be/3032490fa33b36ddc8c4b1da3252c6f974e7133f1a50de00c6b85cca203a/docker-6.1.3-py3-none-any.whl"
        ],
        sha256 = "aecd2277b8bf8e506e484f6ab7aec39abe0038e29fa4a6d3ba86c3fe01844ed9",
        downloaded_file_path = "docker-6.1.3-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_ecdsa_0.18.0_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/09/d4/4f05f5d16a4863b30ba96c23b23e942da8889abfa1cdbabf2a0df12a4532/ecdsa-0.18.0-py2.py3-none-any.whl"
        ],
        sha256 = "80600258e7ed2f16b9aa1d7c295bd70194109ad5a30fdee0eaeefef1d4c559dd",
        downloaded_file_path = "ecdsa-0.18.0-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_exceptiongroup_1.1.3_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/ad/83/b71e58666f156a39fb29417e4c8ca4bc7400c0dd4ed9e8842ab54dc8c344/exceptiongroup-1.1.3-py3-none-any.whl"
        ],
        sha256 = "343280667a4585d195ca1cf9cef84a4e178c4b6cf2274caef9859782b567d5e3",
        downloaded_file_path = "exceptiongroup-1.1.3-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_executing_2.0.1_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/80/03/6ea8b1b2a5ab40a7a60dc464d3daa7aa546e0a74d74a9f8ff551ea7905db/executing-2.0.1-py2.py3-none-any.whl"
        ],
        sha256 = "eac49ca94516ccc753f9fb5ce82603156e590b27525a8bc32cce8ae302eb61bc",
        downloaded_file_path = "executing-2.0.1-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_flask_3.0.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/36/42/015c23096649b908c809c69388a805a571a3bea44362fe87e33fc3afa01f/flask-3.0.0-py3-none-any.whl"
        ],
        sha256 = "21128f47e4e3b9d597a3e8521a329bf56909b690fcc3fa3e477725aa81367638",
        downloaded_file_path = "flask-3.0.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_flask_cors_4.0.0_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/10/69/1e6cfb87117568a9de088c32d6258219e9d1ff7c131abf74249ef2031279/Flask_Cors-4.0.0-py2.py3-none-any.whl"
        ],
        sha256 = "bc3492bfd6368d27cfe79c7821df5a8a319e1a6d5eab277a3794be19bdc51783",
        downloaded_file_path = "Flask_Cors-4.0.0-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_graphql_core_3.2.3_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/f8/39/e5143e7ec70939d2076c1165ae9d4a3815597019c4d797b7f959cf778600/graphql_core-3.2.3-py3-none-any.whl"
        ],
        sha256 = "5766780452bd5ec8ba133f8bf287dc92713e3868ddd83aee4faab9fc3e303dc3",
        downloaded_file_path = "graphql_core-3.2.3-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_greenlet_3.0.1_cp39_cp39_macosx_10_9_universal2",
        urls = [
            "https://files.pythonhosted.org/packages/06/6d/214cfb83e02ea10eefa71e5df028cc83fe7850783d5832142dfb7eb6bb6f/greenlet-3.0.1-cp39-cp39-macosx_10_9_universal2.whl"
        ],
        sha256 = "ce85c43ae54845272f6f9cd8320d034d7a946e9773c693b27d620edec825e376",
        downloaded_file_path = "greenlet-3.0.1-cp39-cp39-macosx_10_9_universal2.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_greenlet_3.0.1_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/fd/18/61c3c50983acf32495f2f99e28d36efc1d876081d920c47175195f188ed0/greenlet-3.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        ],
        sha256 = "9fbc5b8f3dfe24784cee8ce0be3da2d8a79e46a276593db6868382d9c50d97b1",
        downloaded_file_path = "greenlet-3.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_idna_3.4_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl"
        ],
        sha256 = "90b77e79eaa3eba6de819a0c442c0b4ceefc341a7a2ab77d7562bf49f425c5c2",
        downloaded_file_path = "idna-3.4-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_importlib_metadata_6.8.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/cc/37/db7ba97e676af155f5fcb1a35466f446eadc9104e25b83366e8088c9c926/importlib_metadata-6.8.0-py3-none-any.whl"
        ],
        sha256 = "3ebb78df84a805d7698245025b975d9d67053cd94c79245ba4b3eb694abe68bb",
        downloaded_file_path = "importlib_metadata-6.8.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_ipython_8.17.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/20/45/18f0dc2cbc3ee6680a004f620fb1400c6511ded0a76a2dd241813786ce73/ipython-8.17.2-py3-none-any.whl"
        ],
        sha256 = "1e4d1d666a023e3c93585ba0d8e962867f7a111af322efff6b9c58062b3e5444",
        downloaded_file_path = "ipython-8.17.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_itsdangerous_2.1.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/68/5f/447e04e828f47465eeab35b5d408b7ebaaaee207f48b7136c5a7267a30ae/itsdangerous-2.1.2-py3-none-any.whl"
        ],
        sha256 = "2c2349112351b88699d8d4b6b075022c0808887cb7ad10069318a8b0bc88db44",
        downloaded_file_path = "itsdangerous-2.1.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_jedi_0.19.1_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/20/9f/bc63f0f0737ad7a60800bfd472a4836661adae21f9c2535f3957b1e54ceb/jedi-0.19.1-py2.py3-none-any.whl"
        ],
        sha256 = "e983c654fe5c02867aef4cdfce5a2fbb4a50adc0af145f70504238f18ef5e7e0",
        downloaded_file_path = "jedi-0.19.1-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_jinja2_3.1.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl"
        ],
        sha256 = "6088930bfe239f0e6710546ab9c19c9ef35e29792895fed6e6e31a023a182a61",
        downloaded_file_path = "Jinja2-3.1.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_jmespath_1.0.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/31/b4/b9b800c45527aadd64d5b442f9b932b00648617eb5d63d2c7a6587b7cafc/jmespath-1.0.1-py3-none-any.whl"
        ],
        sha256 = "02e2e4cc71b5bcab88332eebf907519190dd9e6e82107fa7f83b1003a6252980",
        downloaded_file_path = "jmespath-1.0.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_jschema_to_python_1.2.3_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/31/9e/1b6819a87c3f59170406163ba17bc55b0abe18ae552f53d2b0a2025f9c63/jschema_to_python-1.2.3-py3-none-any.whl"
        ],
        sha256 = "8a703ca7604d42d74b2815eecf99a33359a8dccbb80806cce386d5e2dd992b05",
        downloaded_file_path = "jschema_to_python-1.2.3-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_jsondiff_2.0.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/db/15/0d33d6e8114901a7b2a56d4190e3dc1803a195495ee4f9696c630e046c9e/jsondiff-2.0.0-py3-none-any.whl"
        ],
        sha256 = "689841d66273fc88fc79f7d33f4c074774f4f214b6466e3aff0e5adaf889d1e0",
        downloaded_file_path = "jsondiff-2.0.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_jsonpatch_1.33_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/73/07/02e16ed01e04a374e644b575638ec7987ae846d25ad97bcc9945a3ee4b0e/jsonpatch-1.33-py2.py3-none-any.whl"
        ],
        sha256 = "0ae28c0cd062bbd8b8ecc26d7d164fbbea9652a1a3693f3b956c1eae5145dade",
        downloaded_file_path = "jsonpatch-1.33-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_jsonpickle_3.0.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/d3/25/6e0a450430b7aa194b0f515f64820fc619314faa289458b7dfca4a026114/jsonpickle-3.0.2-py3-none-any.whl"
        ],
        sha256 = "4a8442d97ca3f77978afa58068768dba7bff2dbabe79a9647bc3cdafd4ef019f",
        downloaded_file_path = "jsonpickle-3.0.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_jsonpointer_2.4_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/12/f6/0232cc0c617e195f06f810534d00b74d2f348fe71b2118009ad8ad31f878/jsonpointer-2.4-py2.py3-none-any.whl"
        ],
        sha256 = "15d51bba20eea3165644553647711d150376234112651b4f1811022aecad7d7a",
        downloaded_file_path = "jsonpointer-2.4-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_jsonschema_4.19.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/ce/aa/d1bd0b5ec568a903cc3ebcb6b096ab65c1d971c8a01ca3bf3cf788c3c646/jsonschema-4.19.2-py3-none-any.whl"
        ],
        sha256 = "eee9e502c788e89cb166d4d37f43084e3b64ab405c795c03d343a4dbc2c810fc",
        downloaded_file_path = "jsonschema-4.19.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_jsonschema_specifications_2023.7.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/1c/24/83349ac2189cc2435e84da3f69ba3c97314d3c0622628e55171c6798ed80/jsonschema_specifications-2023.7.1-py3-none-any.whl"
        ],
        sha256 = "05adf340b659828a004220a9613be00fa3f223f2b82002e273dee62fd50524b1",
        downloaded_file_path = "jsonschema_specifications-2023.7.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_junit_xml_1.9_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/2a/93/2d896b5fd3d79b4cadd8882c06650e66d003f465c9d12c488d92853dff78/junit_xml-1.9-py2.py3-none-any.whl"
        ],
        sha256 = "ec5ca1a55aefdd76d28fcc0b135251d156c7106fa979686a4b48d62b761b4732",
        downloaded_file_path = "junit_xml-1.9-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_markupsafe_2.1.3_cp39_cp39_macosx_10_9_universal2",
        urls = [
            "https://files.pythonhosted.org/packages/6a/86/654dc431513cd4417dfcead8102f22bece2d6abf2f584f0e1cc1524f7b94/MarkupSafe-2.1.3-cp39-cp39-macosx_10_9_universal2.whl"
        ],
        sha256 = "8023faf4e01efadfa183e863fefde0046de576c6f14659e8782065bcece22198",
        downloaded_file_path = "MarkupSafe-2.1.3-cp39-cp39-macosx_10_9_universal2.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_markupsafe_2.1.3_cp39_cp39_macosx_10_9_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/62/9b/4908a57acf39d8811836bc6776b309c2e07d63791485589acf0b6d7bc0c6/MarkupSafe-2.1.3-cp39-cp39-macosx_10_9_x86_64.whl"
        ],
        sha256 = "6b2b56950d93e41f33b4223ead100ea0fe11f8e6ee5f641eb753ce4b77a7042b",
        downloaded_file_path = "MarkupSafe-2.1.3-cp39-cp39-macosx_10_9_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_markupsafe_2.1.3_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/de/63/cb7e71984e9159ec5f45b5e81e896c8bdd0e45fe3fc6ce02ab497f0d790e/MarkupSafe-2.1.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        ],
        sha256 = "05fb21170423db021895e1ea1e1f3ab3adb85d1c2333cbc2310f2a26bc77272e",
        downloaded_file_path = "MarkupSafe-2.1.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_matplotlib_inline_0.1.6_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/f2/51/c34d7a1d528efaae3d8ddb18ef45a41f284eacf9e514523b191b7d0872cc/matplotlib_inline-0.1.6-py3-none-any.whl"
        ],
        sha256 = "f1f41aab5328aa5aaea9b16d083b128102f8712542f819fe7e6a420ff581b311",
        downloaded_file_path = "matplotlib_inline-0.1.6-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_moto_3.1.1_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/c4/f6/d65e8cf5fddb70e83bb00b6b2d08a73afcd13e26a5bf1c1ce9d737f39f5b/moto-3.1.1-py2.py3-none-any.whl"
        ],
        sha256 = "462495563847134ea8ef4135a229731a598a8e7b6b10a74f8d745815aa20a25b",
        downloaded_file_path = "moto-3.1.1-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_mpmath_1.3.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/43/e3/7d92a15f894aa0c9c4b49b8ee9ac9850d6e63b03c9c32c0367a13ae62209/mpmath-1.3.0-py3-none-any.whl"
        ],
        sha256 = "a0b2b9fe80bbcd81a6647ff13108738cfb482d481d826cc0e02f5b35e5c88d2c",
        downloaded_file_path = "mpmath-1.3.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_mypy_extensions_1.0.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/2a/e2/5d3f6ada4297caebe1a2add3b126fe800c96f56dbe5d1988a2cbe0b267aa/mypy_extensions-1.0.0-py3-none-any.whl"
        ],
        sha256 = "4392f6c0eb8a5668a69e23d168ffa70f0be9ccfd32b5cc2d26a34ae5b844552d",
        downloaded_file_path = "mypy_extensions-1.0.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_networkx_3.2.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/d5/f0/8fbc882ca80cf077f1b246c0e3c3465f7f415439bdea6b899f6b19f61f70/networkx-3.2.1-py3-none-any.whl"
        ],
        sha256 = "f18c69adc97877c42332c170849c96cefa91881c99a7cb3e95b7c659ebdc1ec2",
        downloaded_file_path = "networkx-3.2.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_numpy_1.22.3_cp39_cp39_macosx_10_14_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/58/55/6fef1ef16124066b96d5b5cb107c8e0af20b2007b79ba8f7e52ca2e1b2b7/numpy-1.22.3-cp39-cp39-macosx_10_14_x86_64.whl"
        ],
        sha256 = "2c10a93606e0b4b95c9b04b77dc349b398fdfbda382d2a39ba5a822f669a0123",
        downloaded_file_path = "numpy-1.22.3-cp39-cp39-macosx_10_14_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_numpy_1.22.3_cp39_cp39_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/22/66/95849d4d0116eef22d42355f1e8b67b43b0799093914fce369551bcc9d2f/numpy-1.22.3-cp39-cp39-macosx_11_0_arm64.whl"
        ],
        sha256 = "fade0d4f4d292b6f39951b6836d7a3c7ef5b2347f3c420cd9820a1d90d794802",
        downloaded_file_path = "numpy-1.22.3-cp39-cp39-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_numpy_1.22.3_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/25/2f/811ad95effd790cd13cdea494e1cd7520ebc3bf049c3e88c3ca4ba8175c5/numpy-1.22.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        ],
        sha256 = "97098b95aa4e418529099c26558eeb8486e66bd1e53a6b606d684d0c3616b168",
        downloaded_file_path = "numpy-1.22.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_oauthlib_3.2.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/7e/80/cab10959dc1faead58dc8384a781dfbf93cb4d33d50988f7a69f1b7c9bbe/oauthlib-3.2.2-py3-none-any.whl"
        ],
        sha256 = "8139f29aac13e25d502680e9e19963e83f16838d48a0d71c287fe40e7067fbca",
        downloaded_file_path = "oauthlib-3.2.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_packaging_23.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl"
        ],
        sha256 = "8c491190033a9af7e1d931d0b5dacc2ef47509b34dd0de67ed209b5203fc88c7",
        downloaded_file_path = "packaging-23.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_parso_0.8.3_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/05/63/8011bd08a4111858f79d2b09aad86638490d62fbf881c44e434a6dfca87b/parso-0.8.3-py2.py3-none-any.whl"
        ],
        sha256 = "c001d4636cd3aecdaf33cbb40aebb59b094be2a74c556778ef5576c175e19e75",
        downloaded_file_path = "parso-0.8.3-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pathspec_0.11.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/b4/2a/9b1be29146139ef459188f5e420a66e835dda921208db600b7037093891f/pathspec-0.11.2-py3-none-any.whl"
        ],
        sha256 = "1d6ed233af05e679efb96b1851550ea95bbb64b7c490b0f5aa52996c11e92a20",
        downloaded_file_path = "pathspec-0.11.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pexpect_4.8.0_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/39/7b/88dbb785881c28a102619d46423cb853b46dbccc70d3ac362d99773a78ce/pexpect-4.8.0-py2.py3-none-any.whl"
        ],
        sha256 = "0b48a55dcb3c05f3329815901ea4fc1537514d6ba867a152b581d69ae3710937",
        downloaded_file_path = "pexpect-4.8.0-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_platformdirs_3.11.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/56/29/3ec311dc18804409ecf0d2b09caa976f3ae6215559306b5b530004e11156/platformdirs-3.11.0-py3-none-any.whl"
        ],
        sha256 = "e9d171d00af68be50e9202731309c4e658fd8bc76f55c11c7dd760d023bda68e",
        downloaded_file_path = "platformdirs-3.11.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_prompt_toolkit_3.0.39_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/a9/b4/ba77c84edf499877317225d7b7bc047a81f7c2eed9628eeb6bab0ac2e6c9/prompt_toolkit-3.0.39-py3-none-any.whl"
        ],
        sha256 = "9dffbe1d8acf91e3de75f3b544e4842382fc06c6babe903ac9acb74dc6e08d88",
        downloaded_file_path = "prompt_toolkit-3.0.39-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_ptyprocess_0.7.0_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/22/a6/858897256d0deac81a172289110f31629fc4cee19b6f01283303e18c8db3/ptyprocess-0.7.0-py2.py3-none-any.whl"
        ],
        sha256 = "4b41f3967fce3af57cc7e94b888626c18bf37a083e3651ca8feeb66d492fef35",
        downloaded_file_path = "ptyprocess-0.7.0-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pure_eval_0.2.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/2b/27/77f9d5684e6bce929f5cfe18d6cfbe5133013c06cb2fbf5933670e60761d/pure_eval-0.2.2-py3-none-any.whl"
        ],
        sha256 = "01eaab343580944bc56080ebe0a674b39ec44a945e6d09ba7db3cb8cec289350",
        downloaded_file_path = "pure_eval-0.2.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pyasn1_0.5.0_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/14/e5/b56a725cbde139aa960c26a1a3ca4d4af437282e20b5314ee6a3501e7dfc/pyasn1-0.5.0-py2.py3-none-any.whl"
        ],
        sha256 = "87a2121042a1ac9358cabcaf1d07680ff97ee6404333bacca15f76aa8ad01a57",
        downloaded_file_path = "pyasn1-0.5.0-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pycparser_2.21_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl"
        ],
        sha256 = "8ee45429555515e1f6b185e78100aea234072576aa43ab53aefcae078162fca9",
        downloaded_file_path = "pycparser-2.21-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pydantic_2.4.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/73/66/0a72c9fcde42e5650c8d8d5c5c1873b9a3893018020c77ca8eb62708b923/pydantic-2.4.2-py3-none-any.whl"
        ],
        sha256 = "bc3ddf669d234f4220e6e1c4d96b061abe0998185a8d7855c0126782b7abc8c1",
        downloaded_file_path = "pydantic-2.4.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pydantic_core_2.10.1_cp39_cp39_macosx_10_7_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/cb/1b/069642e5091a5c36ef4a89f98acd0cde0bcad5d019d9e4a5a467e7e6ff86/pydantic_core-2.10.1-cp39-cp39-macosx_10_7_x86_64.whl"
        ],
        sha256 = "655f8f4c8d6a5963c9a0687793da37b9b681d9ad06f29438a3b2326d4e6b7970",
        downloaded_file_path = "pydantic_core-2.10.1-cp39-cp39-macosx_10_7_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pydantic_core_2.10.1_cp39_cp39_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/1d/f8/9b27ecd02750f02e30d0761a2bcc688b7693d1c0edac35c5a11ae6dc9c07/pydantic_core-2.10.1-cp39-cp39-macosx_11_0_arm64.whl"
        ],
        sha256 = "e570ffeb2170e116a5b17e83f19911020ac79d19c96f320cbfa1fa96b470185b",
        downloaded_file_path = "pydantic_core-2.10.1-cp39-cp39-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pydantic_core_2.10.1_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/7e/79/ce020f23d8e4e874aa95e4097a90804912b933145aa870818fdfd8c86739/pydantic_core-2.10.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        ],
        sha256 = "25bd966103890ccfa028841a8f30cebcf5875eeac8c4bde4fe221364c92f0c9a",
        downloaded_file_path = "pydantic_core-2.10.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pygments_2.16.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/43/88/29adf0b44ba6ac85045e63734ae0997d3c58d8b1a91c914d240828d0d73d/Pygments-2.16.1-py3-none-any.whl"
        ],
        sha256 = "13fc09fa63bc8d8671a6d247e1eb303c4b343eaee81d861f3404db2935653692",
        downloaded_file_path = "Pygments-2.16.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pyjwt_2.8.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/2b/4f/e04a8067c7c96c364cef7ef73906504e2f40d690811c021e1a1901473a19/PyJWT-2.8.0-py3-none-any.whl"
        ],
        sha256 = "59127c392cc44c2da5bb3192169a91f429924e17aff6534d70fdc02ab3e04320",
        downloaded_file_path = "PyJWT-2.8.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_python3_openid_3.2.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/e0/a5/c6ba13860bdf5525f1ab01e01cc667578d6f1efc8a1dba355700fb04c29b/python3_openid-3.2.0-py3-none-any.whl"
        ],
        sha256 = "6626f771e0417486701e0b4daff762e7212e820ca5b29fcc0d05f6f8736dfa6b",
        downloaded_file_path = "python3_openid-3.2.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_python_dateutil_2.8.2_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl"
        ],
        sha256 = "961d03dc3453ebbc59dbdea9e4e11c5651520a876d0f4db161e8674aae935da9",
        downloaded_file_path = "python_dateutil-2.8.2-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_python_jose_3.1.0_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/6c/80/5bdf2543fe002dc74429e9360148deb4d9e0b453acdc2b5c6fb1617f4f9d/python_jose-3.1.0-py2.py3-none-any.whl"
        ],
        sha256 = "1ac4caf4bfebd5a70cf5bd82702ed850db69b0b6e1d0ae7368e5f99ac01c9571",
        downloaded_file_path = "python_jose-3.1.0-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pytz_2023.3.post1_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl"
        ],
        sha256 = "ce42d816b81b68506614c11e8937d3aa9e41007ceb50bfdcb0749b921bf646c7",
        downloaded_file_path = "pytz-2023.3.post1-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pyyaml_6.0.1_cp39_cp39_macosx_10_9_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/57/c5/5d09b66b41d549914802f482a2118d925d876dc2a35b2d127694c1345c34/PyYAML-6.0.1-cp39-cp39-macosx_10_9_x86_64.whl"
        ],
        sha256 = "9eb6caa9a297fc2c2fb8862bc5370d0303ddba53ba97e71f08023b6cd73d16a8",
        downloaded_file_path = "PyYAML-6.0.1-cp39-cp39-macosx_10_9_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pyyaml_6.0.1_cp39_cp39_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/0e/88/21b2f16cb2123c1e9375f2c93486e35fdc86e63f02e274f0e99c589ef153/PyYAML-6.0.1-cp39-cp39-macosx_11_0_arm64.whl"
        ],
        sha256 = "c8098ddcc2a85b61647b2590f825f3db38891662cfc2fc776415143f599bb859",
        downloaded_file_path = "PyYAML-6.0.1-cp39-cp39-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_pyyaml_6.0.1_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/7d/39/472f2554a0f1e825bd7c5afc11c817cd7a2f3657460f7159f691fbb37c51/PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        ],
        sha256 = "bc1bf2925a1ecd43da378f4db9e4f799775d6367bdb94671027b73b393a7c42c",
        downloaded_file_path = "PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_referencing_0.30.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/be/8e/56d6f1e2d591f4d6cbcba446cac4a1b0dc4f584537e2071d9bcee8eeab6b/referencing-0.30.2-py3-none-any.whl"
        ],
        sha256 = "449b6669b6121a9e96a7f9e410b245d471e8d48964c67113ce9afe50c8dd7bdf",
        downloaded_file_path = "referencing-0.30.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_regex_2023.10.3_cp39_cp39_macosx_10_9_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/af/14/97ba8f3eb4275b2fdeae73d79b74bd0b8995c6e22c7aa7e90a547c19cf90/regex-2023.10.3-cp39-cp39-macosx_10_9_x86_64.whl"
        ],
        sha256 = "2c54e23836650bdf2c18222c87f6f840d4943944146ca479858404fedeb9f9af",
        downloaded_file_path = "regex-2023.10.3-cp39-cp39-macosx_10_9_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_regex_2023.10.3_cp39_cp39_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/cd/98/999f0456bdb4124b3d0a7f1d8b6d50979536f5df9856e597580dd9a6d3ff/regex-2023.10.3-cp39-cp39-macosx_11_0_arm64.whl"
        ],
        sha256 = "69c0771ca5653c7d4b65203cbfc5e66db9375f1078689459fe196fe08b7b4930",
        downloaded_file_path = "regex-2023.10.3-cp39-cp39-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_regex_2023.10.3_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/54/71/b85c050a8b6a552261e9deae23ba20099852cfbcc9819a628ce64f5a0db6/regex-2023.10.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        ],
        sha256 = "7ef1e014eed78ab650bef9a6a9cbe50b052c0aebe553fb2881e0453717573f52",
        downloaded_file_path = "regex-2023.10.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_requests_2.31.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl"
        ],
        sha256 = "58cd2187c01e70e6e26505bca751777aa9f2ee0b7f4300988b709f44e013003f",
        downloaded_file_path = "requests-2.31.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_requests_oauthlib_1.3.1_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/6f/bb/5deac77a9af870143c684ab46a7934038a53eb4aa975bc0687ed6ca2c610/requests_oauthlib-1.3.1-py2.py3-none-any.whl"
        ],
        sha256 = "2577c501a2fb8d05a304c09d090d6e47c306fef15809d102b327cf8364bddab5",
        downloaded_file_path = "requests_oauthlib-1.3.1-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_responses_0.24.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/8e/80/e67b345c978ba82adff1ee3bba4f9defd839e7068a295e7aff55bb2c4cb4/responses-0.24.0-py3-none-any.whl"
        ],
        sha256 = "060be153c270c06fa4d22c1ef8865fdef43902eb595204deeef736cddb62d353",
        downloaded_file_path = "responses-0.24.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_rpds_py_0.12.0_cp39_cp39_macosx_10_7_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/d9/73/5f517eb5e1e146419aa3193ca298869964872371f44d48a1f75fc10f9cab/rpds_py-0.12.0-cp39-cp39-macosx_10_7_x86_64.whl"
        ],
        sha256 = "1096ca0bf2d3426cbe79d4ccc91dc5aaa73629b08ea2d8467375fad8447ce11a",
        downloaded_file_path = "rpds_py-0.12.0-cp39-cp39-macosx_10_7_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_rpds_py_0.12.0_cp39_cp39_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/8c/75/75d6a34d5fe7a2ce0d1b1bd78fbae8fc7edc0e1b252c8705fa67401ef906/rpds_py-0.12.0-cp39-cp39-macosx_11_0_arm64.whl"
        ],
        sha256 = "48aa98987d54a46e13e6954880056c204700c65616af4395d1f0639eba11764b",
        downloaded_file_path = "rpds_py-0.12.0-cp39-cp39-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_rpds_py_0.12.0_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/87/d3/da07d3b03704379445d30bcaea7574139ebfa6ed8dd7d8e4b0f64eea1d74/rpds_py-0.12.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        ],
        sha256 = "6f5dcb658d597410bb7c967c1d24eaf9377b0d621358cbe9d2ff804e5dd12e81",
        downloaded_file_path = "rpds_py-0.12.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_rsa_4.9_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/49/97/fa78e3d2f65c02c8e1268b9aba606569fe97f6c8f7c2d74394553347c145/rsa-4.9-py3-none-any.whl"
        ],
        sha256 = "90260d9058e514786967344d0ef75fa8727eed8a7d2e43ce9f4bcf1b536174f7",
        downloaded_file_path = "rsa-4.9-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_s3transfer_0.7.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/5a/4b/fec9ce18f8874a96c5061422625ba86c3ee1e6587ccd92ff9f5bf7bd91b2/s3transfer-0.7.0-py3-none-any.whl"
        ],
        sha256 = "10d6923c6359175f264811ef4bf6161a3156ce8e350e705396a7557d6293c33a",
        downloaded_file_path = "s3transfer-0.7.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_sarif_om_1.0.4_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/82/7c/1d3d0467565aa8b3e77ab8712042a09dd1158056826f45783f3d2b34adf1/sarif_om-1.0.4-py3-none-any.whl"
        ],
        sha256 = "539ef47a662329b1c8502388ad92457425e95dc0aaaf995fe46f4984c4771911",
        downloaded_file_path = "sarif_om-1.0.4-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_setuptools_59.2.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/18/ad/ec41343a49a0371ea40daf37b1ba2c11333cdd121cb378161635d14b9750/setuptools-59.2.0-py3-none-any.whl"
        ],
        sha256 = "4adde3d1e1c89bde1c643c64d89cdd94cbfd8c75252ee459d4500bccb9c7d05d",
        downloaded_file_path = "setuptools-59.2.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_six_1.16.0_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl"
        ],
        sha256 = "8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254",
        downloaded_file_path = "six-1.16.0-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_sqlalchemy_2.0.23_cp39_cp39_macosx_10_9_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/62/20/3a0cbfbb17b311c6323769c09ec559a2324e09871a2f66d6040bec930031/SQLAlchemy-2.0.23-cp39-cp39-macosx_10_9_x86_64.whl"
        ],
        sha256 = "616fe7bcff0a05098f64b4478b78ec2dfa03225c23734d83d6c169eb41a93e55",
        downloaded_file_path = "SQLAlchemy-2.0.23-cp39-cp39-macosx_10_9_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_sqlalchemy_2.0.23_cp39_cp39_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/9b/41/e92e465f91aeeea7974a77549edc6736544cf881448ddb4b133903d008fe/SQLAlchemy-2.0.23-cp39-cp39-macosx_11_0_arm64.whl"
        ],
        sha256 = "0e680527245895aba86afbd5bef6c316831c02aa988d1aad83c47ffe92655e74",
        downloaded_file_path = "SQLAlchemy-2.0.23-cp39-cp39-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_sqlalchemy_2.0.23_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/5c/e7/d363abf1882ef31e780821b27bda4750d31fd46149da6b3741e99b23f873/SQLAlchemy-2.0.23-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        ],
        sha256 = "4895a63e2c271ffc7a81ea424b94060f7b3b03b4ea0cd58ab5bb676ed02f4221",
        downloaded_file_path = "SQLAlchemy-2.0.23-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_sqlalchemy_utils_0.38.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/b1/f9/7fdb5a12d63f1d059530dd807e696f16062fa0630fac6b4ce1c74c4056f5/SQLAlchemy_Utils-0.38.2-py3-none-any.whl"
        ],
        sha256 = "622235b1598f97300e4d08820ab024f5219c9a6309937a8b908093f487b4ba54",
        downloaded_file_path = "SQLAlchemy_Utils-0.38.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_sqlparse_0.4.4_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/98/5a/66d7c9305baa9f11857f247d4ba761402cea75db6058ff850ed7128957b7/sqlparse-0.4.4-py3-none-any.whl"
        ],
        sha256 = "5430a4fe2ac7d0f93e66f1efc6e1338a41884b7ddf2a350cedd20ccc4d9d28f3",
        downloaded_file_path = "sqlparse-0.4.4-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_sshpubkeys_3.3.1_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/e3/76/bc71db2f6830196554e5a197331ad668c049a12fb331075f4f579ff73cb4/sshpubkeys-3.3.1-py2.py3-none-any.whl"
        ],
        sha256 = "946f76b8fe86704b0e7c56a00d80294e39bc2305999844f079a217885060b1ac",
        downloaded_file_path = "sshpubkeys-3.3.1-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_stack_data_0.6.3_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/f1/7b/ce1eafaf1a76852e2ec9b22edecf1daa58175c090266e9f6c64afcd81d91/stack_data-0.6.3-py3-none-any.whl"
        ],
        sha256 = "d5558e0c25a4cb0853cddad3d77da9891a08cb85dd9f9f91b9f8cd66e511e695",
        downloaded_file_path = "stack_data-0.6.3-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_sympy_1.12_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/d2/05/e6600db80270777c4a64238a98d442f0fd07cc8915be2a1c16da7f2b9e74/sympy-1.12-py3-none-any.whl"
        ],
        sha256 = "c3588cd4295d0c0f603d0f2ae780587e64e2efeedb3521e46b9bb1d08d184fa5",
        downloaded_file_path = "sympy-1.12-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_tomli_2.0.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl"
        ],
        sha256 = "939de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc",
        downloaded_file_path = "tomli-2.0.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_traitlets_5.13.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/ed/fd/cfc0d27ca11f3dd12b2a90d06875d8bfb532ef40ce67be4066d10807f4aa/traitlets-5.13.0-py3-none-any.whl"
        ],
        sha256 = "baf991e61542da48fe8aef8b779a9ea0aa38d8a54166ee250d5af5ecf4486619",
        downloaded_file_path = "traitlets-5.13.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_tree_sitter_0.20.0_cp39_cp39_macosx_12_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/c0/6a/c36db85f3cb408f8cdf1329902ebfd88546c04b9224f952e99855092390b/tree_sitter-0.20.0-cp39-cp39-macosx_12_0_arm64.whl"
        ],
        sha256 = "51a609a7c1bd9d9e75d92ee128c12c7852ae70a482900fbbccf3d13a79e0378c",
        downloaded_file_path = "tree_sitter-0.20.0-cp39-cp39-macosx_12_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_typing_extensions_4.8.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/24/21/7d397a4b7934ff4028987914ac1044d3b7d52712f30e2ac7a2ae5bc86dd0/typing_extensions-4.8.0-py3-none-any.whl"
        ],
        sha256 = "8f92fc8806f9a6b641eaa5318da32b44d401efaac0f6678c9bc448ba3605faa0",
        downloaded_file_path = "typing_extensions-4.8.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_urllib3_1.26.18_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/b0/53/aa91e163dcfd1e5b82d8a890ecf13314e3e149c05270cc644581f77f17fd/urllib3-1.26.18-py2.py3-none-any.whl"
        ],
        sha256 = "34b97092d7e0a3a8cf7cd10e386f401b3737364026c45e622aa02903dffe0f07",
        downloaded_file_path = "urllib3-1.26.18-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_wcwidth_0.2.9_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/19/0b/00728863778b14ececfc97e40850fd71529b6a1695907981cc3fdc085ba6/wcwidth-0.2.9-py2.py3-none-any.whl"
        ],
        sha256 = "9a929bd8380f6cd9571a968a9c8f4353ca58d7cd812a4822bba831f8d685b223",
        downloaded_file_path = "wcwidth-0.2.9-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_websocket_client_1.6.4_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/c4/3c/1892ce394828c43d4f65248ebdee3854114266b75d1f5915cb211155ad7b/websocket_client-1.6.4-py3-none-any.whl"
        ],
        sha256 = "084072e0a7f5f347ef2ac3d8698a5e0b4ffbfcab607628cadabc650fc9a83a24",
        downloaded_file_path = "websocket_client-1.6.4-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_werkzeug_3.0.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/c3/fc/254c3e9b5feb89ff5b9076a23218dafbc99c96ac5941e900b71206e6313b/werkzeug-3.0.1-py3-none-any.whl"
        ],
        sha256 = "90a285dc0e42ad56b34e696398b8122ee4c681833fb35b8334a095d82c56da10",
        downloaded_file_path = "werkzeug-3.0.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_wheel_0.37.0_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/04/80/cad93b40262f5d09f6de82adbee452fd43cdff60830b56a74c5930f7e277/wheel-0.37.0-py2.py3-none-any.whl"
        ],
        sha256 = "21014b2bd93c6d0034b6ba5d35e4eb284340e09d63c59aef6fc14b0f346146fd",
        downloaded_file_path = "wheel-0.37.0-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_wrapt_1.15.0_cp39_cp39_macosx_10_9_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/b7/3d/9d3cd75f7fc283b6e627c9b0e904189c41ca144185fd8113a1a094dec8ca/wrapt-1.15.0-cp39-cp39-macosx_10_9_x86_64.whl"
        ],
        sha256 = "2e51de54d4fb8fb50d6ee8327f9828306a959ae394d3e01a1ba8b2f937747d86",
        downloaded_file_path = "wrapt-1.15.0-cp39-cp39-macosx_10_9_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_wrapt_1.15.0_cp39_cp39_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/1e/3c/cb96dbcafbf3a27413fb15e0a1997c4610283f895dc01aca955cd2fda8b9/wrapt-1.15.0-cp39-cp39-macosx_11_0_arm64.whl"
        ],
        sha256 = "0970ddb69bba00670e58955f8019bec4a42d1785db3faa043c33d81de2bf843c",
        downloaded_file_path = "wrapt-1.15.0-cp39-cp39-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_wrapt_1.15.0_cp39_cp39_manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/dd/eb/389f9975a6be31ddd19d29128a11f1288d07b624e464598a4b450f8d007e/wrapt-1.15.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        ],
        sha256 = "9d37ac69edc5614b90516807de32d08cb8e7b12260a285ee330955604ed9dd29",
        downloaded_file_path = "wrapt-1.15.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_xmltodict_0.13.0_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/94/db/fd0326e331726f07ff7f40675cd86aa804bfd2e5016c727fa761c934990e/xmltodict-0.13.0-py2.py3-none-any.whl"
        ],
        sha256 = "aa89e8fd76320154a40d19a0df04a4695fb9dc5ba977cbb68ab3e4eb225e7852",
        downloaded_file_path = "xmltodict-0.13.0-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_zipp_3.17.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/d9/66/48866fc6b158c81cc2bfecc04c480f105c6040e8b077bc54c634b4a67926/zipp-3.17.0-py3-none-any.whl"
        ],
        sha256 = "0e923e726174922dce09c53c59ad483ff7bbb8e572e00c7f7c46b88556409f31",
        downloaded_file_path = "zipp-3.17.0-py3-none-any.whl",
    )

