[project]
name = "rules_pycross_example_pdm"
version = "0.1"
description = "rules_pycross"
authors = []
dependencies = [
    "ipython>=8.0.1",
    "moto[all,server]==3.1.1",
    "SQLAlchemy-Utils==0.38.2",
    "cognitojwt",
    "python-jose==3.1.0",
    "numpy==1.22.3",
    "Cython>=0.29.24,<3.0",
    "setuptools==59.2.0",
    "wheel==0.37.0",
    "setproctitle==1.2.2",
    "tree-sitter==0.20.0",
    "aws-xray-sdk==2.9.0",
    "django-allauth==0.51.0",
]
requires-python = "~=3.9"
license = {text = "MIT"}
[project.optional-dependencies]
cow = [
    "cowsay>=5.0",
]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "black>=22.6.0",
]
nodev = [
    "flake8>=5.0.4",
]
