[project]
name = "rules_pycross_example_pdm"
version = "0.1"
description = "rules_pycross"
authors = []
dependencies = [
    "ipython>=8.17",
    "moto[all,server]==4.2.7",
    "SQLAlchemy-Utils==0.41.1",
    "cognitojwt",
    "python-jose==3.3.0",
    "numpy==1.26.1",
    "Cython>=0.29.24,<3.0",
    "setuptools==68.2.2",
    "wheel==0.41.3",
    "setproctitle==1.3.3",
    "tree-sitter==0.20.2",
    "aws-xray-sdk==2.12.1",
    "django-allauth==0.58.2",
    "future==0.18.3",
    "sphinx>=7.2.6",
    "amqp-mock==0.6.1",
]
requires-python = ">=3.11,<3.13"
license = {text = "MIT"}
[project.optional-dependencies]
cow = [
    "cowsay>=5.0",
]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "black>=23.11.0",
]
nodev = [
    "flake8>=6.1.0",
]

[tool.pdm.scripts]
post_lock = "bazel run //:update_example_lock"
