# This file is generated by rules_pycross.
# It is not intended for manual editing.
"""Pycross-generated dependency targets."""

load("@@rules_pycross~//pycross:defs.bzl", "pycross_wheel_build", "pycross_wheel_library")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

PINS = {
    "appnope": "appnope@0.1.4",
    "asttokens": "asttokens@2.4.1",
    "cowsay": "cowsay@6.1",
    "decorator": "decorator@5.1.1",
    "exceptiongroup": "exceptiongroup@1.2.1",
    "executing": "executing@2.0.1",
    "ipython": "ipython@8.17.2",
    "jedi": "jedi@0.19.1",
    "matplotlib-inline": "matplotlib-inline@0.1.7",
    "parso": "parso@0.8.4",
    "pexpect": "pexpect@4.9.0",
    "prompt-toolkit": "prompt-toolkit@3.0.47",
    "ptyprocess": "ptyprocess@0.7.0",
    "pure-eval": "pure-eval@0.2.2",
    "pygments": "pygments@2.18.0",
    "regex": "regex@2023.10.3",
    "setuptools": "setuptools@68.2.2",
    "six": "six@1.16.0",
    "stack-data": "stack-data@0.6.3",
    "traitlets": "traitlets@5.14.3",
    "wcwidth": "wcwidth@0.2.13",
    "wheel": "wheel@0.41.3",
    "zope-interface": "zope-interface@5.5.2",
    "zstandard": "zstandard@0.22.0",
}

# buildifier: disable=unnamed-macro
def targets():
    """Generated package targets."""

    for pin_name, pin_target in PINS.items():
        native.alias(
            name = pin_name,
            actual = ":" + pin_target,
        )

    native.alias(
        name = "_env_python_3.10.11_aarch64-apple-darwin",
        actual = "@@rules_pycross~~environments~smoke_environments//:python_3.10.11_aarch64-apple-darwin_config",
    )

    native.alias(
        name = "_env_python_3.10.11_aarch64-unknown-linux-gnu",
        actual = "@@rules_pycross~~environments~smoke_environments//:python_3.10.11_aarch64-unknown-linux-gnu_config",
    )

    native.alias(
        name = "_env_python_3.10.11_x86_64-unknown-linux-gnu",
        actual = "@@rules_pycross~~environments~smoke_environments//:python_3.10.11_x86_64-unknown-linux-gnu_config",
    )

    native.alias(
        name = "_env_python_3.11.6_aarch64-apple-darwin",
        actual = "@@rules_pycross~~environments~smoke_environments//:python_3.11.6_aarch64-apple-darwin_config",
    )

    native.alias(
        name = "_env_python_3.11.6_aarch64-unknown-linux-gnu",
        actual = "@@rules_pycross~~environments~smoke_environments//:python_3.11.6_aarch64-unknown-linux-gnu_config",
    )

    native.alias(
        name = "_env_python_3.11.6_x86_64-unknown-linux-gnu",
        actual = "@@rules_pycross~~environments~smoke_environments//:python_3.11.6_x86_64-unknown-linux-gnu_config",
    )

    native.alias(
        name = "_env_python_3.12.0_aarch64-apple-darwin",
        actual = "@@rules_pycross~~environments~smoke_environments//:python_3.12.0_aarch64-apple-darwin_config",
    )

    native.alias(
        name = "_env_python_3.12.0_aarch64-unknown-linux-gnu",
        actual = "@@rules_pycross~~environments~smoke_environments//:python_3.12.0_aarch64-unknown-linux-gnu_config",
    )

    native.alias(
        name = "_env_python_3.12.0_x86_64-unknown-linux-gnu",
        actual = "@@rules_pycross~~environments~smoke_environments//:python_3.12.0_x86_64-unknown-linux-gnu_config",
    )

    native.alias(
        name = "_env_python_3.12_aarch64-apple-darwin",
        actual = "@@rules_pycross~~environments~smoke_environments//:python_3.12_aarch64-apple-darwin_config",
    )

    native.alias(
        name = "_env_python_3.12_aarch64-unknown-linux-gnu",
        actual = "@@rules_pycross~~environments~smoke_environments//:python_3.12_aarch64-unknown-linux-gnu_config",
    )

    native.alias(
        name = "_env_python_3.12_x86_64-unknown-linux-gnu",
        actual = "@@rules_pycross~~environments~smoke_environments//:python_3.12_x86_64-unknown-linux-gnu_config",
    )

    # buildifier: disable=unused-variable
    _target = select({
        ":_env_python_3.10.11_aarch64-apple-darwin": "@@rules_pycross~~environments~smoke_environments//:python_3.10.11_aarch64-apple-darwin.json",
        ":_env_python_3.10.11_aarch64-unknown-linux-gnu": "@@rules_pycross~~environments~smoke_environments//:python_3.10.11_aarch64-unknown-linux-gnu.json",
        ":_env_python_3.10.11_x86_64-unknown-linux-gnu": "@@rules_pycross~~environments~smoke_environments//:python_3.10.11_x86_64-unknown-linux-gnu.json",
        ":_env_python_3.11.6_aarch64-apple-darwin": "@@rules_pycross~~environments~smoke_environments//:python_3.11.6_aarch64-apple-darwin.json",
        ":_env_python_3.11.6_aarch64-unknown-linux-gnu": "@@rules_pycross~~environments~smoke_environments//:python_3.11.6_aarch64-unknown-linux-gnu.json",
        ":_env_python_3.11.6_x86_64-unknown-linux-gnu": "@@rules_pycross~~environments~smoke_environments//:python_3.11.6_x86_64-unknown-linux-gnu.json",
        ":_env_python_3.12.0_aarch64-apple-darwin": "@@rules_pycross~~environments~smoke_environments//:python_3.12.0_aarch64-apple-darwin.json",
        ":_env_python_3.12.0_aarch64-unknown-linux-gnu": "@@rules_pycross~~environments~smoke_environments//:python_3.12.0_aarch64-unknown-linux-gnu.json",
        ":_env_python_3.12.0_x86_64-unknown-linux-gnu": "@@rules_pycross~~environments~smoke_environments//:python_3.12.0_x86_64-unknown-linux-gnu.json",
        ":_env_python_3.12_aarch64-apple-darwin": "@@rules_pycross~~environments~smoke_environments//:python_3.12_aarch64-apple-darwin.json",
        ":_env_python_3.12_aarch64-unknown-linux-gnu": "@@rules_pycross~~environments~smoke_environments//:python_3.12_aarch64-unknown-linux-gnu.json",
        ":_env_python_3.12_x86_64-unknown-linux-gnu": "@@rules_pycross~~environments~smoke_environments//:python_3.12_x86_64-unknown-linux-gnu.json",
    })

    native.alias(
        name = "_wheel_appnope@0.1.4",
        actual = "@pdm_lock_wheel_appnope_0.1.4_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "appnope@0.1.4",
        wheel = ":_wheel_appnope@0.1.4",
    )

    _asttokens_2_4_1_deps = [
        ":six@1.16.0",
    ]

    native.alias(
        name = "_wheel_asttokens@2.4.1",
        actual = "@pdm_lock_wheel_asttokens_2.4.1_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "asttokens@2.4.1",
        deps = _asttokens_2_4_1_deps,
        wheel = ":_wheel_asttokens@2.4.1",
    )

    native.alias(
        name = "_wheel_cowsay@6.1",
        actual = "@pdm_lock_wheel_cowsay_6.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "cowsay@6.1",
        wheel = ":_wheel_cowsay@6.1",
    )

    native.alias(
        name = "_wheel_decorator@5.1.1",
        actual = "@pdm_lock_wheel_decorator_5.1.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "decorator@5.1.1",
        wheel = ":_wheel_decorator@5.1.1",
    )

    native.alias(
        name = "_wheel_exceptiongroup@1.2.1",
        actual = "@pdm_lock_wheel_exceptiongroup_1.2.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "exceptiongroup@1.2.1",
        wheel = ":_wheel_exceptiongroup@1.2.1",
    )

    native.alias(
        name = "_wheel_executing@2.0.1",
        actual = "@pdm_lock_wheel_executing_2.0.1_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "executing@2.0.1",
        wheel = ":_wheel_executing@2.0.1",
    )

    _ipython_8_17_2_deps = [
        ":decorator@5.1.1",
        ":jedi@0.19.1",
        ":matplotlib-inline@0.1.7",
        ":pexpect@4.9.0",
        ":prompt-toolkit@3.0.47",
        ":pygments@2.18.0",
        ":stack-data@0.6.3",
        ":traitlets@5.14.3",
    ] + select({
        ":_env_python_3.10.11_aarch64-apple-darwin": [
            ":appnope@0.1.4",
            ":exceptiongroup@1.2.1",
        ],
        ":_env_python_3.10.11_aarch64-unknown-linux-gnu": [
            ":exceptiongroup@1.2.1",
        ],
        ":_env_python_3.10.11_x86_64-unknown-linux-gnu": [
            ":exceptiongroup@1.2.1",
        ],
        ":_env_python_3.11.6_aarch64-apple-darwin": [
            ":appnope@0.1.4",
        ],
        ":_env_python_3.12.0_aarch64-apple-darwin": [
            ":appnope@0.1.4",
        ],
        ":_env_python_3.12_aarch64-apple-darwin": [
            ":appnope@0.1.4",
        ],
        "//conditions:default": [],
    })

    native.alias(
        name = "_wheel_ipython@8.17.2",
        actual = "@pdm_lock_wheel_ipython_8.17.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "ipython@8.17.2",
        deps = _ipython_8_17_2_deps,
        wheel = ":_wheel_ipython@8.17.2",
    )

    _jedi_0_19_1_deps = [
        ":parso@0.8.4",
    ]

    native.alias(
        name = "_wheel_jedi@0.19.1",
        actual = "@pdm_lock_wheel_jedi_0.19.1_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "jedi@0.19.1",
        deps = _jedi_0_19_1_deps,
        wheel = ":_wheel_jedi@0.19.1",
    )

    _matplotlib_inline_0_1_7_deps = [
        ":traitlets@5.14.3",
    ]

    native.alias(
        name = "_wheel_matplotlib-inline@0.1.7",
        actual = "@pdm_lock_wheel_matplotlib_inline_0.1.7_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "matplotlib-inline@0.1.7",
        deps = _matplotlib_inline_0_1_7_deps,
        wheel = ":_wheel_matplotlib-inline@0.1.7",
    )

    native.alias(
        name = "_wheel_parso@0.8.4",
        actual = "@pdm_lock_wheel_parso_0.8.4_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "parso@0.8.4",
        wheel = ":_wheel_parso@0.8.4",
    )

    _pexpect_4_9_0_deps = [
        ":ptyprocess@0.7.0",
    ]

    native.alias(
        name = "_wheel_pexpect@4.9.0",
        actual = "@pdm_lock_wheel_pexpect_4.9.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pexpect@4.9.0",
        deps = _pexpect_4_9_0_deps,
        wheel = ":_wheel_pexpect@4.9.0",
    )

    _prompt_toolkit_3_0_47_deps = [
        ":wcwidth@0.2.13",
    ]

    native.alias(
        name = "_wheel_prompt-toolkit@3.0.47",
        actual = "@pdm_lock_wheel_prompt_toolkit_3.0.47_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "prompt-toolkit@3.0.47",
        deps = _prompt_toolkit_3_0_47_deps,
        wheel = ":_wheel_prompt-toolkit@3.0.47",
    )

    native.alias(
        name = "_wheel_ptyprocess@0.7.0",
        actual = "@pdm_lock_wheel_ptyprocess_0.7.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "ptyprocess@0.7.0",
        wheel = ":_wheel_ptyprocess@0.7.0",
    )

    native.alias(
        name = "_wheel_pure-eval@0.2.2",
        actual = "@pdm_lock_wheel_pure_eval_0.2.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pure-eval@0.2.2",
        wheel = ":_wheel_pure-eval@0.2.2",
    )

    native.alias(
        name = "_wheel_pygments@2.18.0",
        actual = "@pdm_lock_wheel_pygments_2.18.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pygments@2.18.0",
        wheel = ":_wheel_pygments@2.18.0",
    )

    native.alias(
        name = "_wheel_regex@2023.10.3",
        actual = select({
            ":_env_python_3.10.11_aarch64-apple-darwin": "@pdm_lock_wheel_regex_2023.10.3_cp310_cp310_macosx_11_0_arm64//file",
            ":_env_python_3.10.11_aarch64-unknown-linux-gnu": "@pdm_lock_wheel_regex_2023.10.3_cp310_cp310_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_3.10.11_x86_64-unknown-linux-gnu": "@pdm_lock_wheel_regex_2023.10.3_cp310_cp310_manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64//file",
            ":_env_python_3.11.6_aarch64-apple-darwin": "@pdm_lock_wheel_regex_2023.10.3_cp311_cp311_macosx_11_0_arm64//file",
            ":_env_python_3.11.6_aarch64-unknown-linux-gnu": "@pdm_lock_wheel_regex_2023.10.3_cp311_cp311_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_3.11.6_x86_64-unknown-linux-gnu": "@pdm_lock_wheel_regex_2023.10.3_cp311_cp311_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
            ":_env_python_3.12.0_aarch64-apple-darwin": "@pdm_lock_wheel_regex_2023.10.3_cp312_cp312_macosx_11_0_arm64//file",
            ":_env_python_3.12.0_aarch64-unknown-linux-gnu": "@pdm_lock_wheel_regex_2023.10.3_cp312_cp312_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_3.12.0_x86_64-unknown-linux-gnu": "@pdm_lock_wheel_regex_2023.10.3_cp312_cp312_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
            ":_env_python_3.12_aarch64-apple-darwin": "@pdm_lock_wheel_regex_2023.10.3_cp312_cp312_macosx_11_0_arm64//file",
            ":_env_python_3.12_aarch64-unknown-linux-gnu": "@pdm_lock_wheel_regex_2023.10.3_cp312_cp312_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_3.12_x86_64-unknown-linux-gnu": "@pdm_lock_wheel_regex_2023.10.3_cp312_cp312_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "regex@2023.10.3",
        wheel = ":_wheel_regex@2023.10.3",
    )

    native.alias(
        name = "_wheel_setuptools@68.2.2",
        actual = "@pdm_lock_wheel_setuptools_68.2.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "setuptools@68.2.2",
        wheel = ":_wheel_setuptools@68.2.2",
    )

    native.alias(
        name = "_wheel_six@1.16.0",
        actual = "@pdm_lock_wheel_six_1.16.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "six@1.16.0",
        wheel = ":_wheel_six@1.16.0",
    )

    _stack_data_0_6_3_deps = [
        ":asttokens@2.4.1",
        ":executing@2.0.1",
        ":pure-eval@0.2.2",
    ]

    native.alias(
        name = "_wheel_stack-data@0.6.3",
        actual = "@pdm_lock_wheel_stack_data_0.6.3_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "stack-data@0.6.3",
        deps = _stack_data_0_6_3_deps,
        wheel = ":_wheel_stack-data@0.6.3",
    )

    native.alias(
        name = "_wheel_traitlets@5.14.3",
        actual = "@pdm_lock_wheel_traitlets_5.14.3_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "traitlets@5.14.3",
        wheel = ":_wheel_traitlets@5.14.3",
    )

    native.alias(
        name = "_wheel_wcwidth@0.2.13",
        actual = "@pdm_lock_wheel_wcwidth_0.2.13_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "wcwidth@0.2.13",
        wheel = ":_wheel_wcwidth@0.2.13",
    )

    native.alias(
        name = "_wheel_wheel@0.41.3",
        actual = "@pdm_lock_wheel_wheel_0.41.3_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "wheel@0.41.3",
        wheel = ":_wheel_wheel@0.41.3",
    )

    _zope_interface_5_5_2_deps = [
        ":setuptools@68.2.2",
    ]

    native.alias(
        name = "_sdist_zope-interface@5.5.2",
        actual = "@pdm_lock_sdist_zope.interface_5.5.2//file",
    )

    pycross_wheel_build(
        name = "_build_zope-interface@5.5.2",
        sdist = ":_sdist_zope-interface@5.5.2",
        target_environment = _target,
        deps = _zope_interface_5_5_2_deps,
        tags = ["manual"],
    )

    native.alias(
        name = "_wheel_zope-interface@5.5.2",
        actual = select({
            ":_env_python_3.10.11_aarch64-apple-darwin": "@pdm_lock_wheel_zope.interface_5.5.2_cp310_cp310_macosx_11_0_arm64//file",
            ":_env_python_3.10.11_aarch64-unknown-linux-gnu": "@pdm_lock_wheel_zope.interface_5.5.2_cp310_cp310_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_3.10.11_x86_64-unknown-linux-gnu": "@pdm_lock_wheel_zope.interface_5.5.2_cp310_cp310_manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64//file",
            ":_env_python_3.11.6_aarch64-apple-darwin": "@pdm_lock_wheel_zope.interface_5.5.2_cp311_cp311_macosx_11_0_arm64//file",
            ":_env_python_3.11.6_aarch64-unknown-linux-gnu": "@pdm_lock_wheel_zope.interface_5.5.2_cp311_cp311_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_3.11.6_x86_64-unknown-linux-gnu": ":_build_zope-interface@5.5.2",
            ":_env_python_3.12.0_aarch64-apple-darwin": ":_build_zope-interface@5.5.2",
            ":_env_python_3.12.0_aarch64-unknown-linux-gnu": ":_build_zope-interface@5.5.2",
            ":_env_python_3.12.0_x86_64-unknown-linux-gnu": ":_build_zope-interface@5.5.2",
            ":_env_python_3.12_aarch64-apple-darwin": ":_build_zope-interface@5.5.2",
            ":_env_python_3.12_aarch64-unknown-linux-gnu": ":_build_zope-interface@5.5.2",
            ":_env_python_3.12_x86_64-unknown-linux-gnu": ":_build_zope-interface@5.5.2",
        }),
    )

    pycross_wheel_library(
        name = "zope-interface@5.5.2",
        deps = _zope_interface_5_5_2_deps,
        wheel = ":_wheel_zope-interface@5.5.2",
    )

    native.alias(
        name = "_wheel_zstandard@0.22.0",
        actual = select({
            ":_env_python_3.10.11_aarch64-apple-darwin": "@pdm_lock_wheel_zstandard_0.22.0_cp310_cp310_macosx_11_0_arm64//file",
            ":_env_python_3.10.11_aarch64-unknown-linux-gnu": "@pdm_lock_wheel_zstandard_0.22.0_cp310_cp310_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_3.10.11_x86_64-unknown-linux-gnu": "@pdm_lock_wheel_zstandard_0.22.0_cp310_cp310_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
            ":_env_python_3.11.6_aarch64-apple-darwin": "@pdm_lock_wheel_zstandard_0.22.0_cp311_cp311_macosx_11_0_arm64//file",
            ":_env_python_3.11.6_aarch64-unknown-linux-gnu": "@pdm_lock_wheel_zstandard_0.22.0_cp311_cp311_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_3.11.6_x86_64-unknown-linux-gnu": "@pdm_lock_wheel_zstandard_0.22.0_cp311_cp311_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
            ":_env_python_3.12.0_aarch64-apple-darwin": "@pdm_lock_wheel_zstandard_0.22.0_cp312_cp312_macosx_11_0_arm64//file",
            ":_env_python_3.12.0_aarch64-unknown-linux-gnu": "@pdm_lock_wheel_zstandard_0.22.0_cp312_cp312_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_3.12.0_x86_64-unknown-linux-gnu": "@pdm_lock_wheel_zstandard_0.22.0_cp312_cp312_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
            ":_env_python_3.12_aarch64-apple-darwin": "@pdm_lock_wheel_zstandard_0.22.0_cp312_cp312_macosx_11_0_arm64//file",
            ":_env_python_3.12_aarch64-unknown-linux-gnu": "@pdm_lock_wheel_zstandard_0.22.0_cp312_cp312_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_3.12_x86_64-unknown-linux-gnu": "@pdm_lock_wheel_zstandard_0.22.0_cp312_cp312_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "zstandard@0.22.0",
        wheel = ":_wheel_zstandard@0.22.0",
    )

# buildifier: disable=unnamed-macro
def repositories():
    """Generated package repositories."""

    maybe(
        http_file,
        name = "pdm_lock_sdist_zope.interface_5.5.2",
        urls = [
            "https://files.pythonhosted.org/packages/38/6f/fbfb7dde38be7e5644bb342c4c7cdc444cd5e2ffbd70d091263b3858a8cb/zope.interface-5.5.2.tar.gz",
        ],
        sha256 = "bfee1f3ff62143819499e348f5b8a7f3aa0259f9aca5e0ddae7391d059dce671",
        downloaded_file_path = "zope.interface-5.5.2.tar.gz",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_appnope_0.1.4_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/81/29/5ecc3a15d5a33e31b26c11426c45c501e439cb865d0bff96315d86443b78/appnope-0.1.4-py2.py3-none-any.whl",
        ],
        sha256 = "502575ee11cd7a28c0205f379b525beefebab9d161b7c964670864014ed7213c",
        downloaded_file_path = "appnope-0.1.4-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_asttokens_2.4.1_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/45/86/4736ac618d82a20d87d2f92ae19441ebc7ac9e7a581d7e58bbe79233b24a/asttokens-2.4.1-py2.py3-none-any.whl",
        ],
        sha256 = "051ed49c3dcae8913ea7cd08e46a606dba30b79993209636c4875bc1d637bc24",
        downloaded_file_path = "asttokens-2.4.1-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_cowsay_6.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/f1/13/63c0a02c44024ee16f664e0b36eefeb22d54e93531630bd99e237986f534/cowsay-6.1-py3-none-any.whl",
        ],
        sha256 = "274b1e6fc1b966d53976333eb90ac94cb07a450a700b455af9fbdf882244b30a",
        downloaded_file_path = "cowsay-6.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_decorator_5.1.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/d5/50/83c593b07763e1161326b3b8c6686f0f4b0f24d5526546bee538c89837d6/decorator-5.1.1-py3-none-any.whl",
        ],
        sha256 = "b8c3f85900b9dc423225913c5aace94729fe1fa9763b38939a95226f02d37186",
        downloaded_file_path = "decorator-5.1.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_exceptiongroup_1.2.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/01/90/79fe92dd413a9cab314ef5c591b5aa9b9ba787ae4cadab75055b0ae00b33/exceptiongroup-1.2.1-py3-none-any.whl",
        ],
        sha256 = "5258b9ed329c5bbdd31a309f53cbfb0b155341807f6ff7606a1e801a891b29ad",
        downloaded_file_path = "exceptiongroup-1.2.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_executing_2.0.1_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/80/03/6ea8b1b2a5ab40a7a60dc464d3daa7aa546e0a74d74a9f8ff551ea7905db/executing-2.0.1-py2.py3-none-any.whl",
        ],
        sha256 = "eac49ca94516ccc753f9fb5ce82603156e590b27525a8bc32cce8ae302eb61bc",
        downloaded_file_path = "executing-2.0.1-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_ipython_8.17.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/20/45/18f0dc2cbc3ee6680a004f620fb1400c6511ded0a76a2dd241813786ce73/ipython-8.17.2-py3-none-any.whl",
        ],
        sha256 = "1e4d1d666a023e3c93585ba0d8e962867f7a111af322efff6b9c58062b3e5444",
        downloaded_file_path = "ipython-8.17.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_jedi_0.19.1_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/20/9f/bc63f0f0737ad7a60800bfd472a4836661adae21f9c2535f3957b1e54ceb/jedi-0.19.1-py2.py3-none-any.whl",
        ],
        sha256 = "e983c654fe5c02867aef4cdfce5a2fbb4a50adc0af145f70504238f18ef5e7e0",
        downloaded_file_path = "jedi-0.19.1-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_matplotlib_inline_0.1.7_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/8f/8e/9ad090d3553c280a8060fbf6e24dc1c0c29704ee7d1c372f0c174aa59285/matplotlib_inline-0.1.7-py3-none-any.whl",
        ],
        sha256 = "df192d39a4ff8f21b1895d72e6a13f5fcc5099f00fa84384e0ea28c2cc0653ca",
        downloaded_file_path = "matplotlib_inline-0.1.7-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_parso_0.8.4_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/c6/ac/dac4a63f978e4dcb3c6d3a78c4d8e0192a113d288502a1216950c41b1027/parso-0.8.4-py2.py3-none-any.whl",
        ],
        sha256 = "a418670a20291dacd2dddc80c377c5c3791378ee1e8d12bffc35420643d43f18",
        downloaded_file_path = "parso-0.8.4-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_pexpect_4.9.0_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/9e/c3/059298687310d527a58bb01f3b1965787ee3b40dce76752eda8b44e9a2c5/pexpect-4.9.0-py2.py3-none-any.whl",
        ],
        sha256 = "7236d1e080e4936be2dc3e326cec0af72acf9212a7e1d060210e70a47e253523",
        downloaded_file_path = "pexpect-4.9.0-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_prompt_toolkit_3.0.47_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/e8/23/22750c4b768f09386d1c3cc4337953e8936f48a888fa6dddfb669b2c9088/prompt_toolkit-3.0.47-py3-none-any.whl",
        ],
        sha256 = "0d7bfa67001d5e39d02c224b663abc33687405033a8c422d0d675a5a13361d10",
        downloaded_file_path = "prompt_toolkit-3.0.47-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_ptyprocess_0.7.0_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/22/a6/858897256d0deac81a172289110f31629fc4cee19b6f01283303e18c8db3/ptyprocess-0.7.0-py2.py3-none-any.whl",
        ],
        sha256 = "4b41f3967fce3af57cc7e94b888626c18bf37a083e3651ca8feeb66d492fef35",
        downloaded_file_path = "ptyprocess-0.7.0-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_pure_eval_0.2.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/2b/27/77f9d5684e6bce929f5cfe18d6cfbe5133013c06cb2fbf5933670e60761d/pure_eval-0.2.2-py3-none-any.whl",
        ],
        sha256 = "01eaab343580944bc56080ebe0a674b39ec44a945e6d09ba7db3cb8cec289350",
        downloaded_file_path = "pure_eval-0.2.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_pygments_2.18.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/f7/3f/01c8b82017c199075f8f788d0d906b9ffbbc5a47dc9918a945e13d5a2bda/pygments-2.18.0-py3-none-any.whl",
        ],
        sha256 = "b8e6aca0523f3ab76fee51799c488e38782ac06eafcf95e7ba832985c8e7b13a",
        downloaded_file_path = "pygments-2.18.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_regex_2023.10.3_cp310_cp310_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/d1/f1/9c50c0e1e76234f05f876dd49df925dae49da7fb8cb152a429006c71f65b/regex-2023.10.3-cp310-cp310-macosx_11_0_arm64.whl",
        ],
        sha256 = "a8f4e49fc3ce020f65411432183e6775f24e02dff617281094ba6ab079ef0915",
        downloaded_file_path = "regex-2023.10.3-cp310-cp310-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_regex_2023.10.3_cp310_cp310_manylinux_2_17_aarch64.manylinux2014_aarch64",
        urls = [
            "https://files.pythonhosted.org/packages/5d/ba/a9b104f3e78d9a08c093c325419ddd4a03fc04e9f391f8cf580cdf21a0fe/regex-2023.10.3-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        ],
        sha256 = "4cd1bccf99d3ef1ab6ba835308ad85be040e6a11b0977ef7ea8c8005f01a3c29",
        downloaded_file_path = "regex-2023.10.3-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_regex_2023.10.3_cp310_cp310_manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/bd/79/ced572f3316e2a1ddfec801d69c167ab3c2d5f76c12918b4f0de147b3180/regex-2023.10.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl",
        ],
        sha256 = "4a8bf76e3182797c6b1afa5b822d1d5802ff30284abe4599e1247be4fd6b03be",
        downloaded_file_path = "regex-2023.10.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_regex_2023.10.3_cp311_cp311_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/4d/d3/38b09813a32618acd437906c4d0194119e27139dbcd7486e69d58e375a27/regex-2023.10.3-cp311-cp311-macosx_11_0_arm64.whl",
        ],
        sha256 = "c7964c2183c3e6cce3f497e3a9f49d182e969f2dc3aeeadfa18945ff7bdd7051",
        downloaded_file_path = "regex-2023.10.3-cp311-cp311-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_regex_2023.10.3_cp311_cp311_manylinux_2_17_aarch64.manylinux2014_aarch64",
        urls = [
            "https://files.pythonhosted.org/packages/be/5d/bf0e6eca09839b82ac640adabad2560cc39a69bf802c6d2759e52c113f7e/regex-2023.10.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        ],
        sha256 = "4ef80829117a8061f974b2fda8ec799717242353bff55f8a29411794d635d964",
        downloaded_file_path = "regex-2023.10.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_regex_2023.10.3_cp311_cp311_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/f2/b8/b1ec82fce93064a73ba67f2bb158ec9cac4a0e8f0b6942268ec963947329/regex-2023.10.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        ],
        sha256 = "8d1f21af4c1539051049796a0f50aa342f9a27cde57318f2fc41ed50b0dbc4ac",
        downloaded_file_path = "regex-2023.10.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_regex_2023.10.3_cp312_cp312_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/c6/a9/d543130248a2ceba74787518aea5d4a9f9373fb09fa860283fb0afa2718b/regex-2023.10.3-cp312-cp312-macosx_11_0_arm64.whl",
        ],
        sha256 = "be5e22bbb67924dea15039c3282fa4cc6cdfbe0cbbd1c0515f9223186fc2ec5f",
        downloaded_file_path = "regex-2023.10.3-cp312-cp312-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_regex_2023.10.3_cp312_cp312_manylinux_2_17_aarch64.manylinux2014_aarch64",
        urls = [
            "https://files.pythonhosted.org/packages/38/a4/645e381727142609772a37c50d2f4b0316bbfa40a6e5b1ad27f8493767f4/regex-2023.10.3-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        ],
        sha256 = "4a992f702c9be9c72fa46f01ca6e18d131906a7180950958f766c2aa294d4b41",
        downloaded_file_path = "regex-2023.10.3-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_regex_2023.10.3_cp312_cp312_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/0a/9e/f5bac36b963741bf3abbcd719f7a7375b95486efcb27c1e2faaaead26c67/regex-2023.10.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        ],
        sha256 = "a9e908ef5889cda4de038892b9accc36d33d72fb3e12c747e2799a0e806ec841",
        downloaded_file_path = "regex-2023.10.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_setuptools_68.2.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl",
        ],
        sha256 = "b454a35605876da60632df1a60f736524eb73cc47bbc9f3f1ef1b644de74fd2a",
        downloaded_file_path = "setuptools-68.2.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_six_1.16.0_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl",
        ],
        sha256 = "8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254",
        downloaded_file_path = "six-1.16.0-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_stack_data_0.6.3_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/f1/7b/ce1eafaf1a76852e2ec9b22edecf1daa58175c090266e9f6c64afcd81d91/stack_data-0.6.3-py3-none-any.whl",
        ],
        sha256 = "d5558e0c25a4cb0853cddad3d77da9891a08cb85dd9f9f91b9f8cd66e511e695",
        downloaded_file_path = "stack_data-0.6.3-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_traitlets_5.14.3_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/00/c0/8f5d070730d7836adc9c9b6408dec68c6ced86b304a9b26a14df072a6e8c/traitlets-5.14.3-py3-none-any.whl",
        ],
        sha256 = "b74e89e397b1ed28cc831db7aea759ba6640cb3de13090ca145426688ff1ac4f",
        downloaded_file_path = "traitlets-5.14.3-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_wcwidth_0.2.13_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/fd/84/fd2ba7aafacbad3c4201d395674fc6348826569da3c0937e75505ead3528/wcwidth-0.2.13-py2.py3-none-any.whl",
        ],
        sha256 = "3da69048e4540d84af32131829ff948f1e022c1c6bdb8d6102117aac784f6859",
        downloaded_file_path = "wcwidth-0.2.13-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_wheel_0.41.3_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/fa/7f/4c07234086edbce4a0a446209dc0cb08a19bb206a3ea53b2f56a403f983b/wheel-0.41.3-py3-none-any.whl",
        ],
        sha256 = "488609bc63a29322326e05560731bf7bfea8e48ad646e1f5e40d366607de0942",
        downloaded_file_path = "wheel-0.41.3-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_zope.interface_5.5.2_cp310_cp310_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/01/45/9ff2b9281597da5fcf84995ca18cde71abf248c98bfc7c6bdee60af87dbb/zope.interface-5.5.2-cp310-cp310-macosx_11_0_arm64.whl",
        ],
        sha256 = "5334e2ef60d3d9439c08baedaf8b84dc9bb9522d0dacbc10572ef5609ef8db6d",
        downloaded_file_path = "zope.interface-5.5.2-cp310-cp310-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_zope.interface_5.5.2_cp310_cp310_manylinux_2_17_aarch64.manylinux2014_aarch64",
        urls = [
            "https://files.pythonhosted.org/packages/ed/c9/265a39c9933aef7cea402c25fb80f6455407d74ed761816496166f55d05a/zope.interface-5.5.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        ],
        sha256 = "dc26c8d44472e035d59d6f1177eb712888447f5799743da9c398b0339ed90b1b",
        downloaded_file_path = "zope.interface-5.5.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_zope.interface_5.5.2_cp310_cp310_manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/48/fa/25d98f89f07e4524e465d4d5ca4164a443628eae0548f1ec085ea0ed2889/zope.interface-5.5.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl",
        ],
        sha256 = "f98d4bd7bbb15ca701d19b93263cc5edfd480c3475d163f137385f49e5b3a3a7",
        downloaded_file_path = "zope.interface-5.5.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_zope.interface_5.5.2_cp311_cp311_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/1a/ba/ca524f2f7184346e93bae317580c4906bc2e81bdac6e3b68b64c632a7df0/zope.interface-5.5.2-cp311-cp311-macosx_11_0_arm64.whl",
        ],
        sha256 = "765d703096ca47aa5d93044bf701b00bbce4d903a95b41fff7c3796e747b1f1d",
        downloaded_file_path = "zope.interface-5.5.2-cp311-cp311-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_zope.interface_5.5.2_cp311_cp311_manylinux_2_17_aarch64.manylinux2014_aarch64",
        urls = [
            "https://files.pythonhosted.org/packages/fb/a7/4e2a58146d909115e102ce4038e3e8672f566174c55d8fa75325151b11fb/zope.interface-5.5.2-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        ],
        sha256 = "e945de62917acbf853ab968d8916290548df18dd62c739d862f359ecd25842a6",
        downloaded_file_path = "zope.interface-5.5.2-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_zstandard_0.22.0_cp310_cp310_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/fc/e5/a1fa6f70764777553cb8ab668690ba793ebf512b3d415e28720d2275d445/zstandard-0.22.0-cp310-cp310-macosx_11_0_arm64.whl",
        ],
        sha256 = "2ac9957bc6d2403c4772c890916bf181b2653640da98f32e04b96e4d6fb3252a",
        downloaded_file_path = "zstandard-0.22.0-cp310-cp310-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_zstandard_0.22.0_cp310_cp310_manylinux_2_17_aarch64.manylinux2014_aarch64",
        urls = [
            "https://files.pythonhosted.org/packages/8e/3b/0284ed7b2612f793d2490339c1b772232c04a6f20dbbdec050020bd730b2/zstandard-0.22.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        ],
        sha256 = "fe3390c538f12437b859d815040763abc728955a52ca6ff9c5d4ac707c4ad98e",
        downloaded_file_path = "zstandard-0.22.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_zstandard_0.22.0_cp310_cp310_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/c9/79/07f6d2670fa2708ae3b79aabb82da78e9cbdb08d9bafadf8638d356775ff/zstandard-0.22.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        ],
        sha256 = "1958100b8a1cc3f27fa21071a55cb2ed32e9e5df4c3c6e661c193437f171cba2",
        downloaded_file_path = "zstandard-0.22.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_zstandard_0.22.0_cp311_cp311_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/54/fc/c1b1a1e140451f3362789f546731b3ef36c78668be19d7fc6fbd4326b535/zstandard-0.22.0-cp311-cp311-macosx_11_0_arm64.whl",
        ],
        sha256 = "a97079b955b00b732c6f280d5023e0eefe359045e8b83b08cf0333af9ec78f26",
        downloaded_file_path = "zstandard-0.22.0-cp311-cp311-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_zstandard_0.22.0_cp311_cp311_manylinux_2_17_aarch64.manylinux2014_aarch64",
        urls = [
            "https://files.pythonhosted.org/packages/68/fb/0a9389ee8ccc532ac4567562c7746bd7537d16bc5b079b2696fe3c510c37/zstandard-0.22.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        ],
        sha256 = "445b47bc32de69d990ad0f34da0e20f535914623d1e506e74d6bc5c9dc40bb09",
        downloaded_file_path = "zstandard-0.22.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_zstandard_0.22.0_cp311_cp311_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/80/6a/f8a618f84aafb9c373a959e7e51ad34bda73f1d99cd856c05c8f0b78e87f/zstandard-0.22.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        ],
        sha256 = "33591d59f4956c9812f8063eff2e2c0065bc02050837f152574069f5f9f17775",
        downloaded_file_path = "zstandard-0.22.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_zstandard_0.22.0_cp312_cp312_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/7d/80/9e40e57ba17dbbf6c55bcf0ac4ee533c367285209f309bdd9ab290c40536/zstandard-0.22.0-cp312-cp312-macosx_11_0_arm64.whl",
        ],
        sha256 = "f9b2cde1cd1b2a10246dbc143ba49d942d14fb3d2b4bccf4618d475c65464912",
        downloaded_file_path = "zstandard-0.22.0-cp312-cp312-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_zstandard_0.22.0_cp312_cp312_manylinux_2_17_aarch64.manylinux2014_aarch64",
        urls = [
            "https://files.pythonhosted.org/packages/47/44/be2d67304ba9bf4694ffcaa99d146814d70c4cb0bfc00e0e86fdfae66a31/zstandard-0.22.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        ],
        sha256 = "a88b7df61a292603e7cd662d92565d915796b094ffb3d206579aaebac6b85d5f",
        downloaded_file_path = "zstandard-0.22.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
    )

    maybe(
        http_file,
        name = "pdm_lock_wheel_zstandard_0.22.0_cp312_cp312_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/e5/01/080939755ca12ebbb7fc38b6f4ddecd5e8c416d571d4927ece1360baba2c/zstandard-0.22.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        ],
        sha256 = "466e6ad8caefb589ed281c076deb6f0cd330e8bc13c5035854ffb9c2014b118c",
        downloaded_file_path = "zstandard-0.22.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )
