# This file is generated by rules_pycross.
# It is not intended for manual editing.

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@jvolkman_rules_pycross//pycross:defs.bzl", "pycross_wheel_build", "pycross_wheel_library", "pypi_file")

PINS = {
    "appnope": "appnope_0.1.3",
    "asttokens": "asttokens_2.2.1",
    "backcall": "backcall_0.2.0",
    "cffi": "cffi_1.15.1",
    "cognitojwt": "cognitojwt_1.4.1",
    "cons": "cons_0.4.6",
    "cryptography": "cryptography_41.0.2",
    "cython": "cython_0.29.36",
    "decorator": "decorator_5.1.1",
    "ecdsa": "ecdsa_0.18.0",
    "etuples": "etuples_0.3.9",
    "executing": "executing_1.2.0",
    "filelock": "filelock_3.12.2",
    "future": "future_0.18.2",
    "greenlet": "greenlet_2.0.2",
    "importlib_metadata": "importlib_metadata_6.8.0",
    "ipython": "ipython_8.14.0",
    "jaraco_classes": "jaraco_classes_3.3.0",
    "jedi": "jedi_0.19.0",
    "jeepney": "jeepney_0.8.0",
    "keyring": "keyring_23.9.1",
    "logical_unification": "logical_unification_0.4.6",
    "matplotlib_inline": "matplotlib_inline_0.1.6",
    "minikanren": "minikanren_1.0.3",
    "more_itertools": "more_itertools_10.0.0",
    "multipledispatch": "multipledispatch_1.0.0",
    "numpy": "numpy_1.22.3",
    "parso": "parso_0.8.3",
    "pexpect": "pexpect_4.8.0",
    "pickleshare": "pickleshare_0.7.5",
    "prompt_toolkit": "prompt_toolkit_3.0.39",
    "ptyprocess": "ptyprocess_0.7.0",
    "pure_eval": "pure_eval_0.2.2",
    "pyasn1": "pyasn1_0.5.0",
    "pycparser": "pycparser_2.21",
    "pygments": "pygments_2.15.1",
    "pytensor": "pytensor_2.12.3",
    "python_jose": "python_jose_3.1.0",
    "rsa": "rsa_4.9",
    "scipy": "scipy_1.9.3",
    "secretstorage": "secretstorage_3.3.3",
    "setproctitle": "setproctitle_1.2.2",
    "setuptools": "setuptools_60.0.5",
    "six": "six_1.16.0",
    "sqlalchemy": "sqlalchemy_2.0.19",
    "sqlalchemy_utils": "sqlalchemy_utils_0.38.2",
    "stack_data": "stack_data_0.6.2",
    "toolz": "toolz_0.12.0",
    "traitlets": "traitlets_5.9.0",
    "tree_sitter": "tree_sitter_0.20.0",
    "typing_extensions": "typing_extensions_4.7.1",
    "wcwidth": "wcwidth_0.2.6",
    "wheel": "wheel_0.37.0",
    "zipp": "zipp_3.16.2",
}

def targets():
    for pin_name, pin_target in PINS.items():
        native.alias(
            name = pin_name,
            actual = ":" + pin_target,
        )

    native.config_setting(
        name = "_env_python_darwin_arm64",
        constraint_values = [
            "@platforms//os:osx",
            "@platforms//cpu:arm64",
        ],
    )

    native.config_setting(
        name = "_env_python_darwin_x86_64",
        constraint_values = [
            "@platforms//os:osx",
            "@platforms//cpu:x86_64",
        ],
    )

    native.config_setting(
        name = "_env_python_linux_aarch64",
        constraint_values = [
            "@platforms//os:linux",
            "@platforms//cpu:arm64",
        ],
    )

    native.config_setting(
        name = "_env_python_linux_x86_64",
        constraint_values = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    )

    _target = select({
        ":_env_python_darwin_arm64": "@//:python_darwin_arm64",
        ":_env_python_darwin_x86_64": "@//:python_darwin_x86_64",
        ":_env_python_linux_aarch64": "@//:python_linux_aarch64",
        ":_env_python_linux_x86_64": "@//:python_linux_x86_64",
    })

    pycross_wheel_library(
        name = "appnope_0.1.3",
        wheel = "@example_lock_wheel_appnope_0.1.3_py2.py3_none_any//file",
    )

    _asttokens_2_2_1_deps = [
        ":six_1.16.0",
    ]

    pycross_wheel_library(
        name = "asttokens_2.2.1",
        deps = _asttokens_2_2_1_deps,
        wheel = "@example_lock_wheel_asttokens_2.2.1_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "backcall_0.2.0",
        wheel = "@example_lock_wheel_backcall_0.2.0_py2.py3_none_any//file",
    )

    _cffi_1_15_1_deps = [
        ":pycparser_2.21",
    ]

    pycross_wheel_library(
        name = "cffi_1.15.1",
        deps = _cffi_1_15_1_deps,
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_cffi_1.15.1_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_cffi_1.15.1_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_aarch64": "@example_lock_wheel_cffi_1.15.1_cp39_cp39_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_cffi_1.15.1_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    _cognitojwt_1_4_1_deps = [
        ":python_jose_3.1.0",
    ]

    pycross_wheel_library(
        name = "cognitojwt_1.4.1",
        deps = _cognitojwt_1_4_1_deps,
        wheel = "@example_lock_wheel_cognitojwt_1.4.1_py3_none_any//file",
    )

    _cons_0_4_6_deps = [
        ":logical_unification_0.4.6",
    ]

    _cons_0_4_6_build_deps = [
        ":setuptools_60.0.5",
        ":wheel_0.37.0",
    ]

    pycross_wheel_build(
        name = "_build_cons_0.4.6",
        sdist = "@example_lock_sdist_cons_0.4.6//file",
        target_environment = _target,
        deps = _cons_0_4_6_deps + _cons_0_4_6_build_deps,
        tags = ["manual"],
    )

    pycross_wheel_library(
        name = "cons_0.4.6",
        deps = _cons_0_4_6_deps,
        wheel = ":_build_cons_0.4.6",
    )

    _cryptography_41_0_2_deps = [
        ":cffi_1.15.1",
    ]

    pycross_wheel_library(
        name = "cryptography_41.0.2",
        deps = _cryptography_41_0_2_deps,
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_cryptography_41.0.2_cp37_abi3_macosx_10_12_universal2//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_cryptography_41.0.2_cp37_abi3_macosx_10_12_x86_64//file",
            ":_env_python_linux_aarch64": "@example_lock_wheel_cryptography_41.0.2_cp37_abi3_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_cryptography_41.0.2_cp37_abi3_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "cython_0.29.36",
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_cython_0.29.36_py2.py3_none_any//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_cython_0.29.36_py2.py3_none_any//file",
            ":_env_python_linux_aarch64": "@example_lock_wheel_cython_0.29.36_cp39_cp39_manylinux_2_17_aarch64.manylinux2014_aarch64.manylinux_2_24_aarch64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_cython_0.29.36_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "decorator_5.1.1",
        wheel = "@example_lock_wheel_decorator_5.1.1_py3_none_any//file",
    )

    _ecdsa_0_18_0_deps = [
        ":six_1.16.0",
    ]

    pycross_wheel_library(
        name = "ecdsa_0.18.0",
        deps = _ecdsa_0_18_0_deps,
        wheel = "@example_lock_wheel_ecdsa_0.18.0_py2.py3_none_any//file",
    )

    _etuples_0_3_9_deps = [
        ":cons_0.4.6",
        ":multipledispatch_1.0.0",
    ]

    _etuples_0_3_9_build_deps = [
        ":setuptools_60.0.5",
        ":wheel_0.37.0",
    ]

    pycross_wheel_build(
        name = "_build_etuples_0.3.9",
        sdist = "@example_lock_sdist_etuples_0.3.9//file",
        target_environment = _target,
        deps = _etuples_0_3_9_deps + _etuples_0_3_9_build_deps,
        tags = ["manual"],
    )

    pycross_wheel_library(
        name = "etuples_0.3.9",
        deps = _etuples_0_3_9_deps,
        wheel = ":_build_etuples_0.3.9",
    )

    pycross_wheel_library(
        name = "executing_1.2.0",
        wheel = "@example_lock_wheel_executing_1.2.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "filelock_3.12.2",
        wheel = "@example_lock_wheel_filelock_3.12.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "future_0.18.2",
        wheel = "@//deps:overridden_future_0.18.2",
    )

    _greenlet_2_0_2_build_deps = [
        ":setuptools_60.0.5",
        ":wheel_0.37.0",
    ]

    pycross_wheel_build(
        name = "_build_greenlet_2.0.2",
        sdist = "@example_lock_sdist_greenlet_2.0.2//file",
        target_environment = _target,
        deps = _greenlet_2_0_2_build_deps,
        tags = ["manual"],
    )

    pycross_wheel_library(
        name = "greenlet_2.0.2",
        wheel = select({
            ":_env_python_darwin_arm64": ":_build_greenlet_2.0.2",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_greenlet_2.0.2_cp39_cp39_macosx_11_0_x86_64//file",
            ":_env_python_linux_aarch64": "@example_lock_wheel_greenlet_2.0.2_cp39_cp39_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_greenlet_2.0.2_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    _importlib_metadata_6_8_0_deps = [
        ":zipp_3.16.2",
    ]

    pycross_wheel_library(
        name = "importlib_metadata_6.8.0",
        deps = _importlib_metadata_6_8_0_deps,
        wheel = "@example_lock_wheel_importlib_metadata_6.8.0_py3_none_any//file",
    )

    _ipython_8_14_0_deps = [
        ":backcall_0.2.0",
        ":decorator_5.1.1",
        ":jedi_0.19.0",
        ":matplotlib_inline_0.1.6",
        ":pexpect_4.8.0",
        ":pickleshare_0.7.5",
        ":prompt_toolkit_3.0.39",
        ":pygments_2.15.1",
        ":stack_data_0.6.2",
        ":traitlets_5.9.0",
        ":typing_extensions_4.7.1",
    ] + select({
        ":_env_python_darwin_arm64": [
            ":appnope_0.1.3",
        ],
        ":_env_python_darwin_x86_64": [
            ":appnope_0.1.3",
        ],
        "//conditions:default": [],
    })

    pycross_wheel_library(
        name = "ipython_8.14.0",
        deps = _ipython_8_14_0_deps,
        wheel = "@example_lock_wheel_ipython_8.14.0_py3_none_any//file",
    )

    _jaraco_classes_3_3_0_deps = [
        ":more_itertools_10.0.0",
    ]

    pycross_wheel_library(
        name = "jaraco_classes_3.3.0",
        deps = _jaraco_classes_3_3_0_deps,
        wheel = "@example_lock_wheel_jaraco.classes_3.3.0_py3_none_any//file",
    )

    _jedi_0_19_0_deps = [
        ":parso_0.8.3",
    ]

    pycross_wheel_library(
        name = "jedi_0.19.0",
        deps = _jedi_0_19_0_deps,
        wheel = "@example_lock_wheel_jedi_0.19.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "jeepney_0.8.0",
        wheel = "@example_lock_wheel_jeepney_0.8.0_py3_none_any//file",
    )

    _keyring_23_9_1_deps = [
        ":importlib_metadata_6.8.0",
        ":jaraco_classes_3.3.0",
    ] + select({
        ":_env_python_linux_aarch64": [
            ":jeepney_0.8.0",
            ":secretstorage_3.3.3",
        ],
        ":_env_python_linux_x86_64": [
            ":jeepney_0.8.0",
            ":secretstorage_3.3.3",
        ],
        "//conditions:default": [],
    })

    pycross_wheel_library(
        name = "keyring_23.9.1",
        deps = _keyring_23_9_1_deps,
        wheel = "@example_lock_wheel_keyring_23.9.1_py3_none_any//file",
    )

    _logical_unification_0_4_6_deps = [
        ":multipledispatch_1.0.0",
        ":toolz_0.12.0",
    ]

    _logical_unification_0_4_6_build_deps = [
        ":setuptools_60.0.5",
        ":wheel_0.37.0",
    ]

    pycross_wheel_build(
        name = "_build_logical_unification_0.4.6",
        sdist = "@example_lock_sdist_logical_unification_0.4.6//file",
        target_environment = _target,
        deps = _logical_unification_0_4_6_deps + _logical_unification_0_4_6_build_deps,
        tags = ["manual"],
    )

    pycross_wheel_library(
        name = "logical_unification_0.4.6",
        deps = _logical_unification_0_4_6_deps,
        wheel = ":_build_logical_unification_0.4.6",
    )

    _matplotlib_inline_0_1_6_deps = [
        ":traitlets_5.9.0",
    ]

    pycross_wheel_library(
        name = "matplotlib_inline_0.1.6",
        deps = _matplotlib_inline_0_1_6_deps,
        wheel = "@example_lock_wheel_matplotlib_inline_0.1.6_py3_none_any//file",
    )

    _minikanren_1_0_3_deps = [
        ":cons_0.4.6",
        ":etuples_0.3.9",
        ":logical_unification_0.4.6",
        ":multipledispatch_1.0.0",
        ":toolz_0.12.0",
    ]

    _minikanren_1_0_3_build_deps = [
        ":setuptools_60.0.5",
        ":wheel_0.37.0",
    ]

    pycross_wheel_build(
        name = "_build_minikanren_1.0.3",
        sdist = "@example_lock_sdist_minikanren_1.0.3//file",
        target_environment = _target,
        deps = _minikanren_1_0_3_deps + _minikanren_1_0_3_build_deps,
        tags = ["manual"],
    )

    pycross_wheel_library(
        name = "minikanren_1.0.3",
        deps = _minikanren_1_0_3_deps,
        wheel = ":_build_minikanren_1.0.3",
    )

    pycross_wheel_library(
        name = "more_itertools_10.0.0",
        wheel = "@example_lock_wheel_more_itertools_10.0.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "multipledispatch_1.0.0",
        wheel = "@example_lock_wheel_multipledispatch_1.0.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "numpy_1.22.3",
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_numpy_1.22.3_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_numpy_1.22.3_cp39_cp39_macosx_10_14_x86_64//file",
            ":_env_python_linux_aarch64": "@example_lock_wheel_numpy_1.22.3_cp39_cp39_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_numpy_1.22.3_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "parso_0.8.3",
        wheel = "@example_lock_wheel_parso_0.8.3_py2.py3_none_any//file",
    )

    _pexpect_4_8_0_deps = [
        ":ptyprocess_0.7.0",
    ]

    pycross_wheel_library(
        name = "pexpect_4.8.0",
        deps = _pexpect_4_8_0_deps,
        wheel = "@example_lock_wheel_pexpect_4.8.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pickleshare_0.7.5",
        wheel = "@example_lock_wheel_pickleshare_0.7.5_py2.py3_none_any//file",
    )

    _prompt_toolkit_3_0_39_deps = [
        ":wcwidth_0.2.6",
    ]

    pycross_wheel_library(
        name = "prompt_toolkit_3.0.39",
        deps = _prompt_toolkit_3_0_39_deps,
        wheel = "@example_lock_wheel_prompt_toolkit_3.0.39_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "ptyprocess_0.7.0",
        wheel = "@example_lock_wheel_ptyprocess_0.7.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pure_eval_0.2.2",
        wheel = "@example_lock_wheel_pure_eval_0.2.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pyasn1_0.5.0",
        wheel = "@example_lock_wheel_pyasn1_0.5.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pycparser_2.21",
        wheel = "@example_lock_wheel_pycparser_2.21_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pygments_2.15.1",
        wheel = "@example_lock_wheel_pygments_2.15.1_py3_none_any//file",
    )

    _pytensor_2_12_3_deps = [
        ":cons_0.4.6",
        ":etuples_0.3.9",
        ":filelock_3.12.2",
        ":logical_unification_0.4.6",
        ":minikanren_1.0.3",
        ":numpy_1.22.3",
        ":scipy_1.9.3",
        ":setuptools_60.0.5",
        ":typing_extensions_4.7.1",
    ]

    pycross_wheel_build(
        name = "_build_pytensor_2.12.3",
        sdist = "@example_lock_sdist_pytensor_2.12.3//file",
        target_environment = _target,
        deps = _pytensor_2_12_3_deps,
        tags = ["manual"],
    )

    pycross_wheel_library(
        name = "pytensor_2.12.3",
        deps = _pytensor_2_12_3_deps,
        wheel = select({
            ":_env_python_darwin_arm64": ":_build_pytensor_2.12.3",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_pytensor_2.12.3_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_aarch64": ":_build_pytensor_2.12.3",
            ":_env_python_linux_x86_64": "@example_lock_wheel_pytensor_2.12.3_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    _python_jose_3_1_0_deps = [
        ":cryptography_41.0.2",
        ":ecdsa_0.18.0",
        ":pyasn1_0.5.0",
        ":rsa_4.9",
        ":six_1.16.0",
    ]

    pycross_wheel_library(
        name = "python_jose_3.1.0",
        deps = _python_jose_3_1_0_deps,
        wheel = "@example_lock_wheel_python_jose_3.1.0_py2.py3_none_any//file",
    )

    _rsa_4_9_deps = [
        ":pyasn1_0.5.0",
    ]

    pycross_wheel_library(
        name = "rsa_4.9",
        deps = _rsa_4_9_deps,
        wheel = "@example_lock_wheel_rsa_4.9_py3_none_any//file",
    )

    _scipy_1_9_3_deps = [
        ":numpy_1.22.3",
    ]

    pycross_wheel_library(
        name = "scipy_1.9.3",
        deps = _scipy_1_9_3_deps,
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_scipy_1.9.3_cp39_cp39_macosx_12_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_scipy_1.9.3_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_aarch64": "@example_lock_wheel_scipy_1.9.3_cp39_cp39_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_scipy_1.9.3_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    _secretstorage_3_3_3_deps = [
        ":cryptography_41.0.2",
        ":jeepney_0.8.0",
    ]

    pycross_wheel_library(
        name = "secretstorage_3.3.3",
        deps = _secretstorage_3_3_3_deps,
        wheel = "@example_lock_wheel_secretstorage_3.3.3_py3_none_any//file",
    )

    _setproctitle_1_2_2_build_deps = [
        ":setuptools_60.0.5",
        ":wheel_0.37.0",
    ]

    pycross_wheel_build(
        name = "_build_setproctitle_1.2.2",
        sdist = "@example_lock_sdist_setproctitle_1.2.2//file",
        target_environment = _target,
        deps = _setproctitle_1_2_2_build_deps,
        tags = ["manual"],
    )

    pycross_wheel_library(
        name = "setproctitle_1.2.2",
        wheel = ":_build_setproctitle_1.2.2",
    )

    pycross_wheel_library(
        name = "setuptools_60.0.5",
        wheel = "@example_lock_wheel_setuptools_60.0.5_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "six_1.16.0",
        wheel = "@example_lock_wheel_six_1.16.0_py2.py3_none_any//file",
    )

    _sqlalchemy_2_0_19_deps = [
        ":typing_extensions_4.7.1",
    ] + select({
        ":_env_python_darwin_x86_64": [
            ":greenlet_2.0.2",
        ],
        ":_env_python_linux_aarch64": [
            ":greenlet_2.0.2",
        ],
        ":_env_python_linux_x86_64": [
            ":greenlet_2.0.2",
        ],
        "//conditions:default": [],
    })

    _sqlalchemy_2_0_19_build_deps = [
        ":setuptools_60.0.5",
        ":wheel_0.37.0",
    ]

    pycross_wheel_library(
        name = "sqlalchemy_2.0.19",
        deps = _sqlalchemy_2_0_19_deps,
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_sqlalchemy_2.0.19_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_sqlalchemy_2.0.19_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_aarch64": "@example_lock_wheel_sqlalchemy_2.0.19_cp39_cp39_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_sqlalchemy_2.0.19_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    _sqlalchemy_utils_0_38_2_deps = [
        ":six_1.16.0",
        ":sqlalchemy_2.0.19",
    ]

    pycross_wheel_library(
        name = "sqlalchemy_utils_0.38.2",
        deps = _sqlalchemy_utils_0_38_2_deps,
        wheel = "@example_lock_wheel_sqlalchemy_utils_0.38.2_py3_none_any//file",
    )

    _stack_data_0_6_2_deps = [
        ":asttokens_2.2.1",
        ":executing_1.2.0",
        ":pure_eval_0.2.2",
    ]

    pycross_wheel_library(
        name = "stack_data_0.6.2",
        deps = _stack_data_0_6_2_deps,
        wheel = "@example_lock_wheel_stack_data_0.6.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "toolz_0.12.0",
        wheel = "@example_lock_wheel_toolz_0.12.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "traitlets_5.9.0",
        wheel = "@example_lock_wheel_traitlets_5.9.0_py3_none_any//file",
    )

    _tree_sitter_0_20_0_build_deps = [
        ":setuptools_60.0.5",
        ":wheel_0.37.0",
    ]

    pycross_wheel_build(
        name = "_build_tree_sitter_0.20.0",
        sdist = "@example_lock_sdist_tree_sitter_0.20.0//file",
        target_environment = _target,
        deps = _tree_sitter_0_20_0_build_deps,
        tags = ["manual"],
    )

    pycross_wheel_library(
        name = "tree_sitter_0.20.0",
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_tree_sitter_0.20.0_cp39_cp39_macosx_12_0_arm64//file",
            ":_env_python_darwin_x86_64": ":_build_tree_sitter_0.20.0",
            ":_env_python_linux_aarch64": ":_build_tree_sitter_0.20.0",
            ":_env_python_linux_x86_64": ":_build_tree_sitter_0.20.0",
        }),
    )

    pycross_wheel_library(
        name = "typing_extensions_4.7.1",
        wheel = "@example_lock_wheel_typing_extensions_4.7.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "wcwidth_0.2.6",
        wheel = "@example_lock_wheel_wcwidth_0.2.6_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "wheel_0.37.0",
        wheel = "@example_lock_wheel_wheel_0.37.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "zipp_3.16.2",
        wheel = "@example_lock_wheel_zipp_3.16.2_py3_none_any//file",
    )

def repositories():
    maybe(
        pypi_file,
        name = "example_lock_sdist_cons_0.4.6",
        package_name = "cons",
        package_version = "0.4.6",
        filename = "cons-0.4.6.tar.gz",
        sha256 = "669fe9d5ee916d5e42b9cac6acc911df803d04f2e945c1604982a04d27a29b47",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_sdist_etuples_0.3.9",
        package_name = "etuples",
        package_version = "0.3.9",
        filename = "etuples-0.3.9.tar.gz",
        sha256 = "a474e586683d8ba8d842ba29305005ceed1c08371a4b4b0e0e232527137e5ea3",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_sdist_future_0.18.2",
        package_name = "future",
        package_version = "0.18.2",
        filename = "future-0.18.2.tar.gz",
        sha256 = "b1bead90b70cf6ec3f0710ae53a525360fa360d306a86583adc6bf83a4db537d",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_sdist_greenlet_2.0.2",
        package_name = "greenlet",
        package_version = "2.0.2",
        filename = "greenlet-2.0.2.tar.gz",
        sha256 = "e7c8dc13af7db097bed64a051d2dd49e9f0af495c26995c00a9ee842690d34c0",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_sdist_logical_unification_0.4.6",
        package_name = "logical-unification",
        package_version = "0.4.6",
        filename = "logical-unification-0.4.6.tar.gz",
        sha256 = "908435123f8a106fa4dcf9bf1b75c7beb309fa2bbecf277868af8f1c212650a0",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_sdist_minikanren_1.0.3",
        package_name = "minikanren",
        package_version = "1.0.3",
        filename = "miniKanren-1.0.3.tar.gz",
        sha256 = "1ec8bdb01144ad5e8752c7c297fb8a122db920f859276d25a72d164e998d7f6e",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_sdist_pytensor_2.12.3",
        package_name = "pytensor",
        package_version = "2.12.3",
        filename = "pytensor-2.12.3.tar.gz",
        sha256 = "fa82d29ef0594e0a2751eaad40882dcd6af51333c28be0d79c1d0de9f3a81a86",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_sdist_setproctitle_1.2.2",
        package_name = "setproctitle",
        package_version = "1.2.2",
        filename = "setproctitle-1.2.2.tar.gz",
        sha256 = "7dfb472c8852403d34007e01d6e3c68c57eb66433fb8a5c77b13b89a160d97df",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_sdist_tree_sitter_0.20.0",
        package_name = "tree-sitter",
        package_version = "0.20.0",
        filename = "tree_sitter-0.20.0.tar.gz",
        sha256 = "1940f64be1e8c9c3c0e34a2258f1e4c324207534d5b1eefc5ab2960a9d98f668",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_appnope_0.1.3_py2.py3_none_any",
        package_name = "appnope",
        package_version = "0.1.3",
        filename = "appnope-0.1.3-py2.py3-none-any.whl",
        sha256 = "265a455292d0bd8a72453494fa24df5a11eb18373a60c7c0430889f22548605e",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_asttokens_2.2.1_py2.py3_none_any",
        package_name = "asttokens",
        package_version = "2.2.1",
        filename = "asttokens-2.2.1-py2.py3-none-any.whl",
        sha256 = "6b0ac9e93fb0335014d382b8fa9b3afa7df546984258005da0b9e7095b3deb1c",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_backcall_0.2.0_py2.py3_none_any",
        package_name = "backcall",
        package_version = "0.2.0",
        filename = "backcall-0.2.0-py2.py3-none-any.whl",
        sha256 = "fbbce6a29f263178a1f7915c1940bde0ec2b2a967566fe1c65c1dfb7422bd255",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_cffi_1.15.1_cp39_cp39_macosx_10_9_x86_64",
        package_name = "cffi",
        package_version = "1.15.1",
        filename = "cffi-1.15.1-cp39-cp39-macosx_10_9_x86_64.whl",
        sha256 = "54a2db7b78338edd780e7ef7f9f6c442500fb0d41a5a4ea24fff1c929d5af585",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_cffi_1.15.1_cp39_cp39_macosx_11_0_arm64",
        package_name = "cffi",
        package_version = "1.15.1",
        filename = "cffi-1.15.1-cp39-cp39-macosx_11_0_arm64.whl",
        sha256 = "fcd131dd944808b5bdb38e6f5b53013c5aa4f334c5cad0c72742f6eba4b73db0",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_cffi_1.15.1_cp39_cp39_manylinux_2_17_aarch64.manylinux2014_aarch64",
        package_name = "cffi",
        package_version = "1.15.1",
        filename = "cffi-1.15.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        sha256 = "6c9a799e985904922a4d207a94eae35c78ebae90e128f0c4e521ce339396be9d",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_cffi_1.15.1_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "cffi",
        package_version = "1.15.1",
        filename = "cffi-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "5d598b938678ebf3c67377cdd45e09d431369c3b1a5b331058c338e201f12b27",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_cognitojwt_1.4.1_py3_none_any",
        package_name = "cognitojwt",
        package_version = "1.4.1",
        filename = "cognitojwt-1.4.1-py3-none-any.whl",
        sha256 = "8ee189f82289d140dc750c91e8772436b64b94d071507ace42efc22c525f42ce",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_cryptography_41.0.2_cp37_abi3_macosx_10_12_universal2",
        package_name = "cryptography",
        package_version = "41.0.2",
        filename = "cryptography-41.0.2-cp37-abi3-macosx_10_12_universal2.whl",
        sha256 = "01f1d9e537f9a15b037d5d9ee442b8c22e3ae11ce65ea1f3316a41c78756b711",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_cryptography_41.0.2_cp37_abi3_macosx_10_12_x86_64",
        package_name = "cryptography",
        package_version = "41.0.2",
        filename = "cryptography-41.0.2-cp37-abi3-macosx_10_12_x86_64.whl",
        sha256 = "079347de771f9282fbfe0e0236c716686950c19dee1b76240ab09ce1624d76d7",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_cryptography_41.0.2_cp37_abi3_manylinux_2_17_aarch64.manylinux2014_aarch64",
        package_name = "cryptography",
        package_version = "41.0.2",
        filename = "cryptography-41.0.2-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        sha256 = "439c3cc4c0d42fa999b83ded80a9a1fb54d53c58d6e59234cfe97f241e6c781d",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_cryptography_41.0.2_cp37_abi3_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "cryptography",
        package_version = "41.0.2",
        filename = "cryptography-41.0.2-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "f14ad275364c8b4e525d018f6716537ae7b6d369c094805cae45300847e0894f",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_cython_0.29.36_cp39_cp39_manylinux_2_17_aarch64.manylinux2014_aarch64.manylinux_2_24_aarch64",
        package_name = "cython",
        package_version = "0.29.36",
        filename = "Cython-0.29.36-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.manylinux_2_24_aarch64.whl",
        sha256 = "bdc0a4cb99f55e6878d4b67a4bfee23823484915cb6b7e9c9dd01002dd3592ea",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_cython_0.29.36_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64",
        package_name = "cython",
        package_version = "0.29.36",
        filename = "Cython-0.29.36-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl",
        sha256 = "f0df6552be39853b10dfb5a10dbd08f5c49023d6b390d7ce92d4792a8b6e73ee",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_cython_0.29.36_py2.py3_none_any",
        package_name = "cython",
        package_version = "0.29.36",
        filename = "Cython-0.29.36-py2.py3-none-any.whl",
        sha256 = "95bb13d8be507425d03ebe051f90d4b2a9fdccc64e4f30b35645fdb7542742eb",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_decorator_5.1.1_py3_none_any",
        package_name = "decorator",
        package_version = "5.1.1",
        filename = "decorator-5.1.1-py3-none-any.whl",
        sha256 = "b8c3f85900b9dc423225913c5aace94729fe1fa9763b38939a95226f02d37186",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_ecdsa_0.18.0_py2.py3_none_any",
        package_name = "ecdsa",
        package_version = "0.18.0",
        filename = "ecdsa-0.18.0-py2.py3-none-any.whl",
        sha256 = "80600258e7ed2f16b9aa1d7c295bd70194109ad5a30fdee0eaeefef1d4c559dd",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_executing_1.2.0_py2.py3_none_any",
        package_name = "executing",
        package_version = "1.2.0",
        filename = "executing-1.2.0-py2.py3-none-any.whl",
        sha256 = "0314a69e37426e3608aada02473b4161d4caf5a4b244d1d0c48072b8fee7bacc",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_filelock_3.12.2_py3_none_any",
        package_name = "filelock",
        package_version = "3.12.2",
        filename = "filelock-3.12.2-py3-none-any.whl",
        sha256 = "cbb791cdea2a72f23da6ac5b5269ab0a0d161e9ef0100e653b69049a7706d1ec",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_greenlet_2.0.2_cp39_cp39_macosx_11_0_x86_64",
        package_name = "greenlet",
        package_version = "2.0.2",
        filename = "greenlet-2.0.2-cp39-cp39-macosx_11_0_x86_64.whl",
        sha256 = "88d9ab96491d38a5ab7c56dd7a3cc37d83336ecc564e4e8816dbed12e5aaefc8",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_greenlet_2.0.2_cp39_cp39_manylinux_2_17_aarch64.manylinux2014_aarch64",
        package_name = "greenlet",
        package_version = "2.0.2",
        filename = "greenlet-2.0.2-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        sha256 = "971ce5e14dc5e73715755d0ca2975ac88cfdaefcaab078a284fea6cfabf866df",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_greenlet_2.0.2_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "greenlet",
        package_version = "2.0.2",
        filename = "greenlet-2.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "94c817e84245513926588caf1152e3b559ff794d505555211ca041f032abbb6b",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_importlib_metadata_6.8.0_py3_none_any",
        package_name = "importlib-metadata",
        package_version = "6.8.0",
        filename = "importlib_metadata-6.8.0-py3-none-any.whl",
        sha256 = "3ebb78df84a805d7698245025b975d9d67053cd94c79245ba4b3eb694abe68bb",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_ipython_8.14.0_py3_none_any",
        package_name = "ipython",
        package_version = "8.14.0",
        filename = "ipython-8.14.0-py3-none-any.whl",
        sha256 = "248aca623f5c99a6635bc3857677b7320b9b8039f99f070ee0d20a5ca5a8e6bf",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_jaraco.classes_3.3.0_py3_none_any",
        package_name = "jaraco-classes",
        package_version = "3.3.0",
        filename = "jaraco.classes-3.3.0-py3-none-any.whl",
        sha256 = "10afa92b6743f25c0cf5f37c6bb6e18e2c5bb84a16527ccfc0040ea377e7aaeb",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_jedi_0.19.0_py2.py3_none_any",
        package_name = "jedi",
        package_version = "0.19.0",
        filename = "jedi-0.19.0-py2.py3-none-any.whl",
        sha256 = "cb8ce23fbccff0025e9386b5cf85e892f94c9b822378f8da49970471335ac64e",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_jeepney_0.8.0_py3_none_any",
        package_name = "jeepney",
        package_version = "0.8.0",
        filename = "jeepney-0.8.0-py3-none-any.whl",
        sha256 = "c0a454ad016ca575060802ee4d590dd912e35c122fa04e70306de3d076cce755",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_keyring_23.9.1_py3_none_any",
        package_name = "keyring",
        package_version = "23.9.1",
        filename = "keyring-23.9.1-py3-none-any.whl",
        sha256 = "3565b9e4ea004c96e158d2d332a49f466733d565bb24157a60fd2e49f41a0fd1",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_matplotlib_inline_0.1.6_py3_none_any",
        package_name = "matplotlib-inline",
        package_version = "0.1.6",
        filename = "matplotlib_inline-0.1.6-py3-none-any.whl",
        sha256 = "f1f41aab5328aa5aaea9b16d083b128102f8712542f819fe7e6a420ff581b311",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_more_itertools_10.0.0_py3_none_any",
        package_name = "more-itertools",
        package_version = "10.0.0",
        filename = "more_itertools-10.0.0-py3-none-any.whl",
        sha256 = "928d514ffd22b5b0a8fce326d57f423a55d2ff783b093bab217eda71e732330f",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_multipledispatch_1.0.0_py3_none_any",
        package_name = "multipledispatch",
        package_version = "1.0.0",
        filename = "multipledispatch-1.0.0-py3-none-any.whl",
        sha256 = "0c53cd8b077546da4e48869f49b13164bebafd0c2a5afceb6bb6a316e7fb46e4",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_numpy_1.22.3_cp39_cp39_macosx_10_14_x86_64",
        package_name = "numpy",
        package_version = "1.22.3",
        filename = "numpy-1.22.3-cp39-cp39-macosx_10_14_x86_64.whl",
        sha256 = "2c10a93606e0b4b95c9b04b77dc349b398fdfbda382d2a39ba5a822f669a0123",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_numpy_1.22.3_cp39_cp39_macosx_11_0_arm64",
        package_name = "numpy",
        package_version = "1.22.3",
        filename = "numpy-1.22.3-cp39-cp39-macosx_11_0_arm64.whl",
        sha256 = "fade0d4f4d292b6f39951b6836d7a3c7ef5b2347f3c420cd9820a1d90d794802",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_numpy_1.22.3_cp39_cp39_manylinux_2_17_aarch64.manylinux2014_aarch64",
        package_name = "numpy",
        package_version = "1.22.3",
        filename = "numpy-1.22.3-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        sha256 = "5bfb1bb598e8229c2d5d48db1860bcf4311337864ea3efdbe1171fb0c5da515d",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_numpy_1.22.3_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "numpy",
        package_version = "1.22.3",
        filename = "numpy-1.22.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "97098b95aa4e418529099c26558eeb8486e66bd1e53a6b606d684d0c3616b168",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_parso_0.8.3_py2.py3_none_any",
        package_name = "parso",
        package_version = "0.8.3",
        filename = "parso-0.8.3-py2.py3-none-any.whl",
        sha256 = "c001d4636cd3aecdaf33cbb40aebb59b094be2a74c556778ef5576c175e19e75",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_pexpect_4.8.0_py2.py3_none_any",
        package_name = "pexpect",
        package_version = "4.8.0",
        filename = "pexpect-4.8.0-py2.py3-none-any.whl",
        sha256 = "0b48a55dcb3c05f3329815901ea4fc1537514d6ba867a152b581d69ae3710937",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_pickleshare_0.7.5_py2.py3_none_any",
        package_name = "pickleshare",
        package_version = "0.7.5",
        filename = "pickleshare-0.7.5-py2.py3-none-any.whl",
        sha256 = "9649af414d74d4df115d5d718f82acb59c9d418196b7b4290ed47a12ce62df56",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_prompt_toolkit_3.0.39_py3_none_any",
        package_name = "prompt-toolkit",
        package_version = "3.0.39",
        filename = "prompt_toolkit-3.0.39-py3-none-any.whl",
        sha256 = "9dffbe1d8acf91e3de75f3b544e4842382fc06c6babe903ac9acb74dc6e08d88",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_ptyprocess_0.7.0_py2.py3_none_any",
        package_name = "ptyprocess",
        package_version = "0.7.0",
        filename = "ptyprocess-0.7.0-py2.py3-none-any.whl",
        sha256 = "4b41f3967fce3af57cc7e94b888626c18bf37a083e3651ca8feeb66d492fef35",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_pure_eval_0.2.2_py3_none_any",
        package_name = "pure-eval",
        package_version = "0.2.2",
        filename = "pure_eval-0.2.2-py3-none-any.whl",
        sha256 = "01eaab343580944bc56080ebe0a674b39ec44a945e6d09ba7db3cb8cec289350",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_pyasn1_0.5.0_py2.py3_none_any",
        package_name = "pyasn1",
        package_version = "0.5.0",
        filename = "pyasn1-0.5.0-py2.py3-none-any.whl",
        sha256 = "87a2121042a1ac9358cabcaf1d07680ff97ee6404333bacca15f76aa8ad01a57",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_pycparser_2.21_py2.py3_none_any",
        package_name = "pycparser",
        package_version = "2.21",
        filename = "pycparser-2.21-py2.py3-none-any.whl",
        sha256 = "8ee45429555515e1f6b185e78100aea234072576aa43ab53aefcae078162fca9",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_pygments_2.15.1_py3_none_any",
        package_name = "pygments",
        package_version = "2.15.1",
        filename = "Pygments-2.15.1-py3-none-any.whl",
        sha256 = "db2db3deb4b4179f399a09054b023b6a586b76499d36965813c71aa8ed7b5fd1",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_pytensor_2.12.3_cp39_cp39_macosx_10_9_x86_64",
        package_name = "pytensor",
        package_version = "2.12.3",
        filename = "pytensor-2.12.3-cp39-cp39-macosx_10_9_x86_64.whl",
        sha256 = "46c48e48c9809b760c5535d6e91e96d365ddf909367afb74c29f541a5e681042",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_pytensor_2.12.3_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "pytensor",
        package_version = "2.12.3",
        filename = "pytensor-2.12.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "cc6848fd95befc49ff30174978ff3d8c2c22ef93c25ed61d31491769c2a67126",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_python_jose_3.1.0_py2.py3_none_any",
        package_name = "python-jose",
        package_version = "3.1.0",
        filename = "python_jose-3.1.0-py2.py3-none-any.whl",
        sha256 = "1ac4caf4bfebd5a70cf5bd82702ed850db69b0b6e1d0ae7368e5f99ac01c9571",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_rsa_4.9_py3_none_any",
        package_name = "rsa",
        package_version = "4.9",
        filename = "rsa-4.9-py3-none-any.whl",
        sha256 = "90260d9058e514786967344d0ef75fa8727eed8a7d2e43ce9f4bcf1b536174f7",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_scipy_1.9.3_cp39_cp39_macosx_10_9_x86_64",
        package_name = "scipy",
        package_version = "1.9.3",
        filename = "scipy-1.9.3-cp39-cp39-macosx_10_9_x86_64.whl",
        sha256 = "d644a64e174c16cb4b2e41dfea6af722053e83d066da7343f333a54dae9bc31c",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_scipy_1.9.3_cp39_cp39_macosx_12_0_arm64",
        package_name = "scipy",
        package_version = "1.9.3",
        filename = "scipy-1.9.3-cp39-cp39-macosx_12_0_arm64.whl",
        sha256 = "da8245491d73ed0a994ed9c2e380fd058ce2fa8a18da204681f2fe1f57f98f95",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_scipy_1.9.3_cp39_cp39_manylinux_2_17_aarch64.manylinux2014_aarch64",
        package_name = "scipy",
        package_version = "1.9.3",
        filename = "scipy-1.9.3-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        sha256 = "4db5b30849606a95dcf519763dd3ab6fe9bd91df49eba517359e450a7d80ce2e",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_scipy_1.9.3_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "scipy",
        package_version = "1.9.3",
        filename = "scipy-1.9.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "c68db6b290cbd4049012990d7fe71a2abd9ffbe82c0056ebe0f01df8be5436b0",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_secretstorage_3.3.3_py3_none_any",
        package_name = "secretstorage",
        package_version = "3.3.3",
        filename = "SecretStorage-3.3.3-py3-none-any.whl",
        sha256 = "f356e6628222568e3af06f2eba8df495efa13b3b63081dafd4f7d9a7b7bc9f99",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_setuptools_60.0.5_py3_none_any",
        package_name = "setuptools",
        package_version = "60.0.5",
        filename = "setuptools-60.0.5-py3-none-any.whl",
        sha256 = "8d1f26f7cc0c81b7b372b0d133bb8b1b0abbb36f2083cb4a474a8b64cede98a7",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_six_1.16.0_py2.py3_none_any",
        package_name = "six",
        package_version = "1.16.0",
        filename = "six-1.16.0-py2.py3-none-any.whl",
        sha256 = "8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_sqlalchemy_2.0.19_cp39_cp39_macosx_10_9_x86_64",
        package_name = "sqlalchemy",
        package_version = "2.0.19",
        filename = "SQLAlchemy-2.0.19-cp39-cp39-macosx_10_9_x86_64.whl",
        sha256 = "a752b7a9aceb0ba173955d4f780c64ee15a1a991f1c52d307d6215c6c73b3a4c",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_sqlalchemy_2.0.19_cp39_cp39_macosx_11_0_arm64",
        package_name = "sqlalchemy",
        package_version = "2.0.19",
        filename = "SQLAlchemy-2.0.19-cp39-cp39-macosx_11_0_arm64.whl",
        sha256 = "7351c05db355da112e056a7b731253cbeffab9dfdb3be1e895368513c7d70106",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_sqlalchemy_2.0.19_cp39_cp39_manylinux_2_17_aarch64.manylinux2014_aarch64",
        package_name = "sqlalchemy",
        package_version = "2.0.19",
        filename = "SQLAlchemy-2.0.19-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        sha256 = "fa51ce4aea583b0c6b426f4b0563d3535c1c75986c4373a0987d84d22376585b",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_sqlalchemy_2.0.19_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "sqlalchemy",
        package_version = "2.0.19",
        filename = "SQLAlchemy-2.0.19-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "ae7473a67cd82a41decfea58c0eac581209a0aa30f8bc9190926fbf628bb17f7",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_sqlalchemy_utils_0.38.2_py3_none_any",
        package_name = "sqlalchemy-utils",
        package_version = "0.38.2",
        filename = "SQLAlchemy_Utils-0.38.2-py3-none-any.whl",
        sha256 = "622235b1598f97300e4d08820ab024f5219c9a6309937a8b908093f487b4ba54",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_stack_data_0.6.2_py3_none_any",
        package_name = "stack-data",
        package_version = "0.6.2",
        filename = "stack_data-0.6.2-py3-none-any.whl",
        sha256 = "cbb2a53eb64e5785878201a97ed7c7b94883f48b87bfb0bbe8b623c74679e4a8",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_toolz_0.12.0_py3_none_any",
        package_name = "toolz",
        package_version = "0.12.0",
        filename = "toolz-0.12.0-py3-none-any.whl",
        sha256 = "2059bd4148deb1884bb0eb770a3cde70e7f954cfbbdc2285f1f2de01fd21eb6f",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_traitlets_5.9.0_py3_none_any",
        package_name = "traitlets",
        package_version = "5.9.0",
        filename = "traitlets-5.9.0-py3-none-any.whl",
        sha256 = "9e6ec080259b9a5940c797d58b613b5e31441c2257b87c2e795c5228ae80d2d8",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_tree_sitter_0.20.0_cp39_cp39_macosx_12_0_arm64",
        package_name = "tree-sitter",
        package_version = "0.20.0",
        filename = "tree_sitter-0.20.0-cp39-cp39-macosx_12_0_arm64.whl",
        sha256 = "51a609a7c1bd9d9e75d92ee128c12c7852ae70a482900fbbccf3d13a79e0378c",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_typing_extensions_4.7.1_py3_none_any",
        package_name = "typing-extensions",
        package_version = "4.7.1",
        filename = "typing_extensions-4.7.1-py3-none-any.whl",
        sha256 = "440d5dd3af93b060174bf433bccd69b0babc3b15b1a8dca43789fd7f61514b36",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_wcwidth_0.2.6_py2.py3_none_any",
        package_name = "wcwidth",
        package_version = "0.2.6",
        filename = "wcwidth-0.2.6-py2.py3-none-any.whl",
        sha256 = "795b138f6875577cd91bba52baf9e445cd5118fd32723b460e30a0af30ea230e",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_wheel_0.37.0_py2.py3_none_any",
        package_name = "wheel",
        package_version = "0.37.0",
        filename = "wheel-0.37.0-py2.py3-none-any.whl",
        sha256 = "21014b2bd93c6d0034b6ba5d35e4eb284340e09d63c59aef6fc14b0f346146fd",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "example_lock_wheel_zipp_3.16.2_py3_none_any",
        package_name = "zipp",
        package_version = "3.16.2",
        filename = "zipp-3.16.2-py3-none-any.whl",
        sha256 = "679e51dd4403591b2d6838a48de3d283f3d188412a9782faadf845f298736ba0",
        index = "https://pypi.org",
    )

