workspace(
    name = "jvolkman_rules_pycross_example",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "8c8fe44ef0a9afc256d1e75ad5f448bb59b81aba149b8958f02f7b3a98f5d9b4",
    strip_prefix = "rules_python-0.13.0",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.13.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python3_9",
    # Available versions are listed in @rules_python//python:versions.bzl.
    # We recommend using the same version your team is already standardized on.
    python_version = "3.9",
)

load("@python3_9//:defs.bzl", "interpreter")

local_repository(
    name = "jvolkman_rules_pycross",
    path = "../..",
)

load("@jvolkman_rules_pycross//pycross:repositories.bzl", "rules_pycross_dependencies")

rules_pycross_dependencies(python_interpreter_target = interpreter)

load("@jvolkman_rules_pycross//pycross:defs.bzl", "pycross_lock_repo")

pycross_lock_repo(
    name = "example_lock_repo",
    lock_file = "//:example_lock.bzl",
)

load("@example_lock_repo//:requirements.bzl", "install_deps")

install_deps()

# Setup a CC toolchain using bazel-zig-cc
# https://git.sr.ht/~motiejus/bazel-zig-cc
BAZEL_ZIG_CC_VERSION = "v1.0.0"

http_archive(
    name = "bazel-zig-cc",
    sha256 = "1f4a1d1e0f6b3e5aa6e1c225fcb23c032f8849441de97b9a38d6ea37362d28e2",
    strip_prefix = "bazel-zig-cc-{}".format(BAZEL_ZIG_CC_VERSION),
    urls = ["https://git.sr.ht/~motiejus/bazel-zig-cc/archive/{}.tar.gz".format(BAZEL_ZIG_CC_VERSION)],
)

load(
    "@bazel-zig-cc//toolchain:defs.bzl",
    "URL_FORMAT_JAKSTYS",
    "URL_FORMAT_NIGHTLY",
    "URL_FORMAT_RELEASE",
    zig_toolchains = "toolchains",
)

zig_version = "0.10.1"

zig_host_platform_sha256 = {
    "linux-aarch64": "db0761664f5f22aa5bbd7442a1617dd696c076d5717ddefcc9d8b95278f71f5d",
    "linux-x86_64": "6699f0e7293081b42428f32c9d9c983854094bd15fee5489f12c4cf4518cc380",
    "macos-aarch64": "b9b00477ec5fa1f1b89f35a7d2a58688e019910ab80a65eac2a7417162737656",
    "macos-x86_64": "02483550b89d2a3070c2ed003357fd6e6a3059707b8ee3fbc0c67f83ca898437",
}

zig_toolchains(
    host_platform_sha256 = zig_host_platform_sha256,
    url_formats = [
        URL_FORMAT_RELEASE,
        URL_FORMAT_NIGHTLY,
        URL_FORMAT_JAKSTYS,
    ],
    version = zig_version,
)

register_toolchains(
    "@zig_sdk//toolchain:linux_amd64_gnu.2.19",
    "@zig_sdk//toolchain:linux_arm64_gnu.2.28",
    "@zig_sdk//toolchain:darwin_amd64",
    "@zig_sdk//toolchain:darwin_arm64",
)

register_toolchains(
    "//:pycross_darwin_linux_tc",
    "//:pycross_darwin_darwin_tc",
    "//:pycross_linux_linux_tc",
    "//:pycross_linux_darwin_tc",
)
