"""Repository rule to generate pycross dependency TOML lock file."""

load("@toml.bzl//:toml.bzl", "toml")
load(":lock_resolver.bzl", "resolve")
load(":uv_lock_model.bzl", "repo_create_uv_model")

def _pycross_deps_toml_repo_impl(rctx):
    project_file = rctx.attr.project_file
    lock_file = rctx.attr.lock_file

    if hasattr(rctx, "watch"):
        rctx.watch(project_file)
        rctx.watch(lock_file)

    # 1. Run uv translator
    # We want all optional groups to match the old genrule
    lock_model = struct(
        default_group = True,
        optional_groups = [],
        all_optional_groups = True,
        development_groups = [],
        all_development_groups = False,
        require_static_urls = False,
    )

    rctx.report_progress("Translating uv.lock")
    repo_create_uv_model(rctx, project_file, lock_file, lock_model, "raw_lock.json")

    # 2. Read raw_lock.json
    raw_lock_data = json.decode(rctx.read("raw_lock.json"))

    # 3. Run resolver in Starlark
    rctx.report_progress("Resolving lock")
    resolved_lock = resolve(
        lock_model_data = raw_lock_data,
        always_include_sdist = False,
        disallow_builds = False,
        default_alias_single_version = False,
    )

    # 4. Format to TOML structure
    pins = {}
    for pin_name, v in resolved_lock.pins.items():
        if "" in v and len(v) == 1:
            pins[pin_name] = v[""]
        else:
            pins[pin_name] = {k: val for k, val in v.items()}

    packages = {}
    for pkg_key, pkg in resolved_lock.packages.items():
        repo_name = None
        filename = None
        sha256 = None
        url = None

        for candidate in pkg["wheel_candidates"]:
            file_ref = candidate["file_reference"]
            if file_ref.get("key"):
                file_info = resolved_lock.remote_files.get(file_ref["key"])
                if file_info:
                    filename = file_info["name"]
                    sha256 = file_info["sha256"]
                    url = file_info["urls"][0]
                    key_str = file_ref["key"]
                    repo_name = "pypi_{}".format(_sanitize_name(key_str.replace("/", "_")))
                    break

        if not repo_name and pkg["sdist_file"] and pkg["sdist_file"].get("key"):
            file_info = resolved_lock.remote_files.get(pkg["sdist_file"]["key"])
            if file_info:
                filename = file_info["name"]
                sha256 = file_info["sha256"]
                url = file_info["urls"][0]
                key_str = pkg["sdist_file"]["key"]
                repo_name = "pypi_{}".format(_sanitize_name(key_str.replace("/", "_")))

        if not repo_name:
            continue

        deps = []
        for md in pkg["marker_dependencies"]:
            dep_dict = {"key": md["key"]}
            if md.get("marker"):
                dep_dict["marker"] = md["marker"]
            deps.append(dep_dict)

        pkg_dict = {
            "name": pkg["name"],
            "version": pkg["version"],
            "repo_name": repo_name,
            "url": url,
            "sha256": sha256,
            "filename": filename,
        }
        if deps:
            pkg_dict["deps"] = sorted(deps, key = lambda x: x["key"])

        packages[pkg_key] = pkg_dict

    sorted_pins = {k: pins[k] for k in sorted(pins.keys())}
    sorted_packages = {k: packages[k] for k in sorted(packages.keys())}

    sorted_lock_dict = {
        "pins": sorted_pins,
        "packages": sorted_packages,
    }

    toml_content = "# Generated by toml_lock_generator.py (Starlark).\n# Do not edit manually.\n\n"
    toml_content += toml.encode(sorted_lock_dict)

    rctx.file("pycross_deps.toml", toml_content)
    rctx.file("BUILD.bazel", 'exports_files(["pycross_deps.toml"])')

def _sanitize_name(val):
    return val.lower().replace("-", "_").replace(".", "_").replace("+", "_").replace("@", "_").replace("!", "_")

pycross_deps_toml_repo = repository_rule(
    implementation = _pycross_deps_toml_repo_impl,
    attrs = {
        "project_file": attr.label(mandatory = True),
        "lock_file": attr.label(mandatory = True),
        "_tools": attr.label_list(default = [
            Label("//pycross/private/tools:uv_translator.py"),
        ]),
    },
)
