"""A simple workspace repo that stores a list of resolved lock files and workspace memberships."""

_root_build = """\
package(default_visibility = ["//visibility:public"])

exports_files([
    "locks.bzl",
    "workspaces.bzl",
])
"""

def _lock_workspace_repo_impl(rctx):
    bzl_lines = ["locks = {"]
    for repo_name in sorted(rctx.attr.repo_files):
        repo_file = rctx.attr.repo_files[repo_name]
        bzl_lines.append('    "{}": Label("{}"),'.format(repo_name, repo_file))
    bzl_lines.append("}")

    workspace_lines = ["workspace_memberships = {"]
    for repo_name in sorted(rctx.attr.workspace_memberships):
        workspace_name = rctx.attr.workspace_memberships[repo_name]
        workspace_lines.append('    "{}": "{}",'.format(repo_name, workspace_name))
    workspace_lines.append("}")

    workspace_lines.append("workspace_build_repos = {")
    for workspace_name in sorted(rctx.attr.workspace_build_repos):
        build_repo = rctx.attr.workspace_build_repos[workspace_name]
        workspace_lines.append('    "{}": "{}",'.format(workspace_name, build_repo))
    workspace_lines.append("}")

    workspace_lines.append("root_repos = [")
    for repo_name in sorted(rctx.attr.root_repos):
        workspace_lines.append('    "{}",'.format(repo_name))
    workspace_lines.append("]")

    # Flags and constraint_values are JSON-encoded lists passed through string_dict attrs.
    # constraint_values are stored as strings (not labels) because repository rules cannot
    # accept label attrs across repo boundaries; labels are resolved to strings at lock_import
    # time via str(label).
    workspace_lines.append("repo_flags = {")
    for repo_name in sorted(rctx.attr.repo_flags):
        flags_json = rctx.attr.repo_flags[repo_name]
        workspace_lines.append('    "{}": {},'.format(repo_name, flags_json))
    workspace_lines.append("}")

    workspace_lines.append("repo_constraint_values = {")
    for repo_name in sorted(rctx.attr.repo_constraint_values):
        constraints_json = rctx.attr.repo_constraint_values[repo_name]
        workspace_lines.append('    "{}": {},'.format(repo_name, constraints_json))
    workspace_lines.append("}")

    workspace_lines.append("repo_platforms = {")
    for repo_name in sorted(rctx.attr.repo_platforms):
        platform = rctx.attr.repo_platforms[repo_name]
        workspace_lines.append('    "{}": "{}",'.format(repo_name, platform))
    workspace_lines.append("}")

    rctx.file("locks.bzl", "\n".join(bzl_lines) + "\n")
    rctx.file("workspaces.bzl", "\n".join(workspace_lines) + "\n")
    rctx.file("BUILD.bazel", _root_build)

lock_workspace_repo = repository_rule(
    implementation = _lock_workspace_repo_impl,
    attrs = {
        "repo_files": attr.string_dict(),
        "workspace_memberships": attr.string_dict(
            doc = "Maps repo_name to workspace_name for repos that share a workspace.",
            default = {},
        ),
        "workspace_build_repos": attr.string_dict(
            doc = "Maps workspace_name to build_repo for workspaces that use a different repo for sdist build dependencies.",
            default = {},
        ),
        "root_repos": attr.string_list(
            doc = "List of repos generated by the root module.",
            default = [],
        ),
        "repo_flags": attr.string_dict(
            doc = "Maps repo_name to JSON-encoded list of flags.",
            default = {},
        ),
        "repo_constraint_values": attr.string_dict(
            doc = "Maps repo_name to JSON-encoded list of constraint values.",
            default = {},
        ),
        "repo_platforms": attr.string_dict(
            doc = "Maps repo_name to platform label.",
            default = {},
        ),
    },
)
