# This file is generated by rules_pycross.
# It is not intended for manual editing.
"""Pycross-generated dependency targets."""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("//pycross:defs.bzl", "pycross_wheel_library")

PINS = {
    "dacite": "dacite@1.9.2",
    "installer": "installer@1.0.0",
    "packaging": "packaging@26.2",
    "pip": "pip@26.1.1",
    "poetry-core": "poetry-core@2.4.0",
    "tomli": "tomli@2.4.1",
}

FILES = {
    "dacite-1.9.2-py3-none-any.whl": Label("@rules_pycross_internal_deps_wheel_dacite_1.9.2_py3_none_any//file:dacite-1.9.2-py3-none-any.whl"),
    "installer-1.0.0-py3-none-any.whl": Label("@rules_pycross_internal_deps_wheel_installer_1.0.0_py3_none_any//file:installer-1.0.0-py3-none-any.whl"),
    "packaging-26.2-py3-none-any.whl": Label("@rules_pycross_internal_deps_wheel_packaging_26.2_py3_none_any//file:packaging-26.2-py3-none-any.whl"),
    "pip-26.1.1-py3-none-any.whl": Label("@rules_pycross_internal_deps_wheel_pip_26.1.1_py3_none_any//file:pip-26.1.1-py3-none-any.whl"),
    "poetry_core-2.4.0-py3-none-any.whl": Label("@rules_pycross_internal_deps_wheel_poetry_core_2.4.0_py3_none_any//file:poetry_core-2.4.0-py3-none-any.whl"),
    "tomli-2.4.1-py3-none-any.whl": Label("@rules_pycross_internal_deps_wheel_tomli_2.4.1_py3_none_any//file:tomli-2.4.1-py3-none-any.whl"),
}

# buildifier: disable=unnamed-macro
def targets():
    """Generated package targets."""

    for pin_name, pin_target in PINS.items():
        native.alias(
            name = pin_name,
            actual = ":" + pin_target,
        )

    native.config_setting(
        name = "_env_rules_pycross_deps_target_env",
    )

    # buildifier: disable=unused-variable
    _target = select({
        ":_env_rules_pycross_deps_target_env": "//pycross/private:rules_pycross_deps_target_env",
    })

    native.alias(
        name = "_wheel_dacite@1.9.2",
        actual = "@rules_pycross_internal_deps_wheel_dacite_1.9.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "dacite@1.9.2",
        wheel = ":_wheel_dacite@1.9.2",
    )

    native.alias(
        name = "_wheel_installer@1.0.0",
        actual = "@rules_pycross_internal_deps_wheel_installer_1.0.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "installer@1.0.0",
        wheel = ":_wheel_installer@1.0.0",
    )

    native.alias(
        name = "_wheel_packaging@26.2",
        actual = "@rules_pycross_internal_deps_wheel_packaging_26.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "packaging@26.2",
        wheel = ":_wheel_packaging@26.2",
    )

    native.alias(
        name = "_wheel_pip@26.1.1",
        actual = "@rules_pycross_internal_deps_wheel_pip_26.1.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pip@26.1.1",
        wheel = ":_wheel_pip@26.1.1",
    )

    native.alias(
        name = "_wheel_poetry-core@2.4.0",
        actual = "@rules_pycross_internal_deps_wheel_poetry_core_2.4.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "poetry-core@2.4.0",
        wheel = ":_wheel_poetry-core@2.4.0",
    )

    native.alias(
        name = "_wheel_tomli@2.4.1",
        actual = "@rules_pycross_internal_deps_wheel_tomli_2.4.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "tomli@2.4.1",
        wheel = ":_wheel_tomli@2.4.1",
    )

# buildifier: disable=unnamed-macro
def repositories():
    """Generated package repositories."""

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_dacite_1.9.2_py3_none_any",
        urls = [
            "https://us-python.pkg.dev/artifact-foundry-prod/ah-3p-staging-python/dacite/dacite-1.9.2-py3-none-any.whl",
        ],
        sha256 = "053f7c3f5128ca2e9aceb66892b1a3c8936d02c686e707bee96e19deef4bc4a0",
        downloaded_file_path = "dacite-1.9.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_installer_1.0.0_py3_none_any",
        urls = [
            "https://us-python.pkg.dev/artifact-foundry-prod/ah-3p-staging-python/installer/installer-1.0.0-py3-none-any.whl",
        ],
        sha256 = "7b46327ded20d8544bfe2d8561618bbcd12d88e7e3645333af1ed141d8bc1bfe",
        downloaded_file_path = "installer-1.0.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_packaging_26.2_py3_none_any",
        urls = [
            "https://us-python.pkg.dev/artifact-foundry-prod/ah-3p-staging-python/packaging/packaging-26.2-py3-none-any.whl",
        ],
        sha256 = "5fc45236b9446107ff2415ce77c807cee2862cb6fac22b8a73826d0693b0980e",
        downloaded_file_path = "packaging-26.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_pip_26.1.1_py3_none_any",
        urls = [
            "https://us-python.pkg.dev/artifact-foundry-prod/ah-3p-staging-python/pip/pip-26.1.1-py3-none-any.whl",
        ],
        sha256 = "99cb1c2899893b075ff56e4ed0af55669a955b49ad7fb8d8603ecdaf4ed653fb",
        downloaded_file_path = "pip-26.1.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_poetry_core_2.4.0_py3_none_any",
        urls = [
            "https://us-python.pkg.dev/artifact-foundry-prod/ah-3p-staging-python/poetry-core/poetry_core-2.4.0-py3-none-any.whl",
        ],
        sha256 = "4305848477da00272bebd3f615bbec87f64bd117cdb858ab660b626a06a9d96c",
        downloaded_file_path = "poetry_core-2.4.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_tomli_2.4.1_py3_none_any",
        urls = [
            "https://us-python.pkg.dev/artifact-foundry-prod/ah-3p-staging-python/tomli/tomli-2.4.1-py3-none-any.whl",
        ],
        sha256 = "0d85819802132122da43cb86656f8d1f8c6587d54ae7dcaf30e90533028b49fe",
        downloaded_file_path = "tomli-2.4.1-py3-none-any.whl",
    )
