# This file is generated by rules_pycross.
# It is not intended for manual editing.
"""Pycross-generated dependency targets."""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("//pycross:defs.bzl", "pycross_wheel_library")

PINS = {
    "build": "build@1.0.3",
    "dacite": "dacite@1.6.0",
    "installer": "installer@0.7.0",
    "packaging": "packaging@23.2",
    "pip": "pip@23.3.1",
    "poetry-core": "poetry-core@1.8.1",
    "repairwheel": "repairwheel@0.3.0",
    "tomli": "tomli@2.0.1",
}

# buildifier: disable=unnamed-macro
def targets():
    """Generated package targets."""

    for pin_name, pin_target in PINS.items():
        native.alias(
            name = pin_name,
            actual = ":" + pin_target,
        )

    native.config_setting(
        name = "_env_rules_pycross_deps_target_env",
    )

    # buildifier: disable=unused-variable
    _target = select({
        ":_env_rules_pycross_deps_target_env": "//pycross/private:rules_pycross_deps_target_env",
    })

    native.alias(
        name = "_wheel_altgraph@0.17.4",
        actual = "@rules_pycross_internal_deps_wheel_altgraph_0.17.4_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "altgraph@0.17.4",
        wheel = ":_wheel_altgraph@0.17.4",
    )

    _build_1_0_3_deps = [
        ":importlib-metadata@7.1.0",
        ":packaging@23.2",
        ":pyproject-hooks@1.1.0",
        ":tomli@2.0.1",
    ]

    native.alias(
        name = "_wheel_build@1.0.3",
        actual = "@rules_pycross_internal_deps_wheel_build_1.0.3_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "build@1.0.3",
        deps = _build_1_0_3_deps,
        wheel = ":_wheel_build@1.0.3",
    )

    native.alias(
        name = "_wheel_dacite@1.6.0",
        actual = "@rules_pycross_internal_deps_wheel_dacite_1.6.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "dacite@1.6.0",
        wheel = ":_wheel_dacite@1.6.0",
    )

    _delvewheel_1_6_0_deps = [
        ":pefile@2023.2.7",
    ]

    native.alias(
        name = "_wheel_delvewheel@1.6.0",
        actual = "@rules_pycross_internal_deps_wheel_delvewheel_1.6.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "delvewheel@1.6.0",
        deps = _delvewheel_1_6_0_deps,
        wheel = ":_wheel_delvewheel@1.6.0",
    )

    _importlib_metadata_7_1_0_deps = [
        ":zipp@3.19.2",
    ]

    native.alias(
        name = "_wheel_importlib-metadata@7.1.0",
        actual = "@rules_pycross_internal_deps_wheel_importlib_metadata_7.1.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "importlib-metadata@7.1.0",
        deps = _importlib_metadata_7_1_0_deps,
        wheel = ":_wheel_importlib-metadata@7.1.0",
    )

    native.alias(
        name = "_wheel_installer@0.7.0",
        actual = "@rules_pycross_internal_deps_wheel_installer_0.7.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "installer@0.7.0",
        wheel = ":_wheel_installer@0.7.0",
    )

    _macholib_1_16_3_deps = [
        ":altgraph@0.17.4",
    ]

    native.alias(
        name = "_wheel_macholib@1.16.3",
        actual = "@rules_pycross_internal_deps_wheel_macholib_1.16.3_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "macholib@1.16.3",
        deps = _macholib_1_16_3_deps,
        wheel = ":_wheel_macholib@1.16.3",
    )

    native.alias(
        name = "_wheel_packaging@23.2",
        actual = "@rules_pycross_internal_deps_wheel_packaging_23.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "packaging@23.2",
        wheel = ":_wheel_packaging@23.2",
    )

    native.alias(
        name = "_wheel_pefile@2023.2.7",
        actual = "@rules_pycross_internal_deps_wheel_pefile_2023.2.7_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pefile@2023.2.7",
        wheel = ":_wheel_pefile@2023.2.7",
    )

    native.alias(
        name = "_wheel_pip@23.3.1",
        actual = "@rules_pycross_internal_deps_wheel_pip_23.3.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pip@23.3.1",
        wheel = ":_wheel_pip@23.3.1",
    )

    native.alias(
        name = "_wheel_poetry-core@1.8.1",
        actual = "@rules_pycross_internal_deps_wheel_poetry_core_1.8.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "poetry-core@1.8.1",
        wheel = ":_wheel_poetry-core@1.8.1",
    )

    native.alias(
        name = "_wheel_pyelftools@0.31",
        actual = "@rules_pycross_internal_deps_wheel_pyelftools_0.31_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pyelftools@0.31",
        wheel = ":_wheel_pyelftools@0.31",
    )

    native.alias(
        name = "_wheel_pyproject-hooks@1.1.0",
        actual = "@rules_pycross_internal_deps_wheel_pyproject_hooks_1.1.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pyproject-hooks@1.1.0",
        wheel = ":_wheel_pyproject-hooks@1.1.0",
    )

    _repairwheel_0_3_0_deps = [
        ":delvewheel@1.6.0",
        ":macholib@1.16.3",
        ":packaging@23.2",
        ":pefile@2023.2.7",
        ":pyelftools@0.31",
    ]

    native.alias(
        name = "_wheel_repairwheel@0.3.0",
        actual = "@rules_pycross_internal_deps_wheel_repairwheel_0.3.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "repairwheel@0.3.0",
        deps = _repairwheel_0_3_0_deps,
        wheel = ":_wheel_repairwheel@0.3.0",
    )

    native.alias(
        name = "_wheel_tomli@2.0.1",
        actual = "@rules_pycross_internal_deps_wheel_tomli_2.0.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "tomli@2.0.1",
        wheel = ":_wheel_tomli@2.0.1",
    )

    native.alias(
        name = "_wheel_zipp@3.19.2",
        actual = "@rules_pycross_internal_deps_wheel_zipp_3.19.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "zipp@3.19.2",
        wheel = ":_wheel_zipp@3.19.2",
    )

# buildifier: disable=unnamed-macro
def repositories():
    """Generated package repositories."""

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_altgraph_0.17.4_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/4d/3f/3bc3f1d83f6e4a7fcb834d3720544ca597590425be5ba9db032b2bf322a2/altgraph-0.17.4-py2.py3-none-any.whl",
        ],
        sha256 = "642743b4750de17e655e6711601b077bc6598dbfa3ba5fa2b2a35ce12b508dff",
        downloaded_file_path = "altgraph-0.17.4-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_build_1.0.3_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/93/dd/b464b728b866aaa62785a609e0dd8c72201d62c5f7c53e7c20f4dceb085f/build-1.0.3-py3-none-any.whl",
        ],
        sha256 = "589bf99a67df7c9cf07ec0ac0e5e2ea5d4b37ac63301c4986d1acb126aa83f8f",
        downloaded_file_path = "build-1.0.3-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_dacite_1.6.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/06/9d/11a073172d889e9e0d0ad270a1b468876c82d759af7864a8095dfc73f46d/dacite-1.6.0-py3-none-any.whl",
        ],
        sha256 = "4331535f7aabb505c732fa4c3c094313fc0a1d5ea19907bf4726a7819a68b93f",
        downloaded_file_path = "dacite-1.6.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_delvewheel_1.6.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/24/f7/35e5657954452f6c221969e67a7c69433b1f230dc076cf49e5a9186a7fd4/delvewheel-1.6.0-py3-none-any.whl",
        ],
        sha256 = "15be02e749caacafdd51c283175a041a3f467484a1a96fc2d36340ced6869bff",
        downloaded_file_path = "delvewheel-1.6.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_importlib_metadata_7.1.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/2d/0a/679461c511447ffaf176567d5c496d1de27cbe34a87df6677d7171b2fbd4/importlib_metadata-7.1.0-py3-none-any.whl",
        ],
        sha256 = "30962b96c0c223483ed6cc7280e7f0199feb01a0e40cfae4d4450fc6fab1f570",
        downloaded_file_path = "importlib_metadata-7.1.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_installer_0.7.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/e5/ca/1172b6638d52f2d6caa2dd262ec4c811ba59eee96d54a7701930726bce18/installer-0.7.0-py3-none-any.whl",
        ],
        sha256 = "05d1933f0a5ba7d8d6296bb6d5018e7c94fa473ceb10cf198a92ccea19c27b53",
        downloaded_file_path = "installer-0.7.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_macholib_1.16.3_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/d1/5d/c059c180c84f7962db0aeae7c3b9303ed1d73d76f2bfbc32bc231c8be314/macholib-1.16.3-py2.py3-none-any.whl",
        ],
        sha256 = "0e315d7583d38b8c77e815b1ecbdbf504a8258d8b3e17b61165c6feb60d18f2c",
        downloaded_file_path = "macholib-1.16.3-py2.py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_packaging_23.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl",
        ],
        sha256 = "8c491190033a9af7e1d931d0b5dacc2ef47509b34dd0de67ed209b5203fc88c7",
        downloaded_file_path = "packaging-23.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_pefile_2023.2.7_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/55/26/d0ad8b448476d0a1e8d3ea5622dc77b916db84c6aa3cb1e1c0965af948fc/pefile-2023.2.7-py3-none-any.whl",
        ],
        sha256 = "da185cd2af68c08a6cd4481f7325ed600a88f6a813bad9dea07ab3ef73d8d8d6",
        downloaded_file_path = "pefile-2023.2.7-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_pip_23.3.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl",
        ],
        sha256 = "55eb67bb6171d37447e82213be585b75fe2b12b359e993773aca4de9247a052b",
        downloaded_file_path = "pip-23.3.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_poetry_core_1.8.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/99/bc/058b8ff87871fce6615ad032d62c773272f243266b110f7b86d146cf78d8/poetry_core-1.8.1-py3-none-any.whl",
        ],
        sha256 = "194832b24f3283e01c5402eae71a6aae850ecdfe53f50a979c76bf7aa5010ffa",
        downloaded_file_path = "poetry_core-1.8.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_pyelftools_0.31_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/f8/64/711030d9fe9ccaf6ee3ab1bcf4801c6bb3d0e585af18824a50b016b4f39c/pyelftools-0.31-py3-none-any.whl",
        ],
        sha256 = "f52de7b3c7e8c64c8abc04a79a1cf37ac5fb0b8a49809827130b858944840607",
        downloaded_file_path = "pyelftools-0.31-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_pyproject_hooks_1.1.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/ae/f3/431b9d5fe7d14af7a32340792ef43b8a714e7726f1d7b69cc4e8e7a3f1d7/pyproject_hooks-1.1.0-py3-none-any.whl",
        ],
        sha256 = "7ceeefe9aec63a1064c18d939bdc3adf2d8aa1988a510afec15151578b232aa2",
        downloaded_file_path = "pyproject_hooks-1.1.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_repairwheel_0.3.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/52/ee/18c8641792d0c886d410dfd8c4b7dc54148034cad2a66a18727d30f57e3d/repairwheel-0.3.0-py3-none-any.whl",
        ],
        sha256 = "7554d16ed4c350f5416f18e170b9330746edc342bdb9c12c276c6f2855c7205f",
        downloaded_file_path = "repairwheel-0.3.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_tomli_2.0.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl",
        ],
        sha256 = "939de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc",
        downloaded_file_path = "tomli-2.0.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "rules_pycross_internal_deps_wheel_zipp_3.19.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/20/38/f5c473fe9b90c8debdd29ea68d5add0289f1936d6f923b6b9cc0b931194c/zipp-3.19.2-py3-none-any.whl",
        ],
        sha256 = "f091755f667055f2d02b32c53771a7a6c8b47e1fdbc4b72a8b9072b3eef8015c",
        downloaded_file_path = "zipp-3.19.2-py3-none-any.whl",
    )
