"""Pure Starlark implementation of the resolved_lock_renderer.

This module generates the BUILD.bazel content for the `_lock` repository.
It implements the following naming conventions for generated targets:
  - `_raw_<pkg_key>`: The underlying `pycross_wheel_library` or `pycross_wheel_build` target.
  - `<pkg_key>`: A `py_library` that wraps the raw target. If the package is part of a cycle,
    this target depends on both the raw target and the shared cycle group target to break the cycle.
  - `_cycle_<group_name>`: A `py_library` aggregating all packages in a cycle SCC.
  - `<pkg_name>[_all_]@<version>`: A synthetic `py_library` that aggregates the base package and
    all of its parsed extras into a single target. Repos using `squash_extras` point their
    aliases to this `[_all_]` target to squash the graph at the alias layer.
"""

def _ind(text, tabs = 1):
    if not text:
        return ""
    return ("    " * tabs) + text

def _sanitize_name(name):
    return name.lower().replace("-", "_").replace("@", "_").replace("+", "_").replace(".", "_").replace("[", "_").replace("]", "_")

def _is_in_same_cycle(dep_key, pkg, packages):
    cycle_group = pkg.get("cycle_group")
    if not cycle_group:
        return False
    dep_pkg = packages.get(dep_key)
    if not dep_pkg:
        return False
    return dep_pkg.get("cycle_group") == cycle_group

def _wheel_target(file_ref, sdist_file, pkg_key, pkg, repo_map, sdist_map, rctx_name):
    if file_ref.get("label"):
        return file_ref["label"]
    key = file_ref.get("key")
    if sdist_file and key == sdist_file.get("key"):
        if pkg.get("build_target"):
            return pkg["build_target"]
        if sdist_map and key in sdist_map:
            return sdist_map[key]
        repo_name = "{}_sdist_{}".format(rctx_name, _sanitize_name(pkg_key))
        return "@@{}//:wheel".format(repo_name)

    return repo_map.get(key)

def render_lock_bzl(lock, repo_map, sdist_map = None, rctx_name = ""):
    """Renders a lock.bzl file from a resolved lock structure.

    Args:
        lock: The parsed lock.json dict.
        repo_map: A dict mapping file keys to repo labels.
        sdist_map: A dict mapping sdist package keys to their wheel target labels.
        rctx_name: The name of the package repository.

    Returns:
        A string containing the rendered lock.bzl file.
    """
    lines = [
        "# This file is generated by rules_pycross.",
        "# It is not intended for manual editing.",
        '"""Pycross-generated dependency targets."""',
        "",
        'load("@rules_pycross//pycross:defs.bzl", "pycross_dist_info", "pycross_wheel_library")',
        'load("@rules_python//python:defs.bzl", "py_library")',
        "",
        "# buildifier: disable=unnamed-macro",
        "def targets():",
        _ind('"""Generated package targets."""'),
        "",
    ]

    environments = lock.get("environments", {})
    packages = lock.get("packages", {})
    cycle_groups = lock.get("cycle_groups", {})

    # 1. Environment config_settings
    for env_name, env_ref in sorted(environments.items()):
        if env_ref.get("config_setting_label"):
            lines.extend([
                _ind("native.alias("),
                _ind('name = "{}",'.format(env_name), 2),
                _ind('actual = "{}",'.format(env_ref["config_setting_label"]), 2),
                _ind(")"),
                "",
            ])
        else:
            config_setting = env_ref.get("config_setting", {})
            lines.extend([
                _ind("native.config_setting("),
                _ind('name = "{}",'.format(env_name), 2),
            ])
            if config_setting.get("constraint_values"):
                lines.append(_ind("constraint_values = [", 2))
                for cv in config_setting["constraint_values"]:
                    lines.append(_ind('"{}",'.format(cv), 3))
                lines.append(_ind("],", 2))
            if config_setting.get("flag_values"):
                lines.append(_ind("flag_values = {", 2))
                for f, v in sorted(config_setting["flag_values"].items()):
                    lines.append(_ind('"{}": "{}",'.format(f, v), 3))
                lines.append(_ind("},", 2))
            lines.extend([
                _ind(")"),
                "",
            ])

    # 2. Cycle groups
    for group_name, scc in sorted(cycle_groups.items()):
        lines.append(_ind("py_library("))
        lines.append(_ind('name = "_cycle_{}",'.format(group_name), 2))

        common_members = []
        env_members = {}
        for pkg_key in sorted(scc):
            pkg = packages.get(pkg_key, {})
            pkg_envs = pkg.get("environment_files", {}).keys()
            if not pkg_envs or all([env in pkg_envs for env in environments]):
                common_members.append(pkg_key)
            else:
                for env in pkg_envs:
                    env_members.setdefault(env, []).append(pkg_key)

        if not env_members:
            lines.append(_ind("deps = [", 2))
            for pkg_key in common_members:
                lines.append(_ind('":_raw_{}",'.format(pkg_key), 3))
            lines.append(_ind("],", 2))
        else:
            lines.append(_ind("deps = [", 2))
            for pkg_key in common_members:
                lines.append(_ind('":_raw_{}",'.format(pkg_key), 3))
            lines.append(_ind("] + select({", 2))
            for env_name in sorted(environments.keys()):
                deps = env_members.get(env_name, [])
                if deps:
                    lines.append(_ind('":{env}": ['.format(env = env_name), 3))
                    for pkg_key in sorted(deps):
                        lines.append(_ind('":_raw_{}",'.format(pkg_key), 4))
                    lines.append(_ind("],", 3))
            lines.append(_ind('"//conditions:default": [],', 3))
            lines.append(_ind("}),", 2))

        lines.append(_ind(")"))
        lines.append("")

    # 3. Packages
    for pkg_key, pkg in sorted(packages.items()):
        pkg_key_san = _sanitize_name(pkg_key)
        package_name = pkg_key.split("@", 1)[0]
        package_version = pkg_key.split("@", 1)[1]

        has_runtime_deps = bool(pkg.get("common_dependencies") or pkg.get("environment_dependencies"))

        sdist_file = pkg.get("sdist_file")
        sdist_label = None
        if sdist_file:
            if sdist_file.get("label"):
                sdist_label = sdist_file["label"]
            elif sdist_file.get("key"):
                sdist_label = repo_map.get(sdist_file["key"])

        # Runtime deps
        if has_runtime_deps:
            lines.append(_ind("_{}_deps = [".format(pkg_key_san)))
            for dep_key in sorted(pkg.get("common_dependencies", [])):
                if _is_in_same_cycle(dep_key, pkg, packages):
                    continue
                lines.append(_ind('":{dep}",'.format(dep = dep_key), 2))
            lines.append(_ind("]"))

            if pkg.get("environment_dependencies"):
                lines[-1] = lines[-1] + " + select({"
                for env_name, deps in sorted(pkg.get("environment_dependencies").items()):
                    lines.append(_ind('":{env}": ['.format(env = env_name), 2))
                    for dep_key in sorted(deps):
                        if _is_in_same_cycle(dep_key, pkg, packages):
                            continue
                        lines.append(_ind('":{dep}",'.format(dep = dep_key), 3))
                    lines.append(_ind("],", 2))
                lines.append(_ind('"//conditions:default": [],', 2))
                lines.append(_ind("})", 1))
            lines.append("")

        if not pkg.get("environment_files") and "[" in pkg_key:
            # Extra packages just wrap their dependencies
            lines.extend([
                _ind("py_library("),
                _ind('name = "{}",'.format(pkg_key), 2),
                _ind("deps = _{}_deps,".format(pkg_key_san) if has_runtime_deps else "deps = [],", 2),
                _ind(")"),
                "",
            ])
            continue

        # Sdist alias
        if sdist_label:
            lines.extend([
                _ind("native.alias("),
                _ind('name = "_sdist_{}",'.format(pkg_key), 2),
                _ind('actual = "{}",'.format(sdist_label), 2),
                _ind(")"),
                "",
            ])

        # Wheel alias (with select for multi-environment)
        lines.extend([
            _ind("native.alias("),
            _ind('name = "_wheel_{}",'.format(pkg_key), 2),
        ])
        lines.append(_ind("actual = select({", 2))
        for env_name, env_ref in sorted(pkg.get("environment_files", {}).items()):
            lines.append(_ind('":{env}": "{target}",'.format(
                env = env_name,
                target = _wheel_target(env_ref, sdist_file, pkg_key, pkg, repo_map, sdist_map, rctx_name),
            ), 3))
        lines.append(_ind('"//conditions:default": "@rules_pycross//pycross/private:no_match_error",', 3))
        lines.append(_ind("}),", 2))
        lines.extend([
            _ind(")"),
            "",
        ])

        # Library
        lib_name = pkg_key
        if pkg.get("cycle_group"):
            lib_name = "_raw_{}".format(pkg_key)

        lines.extend([
            _ind("pycross_wheel_library("),
            _ind('name = "{}",'.format(lib_name), 2),
            _ind('package_name = "{}",'.format(package_name), 2),
            _ind('package_version = "{}",'.format(package_version), 2),
            _ind('wheel = ":_wheel_{}",'.format(pkg_key), 2),
        ])

        if pkg.get("site_paths"):
            lines.append(_ind("site_paths = [", 2))
            for tlp in pkg["site_paths"]:
                lines.append(_ind('"{}",'.format(tlp), 3))
            lines.append(_ind("],", 2))

        if pkg.get("bin_paths"):
            lines.append(_ind("bin_paths = [", 2))
            for bp in pkg["bin_paths"]:
                lines.append(_ind('"{}",'.format(bp), 3))
            lines.append(_ind("],", 2))

        if pkg.get("data_paths"):
            lines.append(_ind("data_paths = [", 2))
            for dp in pkg["data_paths"]:
                lines.append(_ind('"{}",'.format(dp), 3))
            lines.append(_ind("],", 2))

        if pkg.get("include_paths"):
            lines.append(_ind("include_paths = [", 2))
            for ip in pkg["include_paths"]:
                lines.append(_ind('"{}",'.format(ip), 3))
            lines.append(_ind("],", 2))

        if has_runtime_deps:
            lines.append(_ind("deps = _{}_deps,".format(pkg_key_san), 2))

        if pkg.get("install_exclude_globs"):
            lines.append(_ind("install_exclude_globs = [", 2))
            for glob in pkg["install_exclude_globs"]:
                lines.append(_ind('"{}",'.format(glob), 3))
            lines.append(_ind("],", 2))

        if pkg.get("post_install_patches"):
            lines.append(_ind("post_install_patches = [", 2))
            for patch in pkg["post_install_patches"]:
                lines.append(_ind('"{}",'.format(patch), 3))
            lines.append(_ind("],", 2))

        lines.extend([
            _ind(")"),
            "",
        ])

        # Cycle group wrapper
        if pkg.get("cycle_group"):
            lines.append(_ind("py_library("))
            lines.append(_ind('name = "{}",'.format(pkg_key), 2))
            lines.append(_ind('deps = [":_raw_{}", ":_cycle_{}"],'.format(pkg_key, pkg["cycle_group"]), 2))
            lines.append(_ind(")"))
            lines.append("")

        # dist_info
        lines.extend([
            _ind("pycross_dist_info("),
            _ind('name = "_dist_info_{}",'.format(pkg_key), 2),
            _ind('pkg = ":{lib}",'.format(lib = pkg_key), 2),
            _ind(")"),
            "",
        ])

    base_packages_with_extras = {}
    for pkg_key in packages.keys():
        if "[" in pkg_key:
            base_name, extra_and_version = pkg_key.split("[", 1)
            _, version = extra_and_version.split("]@", 1)
            base_pkg_key = "{}@{}".format(base_name, version)
            if base_pkg_key not in base_packages_with_extras:
                base_packages_with_extras[base_pkg_key] = []
            base_packages_with_extras[base_pkg_key].append(pkg_key)

    for base_pkg_key, extra_keys in sorted(base_packages_with_extras.items()):
        base_name, version = base_pkg_key.split("@", 1)
        lines.extend([
            _ind("py_library("),
            _ind('name = "{}[_all_]@{}",'.format(base_name, version), 2),
            _ind("deps = [", 2),
            _ind('":{}\",'.format(base_pkg_key), 3),
        ])
        for extra_key in sorted(extra_keys):
            lines.append(_ind('":{}\",'.format(extra_key), 3))
        lines.extend([
            _ind("],", 2),
            _ind(")"),
            "",
        ])

    return "\n".join(lines) + "\n"
