"""Pure Starlark implementation of the resolved_lock_renderer."""

def _ind(text, tabs = 1):
    if not text:
        return ""
    return ("    " * tabs) + text

def _sanitize_name(name):
    return name.lower().replace("-", "_").replace("@", "_").replace("+", "_").replace(".", "_")

def _wheel_target(file_ref, sdist_file, pkg_key, pkg, repo_map, rctx_name):
    if file_ref.get("label"):
        return file_ref["label"]
    key = file_ref.get("key")
    if sdist_file and key == sdist_file.get("key"):
        if pkg.get("build_target"):
            target = pkg["build_target"]
        else:
            repo_name = "{}_sdist_{}".format(rctx_name, _sanitize_name(pkg_key))
            target = "@@{}//:pkg".format(repo_name)

        parts = target.rsplit(":", 1)
        if len(parts) == 2:
            return parts[0] + ":wheel"
        else:
            return target + ":wheel"

    return repo_map.get(key)

def render_lock_bzl(lock, repo_map, rctx_name):
    """Renders the BUILD files for a lock repo.

    Args:
        lock: The parsed lock.json dict.
        repo_map: A dict mapping file keys to repo labels.
        rctx_name: The name of the package repository.

    Returns:
        A dict of string path to string file content.
    """
    environments = lock.get("environments", {})
    packages = lock.get("packages", {})

    build_files = {}

    # 1. Environments
    env_lines = []
    env_lines.append("# This file is generated by rules_pycross.")
    env_lines.append('package(default_visibility = ["//visibility:public"])')
    env_lines.append("")
    
    target_env_cases = {}
    for env_name, env_ref in sorted(environments.items()):
        env_target = env_name
        if env_ref.get("config_setting_label"):
            env_lines.append("alias(")
            env_lines.append('    name = "{}",'.format(env_target))
            env_lines.append('    actual = "{}",'.format(env_ref["config_setting_label"]))
            env_lines.append(")")
            env_lines.append("")
        else:
            config_setting = env_ref.get("config_setting", {})
            env_lines.append("config_setting(")
            env_lines.append('    name = "{}",'.format(env_target))
            if config_setting.get("constraint_values"):
                env_lines.append("    constraint_values = [")
                for cv in config_setting["constraint_values"]:
                    env_lines.append('        "{}",'.format(cv))
                env_lines.append("    ],")
            if config_setting.get("flag_values"):
                env_lines.append("    flag_values = {")
                for f, v in config_setting["flag_values"].items():
                    env_lines.append('        "{}": "{}",'.format(f, v))
                env_lines.append("    },")
            env_lines.append(")")
            env_lines.append("")

        target_env_cases['"//_env:{}"'.format(env_target)] = '"{}"'.format(env_ref["environment_label"])

    if environments:
        build_files["_env/BUILD.bazel"] = "\n".join(env_lines) + "\n"

    # 2. Packages
    for pkg_key, pkg in sorted(packages.items()):
        package_name_parts = pkg_key.split("@", 1)
        package_name = package_name_parts[0]
        package_version = package_name_parts[1]
        
        # Normalize package_name as per PEP 503
        norm_package_name = package_name.replace("_", "-").replace(".", "-").lower()
        for _i in range(len(norm_package_name)):
            if "--" in norm_package_name:
                norm_package_name = norm_package_name.replace("--", "-")
            else:
                break
        
        pkg_dir = "{}/v{}".format(norm_package_name, package_version)

        lines = []
        lines.append("# This file is generated by rules_pycross.")
        lines.append('package(default_visibility = ["//visibility:public"])')
        lines.append("")
        lines.append('load("@rules_pycross//pycross:defs.bzl", "pycross_wheel_library")')
        lines.append("")
        if pkg.get("extra_dependencies"):
            lines.append('load("@rules_python//python:defs.bzl", "py_library")')
            lines.append("")

        has_runtime_deps = bool(pkg.get("common_dependencies") or pkg.get("environment_dependencies"))

        sdist_file = pkg.get("sdist_file")
        sdist_label = None
        if sdist_file:
            if sdist_file.get("label"):
                sdist_label = sdist_file["label"]
            elif sdist_file.get("key"):
                sdist_label = repo_map.get(sdist_file["key"])

        # Runtime deps
        deps_name = "_deps"
        if has_runtime_deps:
            lines.append("{} = [".format(deps_name))
            for dep_key in sorted(pkg.get("common_dependencies", [])):
                dep_parts = dep_key.split("@", 1)
                dep_pkg = dep_parts[0]
                dep_ver = dep_parts[1]
                
                dep_norm = dep_pkg.replace("_", "-").replace(".", "-").lower()
                for _i in range(len(dep_norm)):
                    if "--" in dep_norm:
                        dep_norm = dep_norm.replace("--", "-")
                    else:
                        break
                lines.append('    "//{}/v{}:pkg",'.format(dep_norm, dep_ver))
            lines.append("]")

            if pkg.get("environment_dependencies"):
                # Workaround for string appending in Starlark: using list index updates
                lines[-1] = lines[-1] + " + select({"
                for env_name, deps in sorted(pkg.get("environment_dependencies").items()):
                    lines.append('    "//_env:{}": ['.format(env_name))
                    for dep_key in sorted(deps):
                        dep_parts = dep_key.split("@", 1)
                        dep_pkg = dep_parts[0]
                        dep_ver = dep_parts[1]
                        dep_norm = dep_pkg.replace("_", "-").replace(".", "-").lower()
                        for _i in range(len(dep_norm)):
                            if "--" in dep_norm:
                                dep_norm = dep_norm.replace("--", "-")
                            else:
                                break
                        lines.append('        "//{}/v{}:pkg",'.format(dep_norm, dep_ver))
                    lines.append("    ],")
                lines.append('    "//conditions:default": [],')
                lines.append("})")
            lines.append("")

        # Sdist alias
        if sdist_label:
            lines.append("alias(")
            lines.append('    name = "sdist",')
            lines.append('    actual = "{}",'.format(sdist_label))
            lines.append(")")
            lines.append("")

        # Wheel alias
        target_name_whl = "whl"
        target_name_pkg = "pkg"
        
        aliases_to_make = ["pkg", "whl"]
        if sdist_label:
            aliases_to_make.append("sdist")
        aliases_to_make.append(norm_package_name)
        
        for _ in range(3):
            if target_name_whl in (norm_package_name, target_name_pkg, "sdist"):
                target_name_whl += "_"
        for _ in range(3):
            if target_name_pkg in (norm_package_name, "sdist", target_name_whl):
                target_name_pkg += "_"

        lines.append("alias(")
        lines.append('    name = "{}",'.format(target_name_whl))

        distinct_file_refs = []
        for env_ref in pkg.get("environment_files", {}).values():
            if env_ref not in distinct_file_refs:
                distinct_file_refs.append(env_ref)

        if len(distinct_file_refs) == 1:
            lines.append('    actual = "{}",'.format(_wheel_target(distinct_file_refs[0], sdist_file, pkg_key, pkg, repo_map, rctx_name)))
        else:
            lines.append("    actual = select({")
            for env_name, env_ref in sorted(pkg.get("environment_files", {}).items()):
                lines.append('        "//_env:{}": "{}",'.format(env_name, _wheel_target(env_ref, sdist_file, pkg_key, pkg, repo_map, rctx_name)))
            lines.append("    }),")
        lines.append(")")
        lines.append("")

        # Library
        lines.append("pycross_wheel_library(")
        lines.append('    name = "{}",'.format(target_name_pkg))
        lines.append('    package_name = "{}",'.format(package_name))
        lines.append('    package_version = "{}",'.format(package_version))
        lines.append('    wheel = ":{}",'.format(target_name_whl))
        

        if pkg.get("top_level_packages"):
            lines.append("    top_level_packages = [")
            for tlp in pkg["top_level_packages"]:
                lines.append('        "{}",'.format(tlp))
            lines.append("    ],")

        if has_runtime_deps:
            lines.append("    deps = {},".format(deps_name))

        if pkg.get("install_exclude_globs"):
            lines.append("    install_exclude_globs = [")
            for glob in pkg["install_exclude_globs"]:
                lines.append('        "{}",'.format(glob))
            lines.append("    ],")

        if pkg.get("post_install_patches"):
            lines.append("    post_install_patches = [")
            for patch in pkg["post_install_patches"]:
                lines.append('        "{}",'.format(patch))
            lines.append("    ],")

        lines.append(")")
        lines.append("")
        
        # Extras
        for extra_name, extra_deps in sorted(pkg.get("extra_dependencies", {}).items()):
            deps_name = "_deps_{}".format(extra_name.replace("-", "_").replace(".", "_"))
            lines.append("{} = [".format(deps_name))
            lines.append('    ":{}",'.format(target_name_pkg))
            for dep_key in sorted(extra_deps.get("common_dependencies", [])):
                dep_parts = dep_key.split("@", 1)
                dep_pkg = dep_parts[0]
                dep_ver = dep_parts[1]
                dep_norm = dep_pkg.replace("_", "-").replace(".", "-").lower()
                for _i in range(len(dep_norm)):
                    if "--" in dep_norm:
                        dep_norm = dep_norm.replace("--", "-")
                    else:
                        break
                lines.append('    "//{}/v{}:pkg",'.format(dep_norm, dep_ver))
            lines.append("]")
            
            if extra_deps.get("environment_dependencies"):
                lines[-1] = lines[-1] + " + select({"
                for env_name, env_deps in sorted(extra_deps.get("environment_dependencies").items()):
                    lines.append('    "//_env:{}": ['.format(env_name))
                    for dep_key in sorted(env_deps):
                        dep_parts = dep_key.split("@", 1)
                        dep_pkg = dep_parts[0]
                        dep_ver = dep_parts[1]
                        dep_norm = dep_pkg.replace("_", "-").replace(".", "-").lower()
                        for _i in range(len(dep_norm)):
                            if "--" in dep_norm:
                                dep_norm = dep_norm.replace("--", "-")
                            else:
                                break
                        lines.append('        "//{}/v{}:pkg",'.format(dep_norm, dep_ver))
                    lines.append("    ],")
                lines.append('    "//conditions:default": [],')
                lines.append("})")
            lines.append("")
            
            lines.append("py_library(")
            lines.append('    name = "[{}]",'.format(extra_name))
            lines.append('    deps = {},'.format(deps_name))
            lines.append(")")
            lines.append("")

        # Finally, the package alias
        if norm_package_name != target_name_pkg:
            lines.append("alias(")
            lines.append('    name = "{}",'.format(norm_package_name))
            lines.append('    actual = ":{}",'.format(target_name_pkg))
            lines.append(")")
            lines.append("")

        build_files[pkg_dir + "/BUILD.bazel"] = "\n".join(lines) + "\n"

    return build_files
