"""Pure Starlark implementation of the resolved_lock_renderer."""

def _ind(text, tabs = 1):
    if not text:
        return ""
    return ("    " * tabs) + text

def _sanitize_name(name):
    return name.lower().replace("-", "_").replace("@", "_").replace("+", "_").replace(".", "_")

def render_lock_bzl(lock, repo_map, rctx_name):
    """Renders a lock.bzl file from a resolved lock structure.

    Args:
        lock: The parsed lock.json dict.
        repo_map: A dict mapping file keys to repo labels.
        rctx_name: The name of the package repository.

    Returns:
        A string containing the rendered lock.bzl file.
    """
    lines = [
        "# This file is generated by rules_pycross.",
        "# It is not intended for manual editing.",
        '"""Pycross-generated dependency targets."""',
        "",
        'load("@rules_pycross//pycross:defs.bzl", "pycross_wheel_library")',
        "",
        "# buildifier: disable=unnamed-macro",
        "def targets():",
        _ind('"""Generated package targets."""'),
        "",
    ]

    environments = lock.get("environments", {})
    packages = lock.get("packages", {})

    # Environments
    target_env_cases = {}
    for env_name, env_ref in sorted(environments.items()):
        env_target = "_env_" + env_name
        if env_ref.get("config_setting_label"):
            lines.extend([
                _ind("native.alias("),
                _ind('name = "{}",'.format(env_target), 2),
                _ind('actual = "{}",'.format(env_ref["config_setting_label"]), 2),
                _ind(")"),
                "",
            ])
        else:
            config_setting = env_ref.get("config_setting", {})
            lines.extend([
                _ind("native.config_setting("),
                _ind('name = "{}",'.format(env_target), 2),
            ])
            if config_setting.get("constraint_values"):
                lines.append(_ind("constraint_values = [", 2))
                for cv in config_setting["constraint_values"]:
                    lines.append(_ind('"{}",'.format(cv), 3))
                lines.append(_ind("],", 2))
            if config_setting.get("flag_values"):
                lines.append(_ind("flag_values = {", 2))
                for f, v in config_setting["flag_values"].items():
                    lines.append(_ind('"{}": "{}",'.format(f, v), 3))
                lines.append(_ind("},", 2))
            lines.extend([
                _ind(")"),
                "",
            ])

        target_env_cases['":{}"'.format(env_target)] = '"{}"'.format(env_ref["environment_label"])

    lines.extend([
        _ind("# buildifier: disable=unused-variable"),
        _ind("_target = select({"),
    ])
    for k, v in sorted(target_env_cases.items()):
        lines.append(_ind("{}: {},".format(k, v), 2))
    lines.extend([
        _ind("})"),
        "",
    ])

    for pkg_key, pkg in sorted(packages.items()):
        pkg_key_sanitized = _sanitize_name(pkg_key)

        has_runtime_deps = bool(pkg.get("common_dependencies") or pkg.get("environment_dependencies"))

        sdist_file = pkg.get("sdist_file")
        sdist_label = None
        if sdist_file:
            if sdist_file.get("label"):
                sdist_label = sdist_file["label"]
            elif sdist_file.get("key"):
                sdist_label = repo_map.get(sdist_file["key"])

        # Runtime deps
        deps_name = "_{}_deps".format(pkg_key_sanitized)
        if has_runtime_deps:
            lines.append(_ind("{} = [".format(deps_name)))
            for dep in sorted(pkg.get("common_dependencies", [])):
                lines.append(_ind('":{}",'.format(dep), 2))
            lines.append(_ind("]"))

            if pkg.get("environment_dependencies"):
                lines[-1] = lines[-1] + " + select({"
                for env_name, deps in sorted(pkg.get("environment_dependencies").items()):
                    lines.append(_ind('":_env_{}": ['.format(env_name), 2))
                    for dep in sorted(deps):
                        lines.append(_ind('":{}",'.format(dep), 3))
                    lines.append(_ind("],", 2))
                lines.append(_ind('"//conditions:default": [],', 2))
                lines.append(_ind("})"))
            lines.append("")

        # Sdist alias
        if sdist_label:
            lines.extend([
                _ind("native.alias("),
                _ind('name = "_sdist_{}",'.format(pkg_key), 2),
                _ind('actual = "{}",'.format(sdist_label), 2),
                _ind(")"),
                "",
            ])

        # Wheel alias
        lines.extend([
            _ind("native.alias("),
            _ind('name = "_wheel_{}",'.format(pkg_key), 2),
        ])

        distinct_file_refs = []
        for env_ref in pkg.get("environment_files", {}).values():
            if env_ref not in distinct_file_refs:
                distinct_file_refs.append(env_ref)

        def wheel_target(file_ref):
            if file_ref.get("label"):
                return file_ref["label"]
            key = file_ref.get("key")
            if sdist_file and key == sdist_file.get("key"):
                if pkg.get("build_target"):
                    target = pkg["build_target"]
                else:
                    repo_name = "{}_sdist_{}".format(rctx_name, pkg_key_sanitized)
                    target = "@@{}//:pkg".format(repo_name)

                parts = target.rsplit(":", 1)
                if len(parts) == 2:
                    return parts[0] + ":wheel"
                else:
                    return target + ":wheel"

            return repo_map.get(key)

        if len(distinct_file_refs) == 1:
            lines.append(_ind('actual = "{}",'.format(wheel_target(distinct_file_refs[0])), 2))
        else:
            lines.append(_ind("actual = select({", 2))
            for env_name, env_ref in sorted(pkg.get("environment_files", {}).items()):
                lines.append(_ind('":_env_{}": "{}",'.format(env_name, wheel_target(env_ref)), 3))
            lines.append(_ind("}),", 2))
        lines.extend([
            _ind(")"),
            "",
        ])

        # Library
        package_name, package_version = pkg_key.split("@", 1)
        lines.extend([
            _ind("pycross_wheel_library("),
            _ind('name = "{}",'.format(pkg_key), 2),
            _ind('package_name = "{}",'.format(package_name), 2),
            _ind('package_version = "{}",'.format(package_version), 2),
            _ind('wheel = ":_wheel_{}",'.format(pkg_key), 2),
        ])
        if has_runtime_deps:
            lines.append(_ind("deps = {},".format(deps_name), 2))

        if pkg.get("install_exclude_globs"):
            lines.append(_ind("install_exclude_globs = [", 2))
            for glob in pkg["install_exclude_globs"]:
                lines.append(_ind('"{}",'.format(glob), 3))
            lines.append(_ind("],", 2))

        if pkg.get("post_install_patches"):
            lines.append(_ind("post_install_patches = [", 2))
            for patch in pkg["post_install_patches"]:
                lines.append(_ind('"{}",'.format(patch), 3))
            lines.append(_ind("],", 2))

        lines.extend([
            _ind(")"),
            "",
        ])

    return "\n".join(lines) + "\n"
