module(
    name = "example_bzlmod",
    version = "0.0.0",
)

bazel_dep(name = "bazel_lib", version = "3.3.1")
bazel_dep(name = "rules_python", version = "2.0.0")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.14.2",
)
use_repo(python, "python_versions")

bazel_dep(name = "rules_pycross", version = "0.0.0")
local_path_override(
    module_name = "rules_pycross",
    path = "../..",
)

pycross = use_extension("@rules_pycross//pycross/extensions:pycross.bzl", "pycross")
pycross.configure_toolchains(
    platforms = [
        "aarch64-apple-darwin",
        "aarch64-unknown-linux-gnu",
        "x86_64-unknown-linux-gnu",
        "x86_64-unknown-linux-musl",
    ],
    python_versions = [
        "3.14.2",
    ],
)

# Import the uv lockfile and create the @uv_deps package repository.
uv = use_extension("@rules_pycross//pycross/extensions:uv.bzl", "uv")
uv.workspace(
    name = "uv_deps",
    lock_file = "//:uv.lock",
)
uv.repo(
    dependency_groups = ["default"],
    workspace = "uv_deps",
)

# Specify per-package overrides. Here we say that we want to build ipython from an sdist.
uv.package(
    name = "ipython",
    build_mode = "always",
    workspace = "uv_deps",
)

# Specify per-package overrides. Here we say that we want certain files excluded during installation.
uv.package(
    name = "amqp-mock",
    install_exclude_globs = [
        "tests/**",
    ],
    workspace = "uv_deps",
)
uv.package(
    name = "matplotlib",
    post_install_patches = [
        "//:matplotlib.patch",
    ],
    workspace = "uv_deps",
)
use_repo(uv, "uv_deps")
