# This file is generated by rules_pycross.
# It is not intended for manual editing.
"""Pycross-generated dependency targets."""

load("@aspect_rules_py//py:defs.bzl", "py_library", "py_wheel")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@jvolkman_rules_pycross//pycross:defs.bzl", "pycross_wheel_build")

PINS = {
    "grpclib": "grpclib_0.4.6",
    "h2": "h2_4.1.0",
    "hpack": "hpack_4.0.0",
    "hyperframe": "hyperframe_6.0.1",
    "multidict": "multidict_6.0.4",
    "setuptools": "setuptools_68.2.2",
    "wheel": "wheel_0.41.3",
}

# buildifier: disable=unnamed-macro
def targets():
    """Generated package targets."""

    for pin_name, pin_target in PINS.items():
        native.alias(
            name = pin_name,
            actual = ":" + pin_target,
        )

    native.config_setting(
        name = "_env_python_darwin_arm64",
        constraint_values = [
            "@platforms//os:osx",
            "@platforms//cpu:aarch64",
        ],
    )

    native.config_setting(
        name = "_env_python_darwin_x86_64",
        constraint_values = [
            "@platforms//os:osx",
            "@platforms//cpu:x86_64",
        ],
    )

    native.config_setting(
        name = "_env_python_linux_x86_64",
        constraint_values = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    )

    # buildifier: disable=unused-variable
    _target = select({
        ":_env_python_darwin_arm64": "@jvolkman_rules_pycross_example//:python_darwin_arm64",
        ":_env_python_darwin_x86_64": "@jvolkman_rules_pycross_example//:python_darwin_x86_64",
        ":_env_python_linux_x86_64": "@jvolkman_rules_pycross_example//:python_linux_x86_64",
    })

    _grpclib_0_4_6_deps = [
        ":h2_4.1.0",
        ":multidict_6.0.4",
    ]

    _grpclib_0_4_6_build_deps = [
        ":setuptools_68.2.2",
        ":wheel_0.41.3",
    ]

    pycross_wheel_build(
        name = "_build_grpclib_0.4.6",
        sdist = "@example_lock_sdist_grpclib_0.4.6//file",
        target_environment = _target,
        deps = _grpclib_0_4_6_deps + _grpclib_0_4_6_build_deps,
        tags = ["manual"],
    )

    py_wheel(
        name = "_wheel_grpclib_0.4.6",
        src = ":_build_grpclib_0.4.6",
    )

    py_library(
        name = "grpclib_0.4.6",
        deps = [":_wheel_grpclib_0.4.6"] + _grpclib_0_4_6_deps,
    )

    _h2_4_1_0_deps = [
        ":hpack_4.0.0",
        ":hyperframe_6.0.1",
    ]

    py_wheel(
        name = "_wheel_h2_4.1.0",
        src = "@example_lock_wheel_h2_4.1.0_py3_none_any//file",
    )

    py_library(
        name = "h2_4.1.0",
        deps = [":_wheel_h2_4.1.0"] + _h2_4_1_0_deps,
    )

    py_wheel(
        name = "_wheel_hpack_4.0.0",
        src = "@example_lock_wheel_hpack_4.0.0_py3_none_any//file",
    )

    py_library(
        name = "hpack_4.0.0",
        deps = [":_wheel_hpack_4.0.0"],
    )

    py_wheel(
        name = "_wheel_hyperframe_6.0.1",
        src = "@example_lock_wheel_hyperframe_6.0.1_py3_none_any//file",
    )

    py_library(
        name = "hyperframe_6.0.1",
        deps = [":_wheel_hyperframe_6.0.1"],
    )

    py_wheel(
        name = "_wheel_multidict_6.0.4",
        src = select({
            ":_env_python_darwin_arm64": "@example_lock_wheel_multidict_6.0.4_cp311_cp311_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_wheel_multidict_6.0.4_cp311_cp311_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@example_lock_wheel_multidict_6.0.4_cp311_cp311_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    py_library(
        name = "multidict_6.0.4",
        deps = [":_wheel_multidict_6.0.4"],
    )

    py_wheel(
        name = "_wheel_setuptools_68.2.2",
        src = "@example_lock_wheel_setuptools_68.2.2_py3_none_any//file",
    )

    py_library(
        name = "setuptools_68.2.2",
        deps = [":_wheel_setuptools_68.2.2"],
    )

    py_wheel(
        name = "_wheel_wheel_0.41.3",
        src = "@example_lock_wheel_wheel_0.41.3_py3_none_any//file",
    )

    py_library(
        name = "wheel_0.41.3",
        deps = [":_wheel_wheel_0.41.3"],
    )

# buildifier: disable=unnamed-macro
def repositories():
    """Generated package repositories."""

    maybe(
        http_file,
        name = "example_lock_sdist_grpclib_0.4.6",
        urls = [
            "https://files.pythonhosted.org/packages/55/80/66d4b36161996e75166f752408bb82eb04aeabcfdb487c5fd8dace72491a/grpclib-0.4.6.tar.gz",
        ],
        sha256 = "595d05236ca8b8f8e433f5bf6095e6354c1d8777d003ddaf5288efa9611e3fd6",
        downloaded_file_path = "grpclib-0.4.6.tar.gz",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_h2_4.1.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/2a/e5/db6d438da759efbb488c4f3fbdab7764492ff3c3f953132efa6b9f0e9e53/h2-4.1.0-py3-none-any.whl",
        ],
        sha256 = "03a46bcf682256c95b5fd9e9a99c1323584c3eec6440d379b9903d709476bc6d",
        downloaded_file_path = "h2-4.1.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_hpack_4.0.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/d5/34/e8b383f35b77c402d28563d2b8f83159319b509bc5f760b15d60b0abf165/hpack-4.0.0-py3-none-any.whl",
        ],
        sha256 = "84a076fad3dc9a9f8063ccb8041ef100867b1878b25ef0ee63847a5d53818a6c",
        downloaded_file_path = "hpack-4.0.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_hyperframe_6.0.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/d7/de/85a784bcc4a3779d1753a7ec2dee5de90e18c7bcf402e71b51fcf150b129/hyperframe-6.0.1-py3-none-any.whl",
        ],
        sha256 = "0ec6bafd80d8ad2195c4f03aacba3a8265e57bc4cff261e802bf39970ed02a15",
        downloaded_file_path = "hyperframe-6.0.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_multidict_6.0.4_cp311_cp311_macosx_10_9_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/3c/b3/1c8b525a7243c395a73d0ba35f4625333315c5261d01acc3bcde852a9548/multidict-6.0.4-cp311-cp311-macosx_10_9_x86_64.whl",
        ],
        sha256 = "64da238a09d6039e3bd39bb3aee9c21a5e34f28bfa5aa22518581f910ff94af3",
        downloaded_file_path = "multidict-6.0.4-cp311-cp311-macosx_10_9_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_multidict_6.0.4_cp311_cp311_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/59/28/e50cc24c56609d11f7232606f73981620e94e3445791d9501e21c4c73a61/multidict-6.0.4-cp311-cp311-macosx_11_0_arm64.whl",
        ],
        sha256 = "ff959bee35038c4624250473988b24f846cbeb2c6639de3602c073f10410ceba",
        downloaded_file_path = "multidict-6.0.4-cp311-cp311-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_multidict_6.0.4_cp311_cp311_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/9d/5a/34bd606569178ad8a931ea4d59cda926b046cfa4c01b0191c2e04cfd44c2/multidict-6.0.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        ],
        sha256 = "11bdf3f5e1518b24530b8241529d2050014c884cf18b6fc69c0c2b30ca248710",
        downloaded_file_path = "multidict-6.0.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_setuptools_68.2.2_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl",
        ],
        sha256 = "b454a35605876da60632df1a60f736524eb73cc47bbc9f3f1ef1b644de74fd2a",
        downloaded_file_path = "setuptools-68.2.2-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_wheel_wheel_0.41.3_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/fa/7f/4c07234086edbce4a0a446209dc0cb08a19bb206a3ea53b2f56a403f983b/wheel-0.41.3-py3-none-any.whl",
        ],
        sha256 = "488609bc63a29322326e05560731bf7bfea8e48ad646e1f5e40d366607de0942",
        downloaded_file_path = "wheel-0.41.3-py3-none-any.whl",
    )
